# Generated by Django 5.2.7 on 2026-01-13 14:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LingXingTemuShop',
            fields=[
                ('store_id', models.CharField(db_comment='领星返回的 store_id（主键）', max_length=64, primary_key=True, serialize=False)),
                ('sid', models.CharField(blank=True, db_comment='原始 sid', max_length=64, null=True)),
                ('store_name', models.CharField(blank=True, db_comment='店铺名称', max_length=255, null=True)),
                ('platform_code', models.CharField(blank=True, db_comment='平台编码', max_length=32, null=True)),
                ('platform_name', models.CharField(blank=True, db_comment='平台名称（Temu半托管）', max_length=100, null=True)),
                ('currency', models.CharField(blank=True, db_comment='币种', max_length=10, null=True)),
                ('is_sync', models.SmallIntegerField(blank=True, db_comment='是否同步（0/1）', null=True)),
                ('status', models.SmallIntegerField(blank=True, db_comment='状态（1=正常等）', null=True)),
                ('country_code', models.CharField(blank=True, db_comment='店铺国家码', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('temu_shop', models.ForeignKey(blank=True, db_comment='绑定的本地Temu店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lingxing_temu_shops', to='general.temushop')),
            ],
            options={
                'db_table': 'lingxing_temu_shop',
                'db_table_comment': '领星-Temu店铺信息表',
            },
        ),
        migrations.CreateModel(
            name='TemuOrder',
            fields=[
                ('global_order_no', models.CharField(db_comment='领星返回的 global_order_no（主键）', max_length=80, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(blank=True, db_comment='reference_no', max_length=80, null=True)),
                ('order_from_name', models.CharField(blank=True, db_comment='订单来源', max_length=100, null=True)),
                ('delivery_type', models.SmallIntegerField(blank=True, db_comment='配送类型', null=True)),
                ('split_type', models.CharField(blank=True, db_comment='拆分类型', max_length=20, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_comment='订单状态代码', db_index=True, null=True)),
                ('wid', models.CharField(blank=True, db_comment='仓库ID', max_length=64, null=True)),
                ('warehouse_name', models.CharField(blank=True, db_comment='仓库名称', max_length=255, null=True)),
                ('global_purchase_time', models.DateTimeField(blank=True, db_comment='下单时间', db_index=True, null=True)),
                ('global_payment_time', models.DateTimeField(blank=True, db_comment='付款时间', null=True)),
                ('global_review_time', models.DateTimeField(blank=True, db_comment='审核时间', null=True)),
                ('global_distribution_time', models.DateTimeField(blank=True, db_comment='分配时间', null=True)),
                ('global_print_time', models.DateTimeField(blank=True, db_comment='打印时间', null=True)),
                ('global_mark_time', models.DateTimeField(blank=True, db_comment='标记时间', null=True)),
                ('global_delivery_time', models.DateTimeField(blank=True, db_comment='发货时间', null=True)),
                ('global_create_time', models.CharField(blank=True, db_comment='创建时间字符串', max_length=50, null=True)),
                ('amount_currency', models.CharField(blank=True, db_comment='币种', max_length=10, null=True)),
                ('receiver_country_code', models.CharField(blank=True, db_comment='收货国家码（从 address_info 提取）', db_index=True, max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, db_comment='邮编（从 address_info 提取）', db_index=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_comment='城市（从 address_info 提取）', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, db_comment='物流单号（从 logistics_info 提取）', db_index=True, max_length=100, null=True)),
                ('logistics_provider_name', models.CharField(blank=True, db_comment='物流服务商（从 logistics_info 提取）', max_length=255, null=True)),
                ('order_total_amount', models.DecimalField(blank=True, db_comment='订单总金额（从 transaction_info 提取）', decimal_places=2, max_digits=12, null=True)),
                ('buyer_name_masked', models.CharField(blank=True, db_comment='买家姓名（脱敏）', max_length=200, null=True)),
                ('buyer_email_masked', models.CharField(blank=True, db_comment='买家邮箱（脱敏）', max_length=200, null=True)),
                ('order_tag', models.JSONField(blank=True, db_comment='订单标签数组', null=True)),
                ('pending_order_tag', models.JSONField(blank=True, null=True)),
                ('exception_order_tag', models.JSONField(blank=True, null=True)),
                ('buyers_info', models.JSONField(blank=True, db_comment='买家信息（原始 JSON）', null=True)),
                ('address_info', models.JSONField(blank=True, db_comment='收货地址（原始 JSON）', null=True)),
                ('platform_info', models.JSONField(blank=True, db_comment='平台信息数组', null=True)),
                ('payment_info', models.JSONField(blank=True, db_comment='支付信息数组', null=True)),
                ('logistics_info', models.JSONField(blank=True, db_comment='物流信息（原始 JSON）', null=True)),
                ('transaction_info', models.JSONField(blank=True, db_comment='交易信息数组', null=True)),
                ('supplier_id', models.CharField(blank=True, db_comment='供应商ID', max_length=64, null=True)),
                ('is_delete', models.SmallIntegerField(db_comment='是否删除标志', default=0)),
                ('order_custom_fields', models.JSONField(blank=True, db_comment='自定义字段', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间（本地）')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间（本地）')),
                ('lingxing_shop', models.ForeignKey(blank=True, db_comment='关联的领星 Temu 店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='temu.lingxingtemushop')),
                ('temu_shop', models.ForeignKey(blank=True, db_comment='关联的本地 TemuShop（冗余）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temu_orders', to='general.temushop')),
            ],
            options={
                'db_table': 'temu_orders',
                'db_table_comment': 'Temu 订单主表',
            },
        ),
        migrations.CreateModel(
            name='TemuOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_item_no', models.CharField(blank=True, db_comment='globalItemNo', max_length=80, null=True)),
                ('platform_order_no', models.CharField(blank=True, db_comment='平台订单号', db_index=True, max_length=120, null=True)),
                ('order_item_no', models.CharField(blank=True, db_comment='订单项编号', max_length=120, null=True)),
                ('item_from_name', models.CharField(blank=True, db_comment='商品来源', max_length=80, null=True)),
                ('msku', models.CharField(blank=True, db_comment='商品MSKU', db_index=True, max_length=200, null=True)),
                ('local_sku', models.CharField(blank=True, db_comment='本地SKU', db_index=True, max_length=200, null=True)),
                ('product_no', models.CharField(blank=True, db_comment='商品编号', max_length=80, null=True)),
                ('title', models.TextField(blank=True, db_comment='商品标题', null=True)),
                ('variant_attr', models.CharField(blank=True, db_comment='变体属性', max_length=255, null=True)),
                ('unit_price_amount', models.DecimalField(db_comment='单价', decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('item_price_amount', models.DecimalField(db_comment='商品总价', decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity', models.IntegerField(db_comment='数量', default=0)),
                ('platform_status', models.CharField(blank=True, db_comment='平台状态', db_index=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_comment='商品类型', max_length=50, null=True)),
                ('data_json', models.JSONField(blank=True, db_comment='原始 data_json 字段', null=True)),
                ('item_custom_fields', models.JSONField(blank=True, db_comment='自定义字段', null=True)),
                ('is_delete', models.SmallIntegerField(db_comment='是否删除', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('order', models.ForeignKey(db_column='global_order_no', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='temu.temuorder')),
            ],
            options={
                'db_table': 'temu_order_item',
                'db_table_comment': 'Temu 订单商品明细',
            },
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['status', 'global_purchase_time'], name='idx_status_time'),
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['lingxing_shop', 'status'], name='idx_shop_status'),
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['receiver_country_code', 'postal_code'], name='idx_address'),
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['tracking_number'], name='idx_tracking'),
        ),
        migrations.AddIndex(
            model_name='temuorderitem',
            index=models.Index(fields=['msku', 'platform_status'], name='idx_msku_status'),
        ),
        migrations.AddIndex(
            model_name='temuorderitem',
            index=models.Index(fields=['platform_order_no'], name='idx_platform_order'),
        ),
    ]
