# Generated by Django 5.2.7 on 2026-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temuorder',
            name='divi_audit_time',
            field=models.DateTimeField(blank=True, db_comment='订单审核通过时间', null=True, verbose_name='DIVI审核时间'),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_dispatch_time',
            field=models.DateTimeField(blank=True, db_comment='订单派发给仓库时间(sendOrderTime)', null=True, verbose_name='DIVI派单时间'),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_goods_payment_total',
            field=models.DecimalField(blank=True, db_comment='货款总计', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_import_time',
            field=models.DateTimeField(blank=True, db_comment='订单导入DIVI系统时间(createTime)', null=True, verbose_name='DIVI导入时间'),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_logistics_method',
            field=models.CharField(blank=True, db_comment='物流渠道名称(logisticsMethodName)', max_length=100, null=True, verbose_name='DIVI物流方式'),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_order_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '取消订单'), (1, '未付货款'), (2, '未审核'), (3, '排单中'), (4, '生产中'), (5, '已发货')], db_comment='DIVI系统订单状态(status)', null=True, verbose_name='DIVI订单状态'),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_payment_time',
            field=models.DateTimeField(blank=True, db_comment='买家付款时间(paymentTime)', null=True, verbose_name='DIVI付款时间'),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_shipment_time',
            field=models.DateTimeField(blank=True, db_comment='仓库实际发货时间(sendGoodsTime)', null=True, verbose_name='DIVI发货时间'),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_shipping_amount',
            field=models.DecimalField(blank=True, db_comment='运费金额', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='divi_tracking_number',
            field=models.CharField(blank=True, db_comment='物流跟踪号(trackingNumber)', max_length=100, null=True, verbose_name='DIVI跟踪号'),
        ),
    ]
