# Generated by Django 5.2.7 on 2025-11-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temuorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_order_no',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='order',
            field=models.ForeignKey(db_column='global_order_no', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Temu.temuorder'),
        ),
    ]
