# Generated by Django 5.2.7 on 2025-11-27 14:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0011_user_remark'),
        ('Temu', '0002_remove_temuorder_id_alter_temuorder_global_order_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='temuorder',
            name='uniq_lingxing_shop_global_order_no',
        ),
        migrations.RemoveIndex(
            model_name='temuorderitem',
            name='temu_order__msku_db2c6a_idx',
        ),
        migrations.RenameIndex(
            model_name='temuorderitem',
            new_name='idx_platform_order',
            old_name='temu_order__platfor_853e93_idx',
        ),
        migrations.RemoveField(
            model_name='temuorder',
            name='global_create_datetime',
        ),
        migrations.AddField(
            model_name='temuorder',
            name='buyer_email_masked',
            field=models.CharField(blank=True, db_comment='买家邮箱（脱敏）', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='buyer_name_masked',
            field=models.CharField(blank=True, db_comment='买家姓名（脱敏）', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='city',
            field=models.CharField(blank=True, db_comment='城市（从 address_info 提取）', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='logistics_provider_name',
            field=models.CharField(blank=True, db_comment='物流服务商（从 logistics_info 提取）', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='order_total_amount',
            field=models.DecimalField(blank=True, db_comment='订单总金额（从 transaction_info 提取）', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='postal_code',
            field=models.CharField(blank=True, db_comment='邮编（从 address_info 提取）', db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='receiver_country_code',
            field=models.CharField(blank=True, db_comment='收货国家码（从 address_info 提取）', db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='temuorder',
            name='tracking_number',
            field=models.CharField(blank=True, db_comment='物流单号（从 logistics_info 提取）', db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='address_info',
            field=models.JSONField(blank=True, db_comment='收货地址（原始 JSON）', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='amount_currency',
            field=models.CharField(blank=True, db_comment='币种', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='delivery_type',
            field=models.SmallIntegerField(blank=True, db_comment='配送类型', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_create_time',
            field=models.CharField(blank=True, db_comment='创建时间字符串', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_delivery_time',
            field=models.DateTimeField(blank=True, db_comment='发货时间', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_distribution_time',
            field=models.DateTimeField(blank=True, db_comment='分配时间', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_mark_time',
            field=models.DateTimeField(blank=True, db_comment='标记时间', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_order_no',
            field=models.CharField(db_comment='领星返回的 global_order_no（主键）', max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_payment_time',
            field=models.DateTimeField(blank=True, db_comment='付款时间', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_print_time',
            field=models.DateTimeField(blank=True, db_comment='打印时间', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_purchase_time',
            field=models.DateTimeField(blank=True, db_comment='下单时间', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='global_review_time',
            field=models.DateTimeField(blank=True, db_comment='审核时间', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='is_delete',
            field=models.SmallIntegerField(db_comment='是否删除标志', default=0),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='logistics_info',
            field=models.JSONField(blank=True, db_comment='物流信息（原始 JSON）', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='order_from_name',
            field=models.CharField(blank=True, db_comment='订单来源', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='order_tag',
            field=models.JSONField(blank=True, db_comment='订单标签数组', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='platform_info',
            field=models.JSONField(blank=True, db_comment='平台信息数组', null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='split_type',
            field=models.CharField(blank=True, db_comment='拆分类型', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='status',
            field=models.SmallIntegerField(blank=True, db_comment='订单状态代码', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='supplier_id',
            field=models.CharField(blank=True, db_comment='供应商ID', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='temu_shop',
            field=models.ForeignKey(blank=True, db_comment='关联的本地 TemuShop（冗余）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temu_orders', to='General.temushop'),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='warehouse_name',
            field=models.CharField(blank=True, db_comment='仓库名称', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='temuorder',
            name='wid',
            field=models.CharField(blank=True, db_comment='仓库ID', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='is_delete',
            field=models.SmallIntegerField(db_comment='是否删除', default=0),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='item_custom_fields',
            field=models.JSONField(blank=True, db_comment='自定义字段', null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='item_from_name',
            field=models.CharField(blank=True, db_comment='商品来源', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='item_price_amount',
            field=models.DecimalField(db_comment='商品总价', decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='local_sku',
            field=models.CharField(blank=True, db_comment='本地SKU', db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='msku',
            field=models.CharField(blank=True, db_comment='商品MSKU', db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='order_item_no',
            field=models.CharField(blank=True, db_comment='订单项编号', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='platform_order_no',
            field=models.CharField(blank=True, db_comment='平台订单号', db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='platform_status',
            field=models.CharField(blank=True, db_comment='平台状态', db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='product_no',
            field=models.CharField(blank=True, db_comment='商品编号', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='quantity',
            field=models.IntegerField(db_comment='数量', default=0),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='title',
            field=models.TextField(blank=True, db_comment='商品标题', null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='type',
            field=models.CharField(blank=True, db_comment='商品类型', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='unit_price_amount',
            field=models.DecimalField(db_comment='单价', decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='temuorderitem',
            name='variant_attr',
            field=models.CharField(blank=True, db_comment='变体属性', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['status', 'global_purchase_time'], name='idx_status_time'),
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['lingxing_shop', 'status'], name='idx_shop_status'),
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['receiver_country_code', 'postal_code'], name='idx_address'),
        ),
        migrations.AddIndex(
            model_name='temuorder',
            index=models.Index(fields=['tracking_number'], name='idx_tracking'),
        ),
        migrations.AddIndex(
            model_name='temuorderitem',
            index=models.Index(fields=['msku', 'platform_status'], name='idx_msku_status'),
        ),
    ]
