# Generated by Django 5.2.7 on 2026-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temu', '0002_temuorder_divi_audit_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temuorder',
            name='divi_if_order',
            field=models.BooleanField(db_comment='是否在DIVI系统存在对应订单', default=False, verbose_name='是否DIVI订单'),
        ),
    ]
