# Generated by Django 5.2.7 on 2026-04-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temu', '0003_temuorder_divi_if_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemuSKU',
            fields=[
                ('temu_sku', models.CharField(db_comment='Temu平台SKU货号（主键）', max_length=200, primary_key=True, serialize=False)),
                ('length_cm', models.DecimalField(blank=True, db_comment='长度（cm）', decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, db_comment='宽度（cm）', decimal_places=2, max_digits=10, null=True)),
                ('height_cm', models.DecimalField(blank=True, db_comment='高度（cm）', decimal_places=2, max_digits=10, null=True)),
                ('weight_g', models.DecimalField(blank=True, db_comment='重量（g）', decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'temu_sku_mapping',
                'db_table_comment': 'Temu SKU 规格表',
            },
        ),
    ]
