# Generated by Django 5.2.7 on 2026-01-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_permissionconfig_user_permission_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshop',
            name='qupital_if',
            field=models.BooleanField(db_comment='是否绑定qupital', default=False),
        ),
    ]
