# Generated by Django 5.2.7 on 2026-01-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_company_settings_operationalaccount_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshop',
            name='company',
            field=models.ForeignKey(db_comment='数据隔离边界，不可变更', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='amazon_shops', to='general.company', verbose_name='所属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amazonshop',
            name='project',
            field=models.ForeignKey(db_comment='业务分组标签，可自由迁移', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='amazon_shops', to='general.project', verbose_name='所属项目'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='amazonshop',
            index=models.Index(fields=['company', 'project'], name='idx_shop_company_project'),
        ),
        migrations.AddIndex(
            model_name='amazonshop',
            index=models.Index(fields=['company', 'ops'], name='idx_shop_company_ops'),
        ),
    ]
