# Generated by Django 5.2.7 on 2026-01-29 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_temushop_company_temushop_project'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='groupperformancetarget',
            name='group_perfo_month_714097_idx',
        ),
        migrations.RemoveIndex(
            model_name='personalperformancetarget',
            name='personal_pe_month_a63571_idx',
        ),
        migrations.AlterUniqueTogether(
            name='groupperformancetarget',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='personalperformancetarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groupperformancetarget',
            name='company',
            field=models.ForeignKey(db_comment='数据隔离边界', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='group_targets', to='general.company', verbose_name='所属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalperformancetarget',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='personal_targets', to='general.company', verbose_name='所属公司'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='groupperformancetarget',
            unique_together={('company', 'ops_group', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='personalperformancetarget',
            unique_together={('company', 'user', 'month')},
        ),
        migrations.AddIndex(
            model_name='groupperformancetarget',
            index=models.Index(fields=['company', 'month', 'ops_group'], name='group_perfo_company_157678_idx'),
        ),
        migrations.AddIndex(
            model_name='personalperformancetarget',
            index=models.Index(fields=['company', 'month', 'ops_group'], name='personal_pe_company_aea499_idx'),
        ),
    ]
