# Generated by Django 5.2.7 on 2026-03-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'divi_product',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color_classify_id', models.IntegerField(verbose_name='颜色分类ID')),
                ('color_name', models.CharField(max_length=100, verbose_name='颜色名称')),
                ('en_name', models.CharField(max_length=100, verbose_name='颜色英文名')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='divi.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品颜色',
                'verbose_name_plural': '产品颜色',
                'db_table': 'divi_product_color',
                'unique_together': {('product', 'color_classify_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_size_id', models.IntegerField(verbose_name='尺寸ID')),
                ('product_size_name', models.CharField(max_length=100, verbose_name='尺寸名称')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='divi.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品尺寸',
                'verbose_name_plural': '产品尺寸',
                'db_table': 'divi_product_size',
                'unique_together': {('product', 'product_size_id')},
            },
        ),
    ]
