# Generated by Django 5.2.7 on 2026-04-11 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divi', '0001_initial'),
        ('general', '0030_alter_amazonshop_divi_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiviExportTemplate',
            fields=[
                ('template_id', models.IntegerField(db_comment='DIVI 系统的模板ID (amazonTemplateId)', primary_key=True, serialize=False, verbose_name='模板ID')),
                ('template_name', models.CharField(blank=True, db_comment='模板名称，如：美国-所有帽子-10.99-吴晓云-29曹家勇_2169', max_length=255, null=True, verbose_name='模板名称')),
                ('product_type', models.CharField(blank=True, db_comment='产品类型，如：hat, shirt, decorativesignage 等', max_length=100, null=True, verbose_name='产品类型')),
                ('synced_at', models.DateTimeField(auto_now=True, db_comment='最近一次从 DIVI 同步的时间', verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('company', models.ForeignKey(blank=True, db_comment='数据隔离边界', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divi_export_templates', to='general.company', verbose_name='所属公司')),
                ('products', models.ManyToManyField(blank=True, db_comment='该模板关联的 DIVI 产品列表', related_name='export_templates', to='divi.product', verbose_name='关联产品')),
                ('shops', models.ManyToManyField(blank=True, db_comment='该模板关联的亚马逊店铺（通过 divi_shop_id 关联）', related_name='divi_export_templates', to='general.amazonshop', verbose_name='关联店铺')),
            ],
            options={
                'verbose_name': 'DIVI 汇出模板',
                'verbose_name_plural': 'DIVI 汇出模板',
                'db_table': 'divi_export_templates',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['company', 'synced_at'], name='idx_divi_tpl_company_synced'), models.Index(fields=['product_type'], name='idx_divi_tpl_product_type')],
            },
        ),
    ]
