# Generated by Django 5.2.7 on 2026-04-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divi', '0002_diviexporttemplate'),
        ('general', '0030_alter_amazonshop_divi_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diviexporttemplate',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='export_templates', to='divi.product', verbose_name='关联产品'),
        ),
        migrations.AlterField(
            model_name='diviexporttemplate',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='divi_export_templates', to='general.amazonshop', verbose_name='关联店铺'),
        ),
        migrations.CreateModel(
            name='DiviImageClassify',
            fields=[
                ('id', models.IntegerField(db_comment='DIVI 系统的分类ID', primary_key=True, serialize=False, verbose_name='分类ID')),
                ('label', models.CharField(db_comment='分类显示名称，如"10月"、"10.7天空"', max_length=255, verbose_name='显示名称')),
                ('technology_name', models.CharField(blank=True, db_comment='技术分类名称，如"印花"', max_length=100, null=True, verbose_name='技术名称')),
                ('level', models.IntegerField(db_comment='层级深度，0=根节点，1=一级，以此类推', default=0, verbose_name='层级')),
                ('path', models.CharField(blank=True, db_comment='完整路径，如"/100000/117298/117299"，便于查询子树', max_length=500, null=True, verbose_name='完整路径')),
                ('sort_order', models.IntegerField(db_comment='同层级内的排序', default=0, verbose_name='排序')),
                ('synced_at', models.DateTimeField(auto_now=True, db_comment='最近一次从 DIVI 同步的时间', verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, db_comment='父分类ID，根节点为null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='divi.diviimageclassify', verbose_name='父节点')),
            ],
            options={
                'verbose_name': 'DIVI 图库分类',
                'verbose_name_plural': 'DIVI 图库分类',
                'db_table': 'divi_image_classify',
                'ordering': ['level', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['parent', 'sort_order'], name='idx_divi_img_parent_sort'), models.Index(fields=['level'], name='idx_divi_img_level'), models.Index(fields=['path'], name='idx_divi_img_path')],
            },
        ),
    ]
