# Generated by Django 5.2.7 on 2026-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divi', '0003_alter_diviexporttemplate_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diviimageclassify',
            options={'ordering': ['username', 'level', 'sort_order', 'id'], 'verbose_name': 'DIVI 图库分类', 'verbose_name_plural': 'DIVI 图库分类'},
        ),
        migrations.AddField(
            model_name='diviimageclassify',
            name='username',
            field=models.CharField(blank=True, db_comment='同步数据的 DIVI 账号，如 YMX-26', max_length=100, null=True, verbose_name='DIVI 账号'),
        ),
        migrations.AddIndex(
            model_name='diviimageclassify',
            index=models.Index(fields=['username'], name='idx_divi_img_username'),
        ),
    ]
