# Generated by Django 5.2.7 on 2026-04-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divi', '0004_alter_diviimageclassify_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diviexporttemplate',
            name='template_type',
            field=models.IntegerField(db_comment='模板类型标识', default=0, verbose_name='模板类型'),
        ),
        migrations.AddField(
            model_name='diviexporttemplate',
            name='username',
            field=models.CharField(blank=True, db_comment='同步数据的 DIVI 账号，如 YMX-26', max_length=100, null=True, verbose_name='DIVI 账号'),
        ),
    ]
