# Generated by Django 5.2.7 on 2026-03-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_week', models.DateField(db_index=True, help_text='格式：YYYY-MM-DD（周日），作为分区键', verbose_name='数据周')),
                ('search_frequency_rank', models.IntegerField(db_index=True, verbose_name='搜索频率排名')),
                ('asin_1_code', models.CharField(db_index=True, max_length=20, verbose_name='ASIN-1')),
                ('asin_1_title', models.TextField(verbose_name='标题-1')),
                ('asin_1_click_share', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='点击份额-1')),
                ('asin_1_conversion_share', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='转化份额-1')),
                ('asin_2_code', models.CharField(blank=True, max_length=20, verbose_name='ASIN-2')),
                ('asin_2_title', models.TextField(blank=True, verbose_name='标题-2')),
                ('asin_2_click_share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='点击份额-2')),
                ('asin_2_conversion_share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='转化份额-2')),
                ('asin_3_code', models.CharField(blank=True, max_length=20, verbose_name='ASIN-3')),
                ('asin_3_title', models.TextField(blank=True, verbose_name='标题-3')),
                ('asin_3_click_share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='点击份额-3')),
                ('asin_3_conversion_share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='转化份额-3')),
                ('last_week_rank', models.IntegerField(blank=True, null=True, verbose_name='上周排名')),
                ('rank_change', models.IntegerField(blank=True, help_text='正数表示上升（如+5），负数表示下降（如-3）', null=True, verbose_name='排名变化')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': '搜索词周数据',
                'verbose_name_plural': '搜索词周数据',
                'db_table': 'search_term_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='搜索词')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='品类')),
                ('first_seen', models.DateField(verbose_name='首次出现周')),
                ('last_seen', models.DateField(verbose_name='最后更新周')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '搜索词',
                'verbose_name_plural': '搜索词',
                'db_table': 'search_terms',
            },
        ),
    ]
