# Generated by Django 5.2.7 on 2026-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='denoising',
            field=models.BooleanField(default=False, help_text='人工标记已降噪的搜索词，后续导入', verbose_name='是否已降噪'),
        ),
    ]
