# Generated by Django 5.2.7 on 2026-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0002_searchterm_denoising'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbaReportWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_week', models.DateField(db_index=True, unique=True, verbose_name='数据周')),
                ('display_label', models.CharField(max_length=64, verbose_name='展示文案')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('import_status', models.CharField(db_index=True, default='ready', max_length=20, verbose_name='导入状态')),
                ('record_count', models.IntegerField(default=0, verbose_name='数据条数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'ABA数据周期',
                'verbose_name_plural': 'ABA数据周期',
                'db_table': 'aba_report_weeks',
                'ordering': ['-report_week'],
            },
        ),
    ]
