# Generated by Django 5.2.7 on 2026-03-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0003_abareportweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchterm',
            name='translation_cn',
            field=models.CharField(max_length=500, null=True, verbose_name='搜索词中文翻译'),
        ),
    ]
