# Generated by Django 5.2.7 on 2026-03-20 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0004_searchterm_translation_cn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbaNoiseWord',
            fields=[
                ('word', models.CharField(help_text='需要去噪的词语', max_length=100, primary_key=True, serialize=False, verbose_name='去噪词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_noise_words', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'ABA去噪词',
                'verbose_name_plural': 'ABA去噪词库',
                'db_table': 'aba_noise_words',
                'ordering': ['word'],
            },
        ),
    ]
