# Generated by Django 5.2.7 on 2026-03-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0005_abanoiseword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abanoiseword',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='abanoiseword',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abanoiseword',
            name='updated_at',
        ),
    ]
