# Generated by Django 5.2.7 on 2026-03-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0006_remove_abanoiseword_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['category', 'denoising'], name='category_denoising_idx'),
        ),
        migrations.AddIndex(
            model_name='searchterm',
            index=models.Index(fields=['denoising', 'category'], name='denoising_category_idx'),
        ),
    ]
