# Generated by Django 5.2.7 on 2026-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aba', '0007_searchterm_category_denoising_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abareportweek',
            name='id',
        ),
        migrations.AlterField(
            model_name='abareportweek',
            name='report_week',
            field=models.DateField(db_index=True, primary_key=True, serialize=False, verbose_name='数据周'),
        ),
    ]
