# Generated by Django 5.2.7 on 2026-02-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon', '0006_lingxingamazonshop_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LingXingAdHourlyData',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('campaign_id', models.BigIntegerField(db_comment='广告活动ID（逻辑关联 LingXingCampaign）', db_index=True, verbose_name='Campaign ID')),
                ('ad_group_id', models.BigIntegerField(db_comment='广告组ID', verbose_name='Ad Group ID')),
                ('ad_id', models.BigIntegerField(db_comment='广告条目ID（Product Ad ID）', db_index=True, verbose_name='广告ID')),
                ('targeting_id', models.BigIntegerField(db_comment='投放词ID（Targeting，同一个ad_id可能有多个targeting）', verbose_name='投放ID')),
                ('report_date', models.DateField(db_comment='报表日期（YYYY-MM-DD），分区键', help_text='PostgreSQL按月分区', verbose_name='报表日期')),
                ('hour', models.SmallIntegerField(db_comment='小时（0-23）', verbose_name='小时')),
                ('asin', models.CharField(db_comment='亚马逊商品编码（冗余存储，用于分组查询）', db_index=True, max_length=10, verbose_name='ASIN')),
                ('msku', models.CharField(blank=True, db_comment='本地SKU（冗余存储）', max_length=100, null=True, verbose_name='MSKU')),
                ('targeting', models.CharField(blank=True, db_comment='定位内容（可能是关键词、ASIN或类目）', max_length=255, null=True, verbose_name='投放词')),
                ('match_type', models.CharField(blank=True, choices=[('BROAD', '宽泛匹配'), ('EXACT', '精准匹配'), ('PHRASE', '词组匹配')], db_comment='匹配类型（BROAD/EXACT/PHRASE，targeting为ASIN时可能为空）', max_length=20, null=True, verbose_name='匹配类型')),
                ('impressions', models.IntegerField(db_comment='曝光次数', default=0, verbose_name='曝光量')),
                ('clicks', models.IntegerField(db_comment='点击次数', default=0, verbose_name='点击量')),
                ('cost', models.DecimalField(db_comment='广告花费（站点币种）', decimal_places=2, default=0, max_digits=12, verbose_name='花费')),
                ('orders', models.IntegerField(db_comment='广告订单数', default=0, verbose_name='订单数')),
                ('sales', models.DecimalField(db_comment='广告销售额（站点币种）', decimal_places=2, default=0, max_digits=12, verbose_name='销售额')),
                ('units', models.IntegerField(db_comment='售出商品数量', default=0, verbose_name='销量')),
                ('same_orders', models.IntegerField(db_comment='同品类订单数（品牌光环效应）', default=0, verbose_name='同品类订单')),
                ('same_sales', models.DecimalField(db_comment='同品类销售额', decimal_places=2, default=0, max_digits=12, verbose_name='同品类销售')),
                ('same_units', models.IntegerField(db_comment='同品类售出数量', default=0, verbose_name='同品类销量')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='写入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('lingxing_shop', models.ForeignKey(db_comment='关联领星店铺（级联删除）', on_delete=django.db.models.deletion.CASCADE, related_name='ad_hourly_data', to='amazon.lingxingamazonshop', verbose_name='领星店铺')),
            ],
            options={
                'verbose_name': '领星广告小时数据',
                'verbose_name_plural': '领星广告小时数据',
                'db_table': 'ad_hourly_data',
                'indexes': [models.Index(fields=['lingxing_shop', 'asin', 'report_date'], name='idx_ad_asin_date'), models.Index(fields=['report_date', 'hour'], name='idx_ad_datetime'), models.Index(fields=['campaign_id', 'report_date'], name='idx_ad_campaign_date'), models.Index(fields=['ad_id', 'report_date'], name='idx_ad_adid_date')],
                'unique_together': {('lingxing_shop', 'report_date', 'hour', 'ad_id', 'targeting_id')},
            },
        ),
        migrations.CreateModel(
            name='LingXingCampaign',
            fields=[
                ('campaign_id', models.BigIntegerField(db_comment='领星广告活动ID（亚马逊全局唯一）', primary_key=True, serialize=False, verbose_name='Campaign ID')),
                ('campaign_name', models.CharField(blank=True, db_comment='广告活动名称（可修改，此处存最新值）', max_length=200, null=True, verbose_name='活动名称')),
                ('campaign_type', models.CharField(blank=True, choices=[('SP', 'SP（商品推广）'), ('SB', 'SB（品牌推广）'), ('SD', 'SD（展示型推广）')], db_comment='广告活动类型', max_length=20, null=True, verbose_name='活动类型')),
                ('status', models.CharField(blank=True, choices=[('enabled', '启用'), ('paused', '暂停'), ('archived', '归档')], db_comment='活动状态（enabled/paused/archived）', max_length=20, null=True, verbose_name='状态')),
                ('serving_status', models.CharField(blank=True, choices=[('CAMPAIGN_PAUSED', '活动暂停'), ('CAMPAIGN_STATUS_ENABLED', '活动启用'), ('CAMPAIGN_OUT_OF_BUDGET', '活动预算不足'), ('CAMPAIGN_ARCHIVED', '已归档'), ('ACCOUNT_OUT_OF_BUDGET', '账户预算不足'), ('CAMPAIGN_INCOMPLETE', '设置不完整')], db_comment='实时投放状态', max_length=50, null=True, verbose_name='投放状态')),
                ('targeting_type', models.CharField(blank=True, choices=[('manual', '手动投放'), ('auto', '自动投放')], db_comment='targeting类型（manual/auto）', max_length=20, null=True, verbose_name='投放方式')),
                ('daily_budget', models.DecimalField(blank=True, db_comment='每日预算（站点币种）', decimal_places=2, max_digits=12, null=True, verbose_name='日预算')),
                ('bidding', models.JSONField(blank=True, db_comment='竞价策略JSON', default=dict, null=True, verbose_name='竞价策略')),
                ('portfolio_id', models.BigIntegerField(blank=True, db_comment='广告组合ID', null=True, verbose_name='Portfolio ID')),
                ('start_date', models.DateField(blank=True, db_comment='活动开始日期', null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, db_comment='活动结束日期', null=True, verbose_name='结束日期')),
                ('creation_date', models.DateField(blank=True, db_comment='活动创建日期', null=True, verbose_name='创建日期')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_comment='首次同步到系统的时间', verbose_name='首次发现时间')),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_comment='最后同步更新时间', verbose_name='最后更新时间')),
                ('lingxing_shop', models.ForeignKey(db_comment='关联领星店铺', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='amazon.lingxingamazonshop', verbose_name='领星店铺')),
            ],
            options={
                'verbose_name': '领星Campaign维度',
                'verbose_name_plural': '领星Campaign维度',
                'db_table': 'ad_lingxing_campaigns',
                'indexes': [models.Index(fields=['lingxing_shop', 'status'], name='idx_campaign_shop_status'), models.Index(fields=['campaign_type'], name='idx_campaign_type'), models.Index(fields=['targeting_type'], name='idx_campaign_targeting')],
            },
        ),
    ]
