# Generated by Django 5.2.7 on 2026-02-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
        ('amazon', '0007_amazonlisting_risk_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LingXingAdDailyData',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('campaign_id', models.BigIntegerField(db_comment='广告活动ID（逻辑关联 LingXingCampaign）', db_index=True, verbose_name='Campaign ID')),
                ('ad_group_id', models.BigIntegerField(db_comment='广告组ID', verbose_name='Ad Group ID')),
                ('ad_group_name', models.CharField(blank=True, db_comment='广告组名称（冗余存储）', max_length=200, null=True, verbose_name='广告组名称')),
                ('campaign_name', models.CharField(blank=True, db_comment='广告活动名称（冗余存储）', max_length=200, null=True, verbose_name='广告活动名称')),
                ('ad_id', models.BigIntegerField(db_comment='广告条目ID（Product Ad ID）', db_index=True, verbose_name='广告ID')),
                ('targeting_id', models.BigIntegerField(db_comment='投放词ID（Targeting，同一个ad_id可能有多个targeting）', verbose_name='投放ID')),
                ('report_date', models.DateField(db_comment='报表日期（YYYY-MM-DD），分区键', help_text='PostgreSQL按月分区', verbose_name='报表日期')),
                ('asin', models.CharField(db_comment='亚马逊商品编码（冗余存储，用于分组查询）', db_index=True, max_length=10, verbose_name='ASIN')),
                ('msku', models.CharField(blank=True, db_comment='本地SKU（冗余存储）', max_length=100, null=True, verbose_name='MSKU')),
                ('targeting', models.CharField(blank=True, db_comment='定位内容（可能是关键词、ASIN或类目）', max_length=255, null=True, verbose_name='投放词')),
                ('match_type', models.CharField(blank=True, choices=[('BROAD', '宽泛匹配'), ('EXACT', '精准匹配'), ('PHRASE', '词组匹配')], db_comment='匹配类型（BROAD/EXACT/PHRASE，targeting为ASIN时可能为空）', max_length=20, null=True, verbose_name='匹配类型')),
                ('impressions', models.IntegerField(db_comment='曝光次数', default=0, verbose_name='曝光量')),
                ('clicks', models.IntegerField(db_comment='点击次数', default=0, verbose_name='点击量')),
                ('cost', models.DecimalField(db_comment='广告花费（站点币种）', decimal_places=2, default=0, max_digits=12, verbose_name='花费')),
                ('orders', models.IntegerField(db_comment='广告订单数', default=0, verbose_name='订单数')),
                ('sales', models.DecimalField(db_comment='广告销售额（站点币种）', decimal_places=2, default=0, max_digits=12, verbose_name='销售额')),
                ('units', models.IntegerField(db_comment='售出商品数量', default=0, verbose_name='销量')),
                ('same_orders', models.IntegerField(db_comment='同品类订单数（品牌光环效应）', default=0, verbose_name='同品类订单')),
                ('same_sales', models.DecimalField(db_comment='同品类销售额', decimal_places=2, default=0, max_digits=12, verbose_name='同品类销售')),
                ('same_units', models.IntegerField(db_comment='同品类售出数量', default=0, verbose_name='同品类销量')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='写入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('lingxing_shop', models.ForeignKey(db_comment='关联领星店铺（级联删除）', on_delete=django.db.models.deletion.CASCADE, related_name='ad_daily_data', to='amazon.lingxingamazonshop', verbose_name='领星店铺')),
            ],
            options={
                'verbose_name': '领星广告天数据',
                'verbose_name_plural': '领星广告天数据',
                'db_table': 'ad_daily_data',
            },
        ),
        migrations.DeleteModel(
            name='LingXingAdHourlyData',
        ),
        migrations.AddIndex(
            model_name='lingxingaddailydata',
            index=models.Index(fields=['lingxing_shop', 'asin', 'report_date'], name='idx_ad_asin_date'),
        ),
        migrations.AddIndex(
            model_name='lingxingaddailydata',
            index=models.Index(fields=['campaign_id', 'report_date'], name='idx_ad_campaign_date'),
        ),
        migrations.AddIndex(
            model_name='lingxingaddailydata',
            index=models.Index(fields=['ad_id', 'report_date'], name='idx_ad_adid_date'),
        ),
        migrations.AlterUniqueTogether(
            name='lingxingaddailydata',
            unique_together={('lingxing_shop', 'report_date', 'ad_id', 'targeting_id')},
        ),
    ]
