"""
Django settings for Overlord project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

import mimetypes

mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))  # 必须加这行
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h_9nrs(_rj5nx%qez^+r+9j6)6tskga!04$b#zlg1%zlikh0ts'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False  # Django 不强制跳转
SESSION_COOKIE_SECURE = False  # 允许 HTTP 和 HTTPS 传输
CSRF_COOKIE_SECURE = False  # 同样允许 HTTP 和 HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # 宽松模式，兼容内外网
CSRF_TRUSTED_ORIGINS = [
    'https://ztzf.cpolar.cn',
    'http://192.168.110.54:5555',
    'http://192.168.110.131:5550',
    'http://192.168.110.196:8000',
    'http://localhost',
]

ALLOWED_HOSTS = [
    '192.168.110.131',
    '192.168.110.54',
    'localhost',
    '127.0.0.1',
    '192.168.110.196',
    'ztzf.cpolar.cn'

]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'general.apps.GeneralConfig',
    'amazon.apps.AmazonConfig',
    'temu.apps.TemuConfig',
    'track.apps.TrackConfig',
    'yuser.apps.YuserConfig',
    'zother.apps.ZotherConfig',
    'theme.apps.ThemeConfig',
    'task.apps.TaskConfig',
    'shop_guard.apps.ShopGuardConfig',
    'inventory.apps.InventoryConfig',
    'data_req.apps.DataReqConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 新增：
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'general.middleware.login_required.LoginRequiredMiddleware',
    'general.middleware.announcement.AnnouncementMiddleware',
    'general.middleware.middleware.ThemeMiddleware'

]

ROOT_URLCONF = 'Overlord.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'general.context_processors.announcements_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'Overlord.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        # "HOST": "2.tcp.cpolar.cn",
        "HOST": "192.168.110.54",
        "PORT": "5432",
        # "PORT": "12763",

        "NAME": os.getenv('DB_NAME', 'overlord_db'),  # ✅ 数据库名
        "USER": os.getenv('DB_USER', 'track'),  # ✅ 用户名
        "PASSWORD": os.getenv('DB_PASSWORD'),  # ✅ 密码从环境变量读
        "CONN_MAX_AGE": 60,  # 连接池：长连接，单位秒（生产可调大一些）
        "ATOMIC_REQUESTS": True,  # 每个请求包裹在事务中（出错自动回滚）
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = False

AUTH_USER_MODEL = 'general.User'  # 你的自定义用户模型路径

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / 'media'  # 或者可以设置为 D:/Y-Project/Overlord/media

# 用户通过 URL 访问媒体文件时使用的路径
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

