# Generated by Django 5.2.7 on 2026-01-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='工厂名称')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工厂信息',
                'verbose_name_plural': '工厂信息',
                'db_table': 'inventory_factory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosku', models.CharField(db_index=True, max_length=100, verbose_name='MOSKU编码')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='供应商名称')),
                ('product_name', models.CharField(db_index=True, max_length=300, verbose_name='产品名称')),
                ('color', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='颜色')),
                ('size', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='尺码')),
                ('location', models.CharField(db_index=True, max_length=100, verbose_name='库位')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='库存数量')),
                ('factory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.factory', verbose_name='工厂')),
            ],
            options={
                'verbose_name': '库存主数据',
                'verbose_name_plural': '库存主数据',
                'db_table': 'inventory_master',
            },
        ),
        migrations.CreateModel(
            name='InventoryDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('available_qty', models.IntegerField(default=0, verbose_name='可用数量')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='inventory.inventorymaster', verbose_name='库存主数据')),
            ],
            options={
                'verbose_name': '每日库存快照',
                'verbose_name_plural': '每日库存快照',
                'db_table': 'inventory_daily',
            },
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['factory', 'mosku'], name='inventory_m_factory_137984_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['product_name', 'color', 'size'], name='inventory_m_product_f443c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorymaster',
            constraint=models.UniqueConstraint(fields=('mosku', 'factory'), name='unique_mosku_factory'),
        ),
        migrations.AddIndex(
            model_name='inventorydaily',
            index=models.Index(fields=['date', 'inventory'], name='inventory_d_date_efcf1f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorydaily',
            index=models.Index(fields=['inventory', '-date'], name='inventory_d_invento_7d8010_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorydaily',
            unique_together={('inventory', 'date')},
        ),
    ]
