# Generated by Django 5.2.7 on 2026-01-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('mosku', models.CharField(help_text='唯一SKU编码', max_length=100, primary_key=True, serialize=False, verbose_name='MOSKU编码')),
                ('factory_name', models.CharField(db_index=True, max_length=200, verbose_name='工厂名称')),
                ('supplier_name', models.CharField(max_length=200, null=True, verbose_name='供应商名称')),
                ('product_name', models.CharField(db_index=True, max_length=300, verbose_name='产品名称')),
                ('color', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='颜色')),
                ('size', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='尺码')),
                ('location', models.CharField(db_index=True, max_length=100, verbose_name='库位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存主数据',
                'verbose_name_plural': '库存主数据',
                'db_table': 'inventory_master',
                'indexes': [models.Index(fields=['factory_name', 'supplier_name'], name='inventory_m_factory_9a5dd9_idx'), models.Index(fields=['product_name', 'color', 'size'], name='inventory_m_product_f443c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('available_qty', models.IntegerField(default=0, verbose_name='可用数量')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='库存数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='inventory.inventorymaster', verbose_name='MOSKU')),
            ],
            options={
                'verbose_name': '每日库存快照',
                'verbose_name_plural': '每日库存快照',
                'db_table': 'inventory_daily',
                'indexes': [models.Index(fields=['date', 'inventory'], name='inventory_d_date_efcf1f_idx')],
                'unique_together': {('inventory', 'date')},
            },
        ),
    ]
