# Generated by Django 5.2.7 on 2026-01-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymaster',
            options={'ordering': ['mosku'], 'verbose_name': '库存主数据', 'verbose_name_plural': '库存主数据'},
        ),
    ]
