# Generated by Django 5.2.7 on 2026-01-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydaily',
            name='stock_qty',
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
    ]
