# Generated by Django 5.2.7 on 2026-01-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorydaily_stock_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorydaily',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorydaily',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='inventorymaster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorymaster',
            name='updated_at',
        ),
    ]
