# Generated by Django 5.2.7 on 2026-01-26 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='需求名称')),
                ('requirement_type', models.CharField(choices=[('simple', '简单任务'), ('system', '系统')], default='simple', max_length=10, verbose_name='需求类型')),
                ('status', models.CharField(choices=[('pending', '待开发'), ('developing', '开发中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('P0', 'P0-紧急'), ('P1', 'P1-高'), ('P2', 'P2-中'), ('P3', 'P3-低')], default='P2', max_length=2, verbose_name='优先级')),
                ('score', models.PositiveIntegerField(blank=True, help_text='仅简单任务填写，系统任务自动计算子任务之和', null=True, verbose_name='任务分值')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('pause_reason', models.TextField(blank=True, help_text='暂停状态时填写', verbose_name='暂停原因')),
                ('publish_date', models.DateField(verbose_name='需求发布日期')),
                ('claim_date', models.DateTimeField(blank=True, null=True, verbose_name='需求领取日期')),
                ('expected_finish', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developed_requirements', to=settings.AUTH_USER_MODEL, verbose_name='开发者')),
                ('extends_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_tasks', to='data_req.datarequirement', verbose_name='延伸自(前置任务)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_req.datarequirement', verbose_name='父级需求(包含关系)')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_requirements', to=settings.AUTH_USER_MODEL, verbose_name='需求人')),
            ],
            options={
                'verbose_name': '数据部需求',
                'verbose_name_plural': '数据部需求',
                'db_table': 'data_requirement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('claim', '领取任务'), ('start', '开始开发'), ('pause', '暂停开发'), ('resume', '重新启动'), ('complete', '完成开发'), ('cancel', '取消任务')], max_length=20, verbose_name='操作类型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('reason', models.TextField(blank=True, help_text='暂停、取消等操作时填写原因', verbose_name='原因/备注')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='data_req.datarequirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '需求时间线',
                'verbose_name_plural': '需求时间线',
                'db_table': 'requirement_timeline',
                'ordering': ['-timestamp'],
            },
        ),
    ]
