# Generated by Django 5.2.7 on 2026-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_req', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequirement',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际完成日期'),
        ),
        migrations.AlterField(
            model_name='requirementtimeline',
            name='reason',
            field=models.TextField(blank=True, verbose_name='原因/备注'),
        ),
    ]
