# Generated by Django 5.2.7 on 2026-01-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_req', '0002_datarequirement_finish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequirement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开发开始日期'),
        ),
        migrations.AlterField(
            model_name='datarequirement',
            name='score',
            field=models.FloatField(blank=True, help_text='仅简单任务填写，系统任务自动计算子任务之和', null=True, verbose_name='难度系数'),
        ),
        migrations.AlterField(
            model_name='datarequirement',
            name='status',
            field=models.CharField(choices=[('pending', '待领取'), ('claimed', '已领取'), ('developing', '开发中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='requirementtimeline',
            name='action',
            field=models.CharField(choices=[('claim', '领取任务'), ('unclaim', '退领任务'), ('start', '开始开发'), ('pause', '暂停开发'), ('resume', '恢复开发'), ('complete', '完成开发'), ('cancel', '取消任务'), ('restart', '重新开发')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='requirementtimeline',
            name='reason',
            field=models.TextField(blank=True, help_text='退领、暂停、取消等操作时填写原因', verbose_name='原因/备注'),
        ),
    ]
