# Generated by Django 5.2.7 on 2026-02-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_req', '0003_datarequirement_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarequirement',
            name='requirement_type',
            field=models.CharField(choices=[('simple', '任务'), ('system', '系统')], default='simple', max_length=10, verbose_name='需求类型'),
        ),
    ]
