# Generated by Django 5.2.7 on 2025-11-15 06:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用'), (3, '注销')], default=1, verbose_name='状态')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='角色')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名称')),
                ('platform', models.CharField(blank=True, max_length=255, null=True, verbose_name='平台')),
                ('ops_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='分组')),
                ('wx_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='企业微信消息通知url')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='general_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='general_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OperationalAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operational_account', serialize=False, to='general.user', verbose_name='关联用户')),
                ('shandianyun_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='闪电云账号')),
                ('shandianyun_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='闪电云用户名')),
                ('shandianyun_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='闪电云密码')),
                ('lingxing_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='领星用户名')),
                ('lingxing_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='领星密码')),
                ('ziniao_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='紫鸟公司')),
                ('ziniao_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='紫鸟用户名')),
                ('ziniao_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='紫鸟密码')),
                ('diwei_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='迪唯账号')),
                ('diwei_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='迪唯密码')),
            ],
            options={
                'verbose_name': '运营外部账号',
                'verbose_name_plural': '运营外部账号',
                'db_table': 'operational_accounts',
            },
        ),
    ]
