# Generated by Django 5.2.7 on 2025-11-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
