# Generated by Django 5.2.7 on 2026-01-13 14:53

import general.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=general.models.get_default_valid_to, verbose_name='过期时间'),
        ),
    ]
