# Generated by Django 5.2.7 on 2025-11-17 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonShop',
            fields=[
                ('id', models.BigIntegerField(db_comment='主键', primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, db_comment='客户', max_length=100, null=True)),
                ('shop_number', models.IntegerField(blank=True, db_comment='店铺序号', null=True)),
                ('shop_name', models.CharField(blank=True, db_comment='店铺名', max_length=100, null=True)),
                ('whitelist', models.CharField(blank=True, db_comment='白名单', max_length=255, null=True)),
                ('seller_mark', models.CharField(blank=True, db_comment='卖家记号', max_length=100, null=True)),
                ('amazon_shop_name', models.CharField(blank=True, db_comment='亚马逊-店铺名称', max_length=150, null=True)),
                ('remark', models.TextField(blank=True, db_comment='备注', null=True)),
                ('shop_date', models.DateField(blank=True, db_comment='下店日期', null=True)),
                ('ip_address', models.CharField(blank=True, db_comment='IP', max_length=45, null=True)),
                ('email_account', models.CharField(blank=True, db_comment='邮箱账号（店铺账号）', max_length=150, null=True)),
                ('email_password', models.CharField(blank=True, db_comment='邮箱密码', max_length=100, null=True)),
                ('shop_password', models.CharField(blank=True, db_comment='店铺密码', max_length=100, null=True)),
                ('backup_email_or_phone', models.CharField(blank=True, db_comment='备用邮箱或手机号', max_length=100, null=True)),
                ('credit_card_channel', models.CharField(blank=True, db_comment='信用卡渠道', max_length=100, null=True)),
                ('credit_card_number', models.CharField(blank=True, db_comment='信用卡', max_length=40, null=True)),
                ('credit_card_expiry', models.CharField(blank=True, db_comment='有效期', max_length=10, null=True)),
                ('credit_card_cvv', models.CharField(blank=True, db_comment='信用卡安全码后3位', max_length=3, null=True)),
                ('is_consolidated', models.CharField(blank=True, db_comment='是否归集（寻汇子账号是否归集到寻汇总账号）', max_length=255, null=True)),
                ('bind_collection', models.CharField(blank=True, db_comment='绑定收款', max_length=50, null=True)),
                ('collection_channel', models.CharField(blank=True, db_comment='收款渠道', max_length=50, null=True)),
                ('xunhui_login_account', models.CharField(blank=True, db_comment='寻汇登录账号', max_length=150, null=True)),
                ('login_password', models.CharField(blank=True, db_comment='登录密码', max_length=100, null=True)),
                ('bind_phone', models.CharField(blank=True, db_comment='绑定手机号', max_length=20, null=True)),
                ('collection_card_number', models.CharField(blank=True, db_comment='收款卡号', max_length=30, null=True)),
                ('payment_password', models.CharField(blank=True, db_comment='支付密码', max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, db_comment='身份证号', max_length=100, null=True)),
                ('legal_person_phone', models.CharField(blank=True, db_comment='法人手机号码', max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, db_comment='单位名称', max_length=200, null=True)),
                ('license_number', models.CharField(blank=True, db_comment='执照号', max_length=100, null=True)),
                ('business_license_date', models.DateField(blank=True, db_comment='营业执照日期', null=True)),
                ('birth_date', models.DateField(blank=True, db_comment='出生日期', null=True)),
                ('id_expiry_date', models.CharField(blank=True, db_comment='身份证到期日', max_length=100, null=True)),
                ('additional_remark', models.TextField(blank=True, db_comment='备注', null=True)),
                ('created_at', models.DateTimeField(db_comment='创建时间')),
                ('updated_at', models.DateTimeField(db_comment='更新时间')),
                ('qu_dao', models.CharField(blank=True, db_comment='店铺渠道', max_length=255, null=True)),
                ('img1', models.CharField(blank=True, db_comment='图片', max_length=255, null=True)),
                ('shop_status', models.CharField(blank=True, db_comment='店铺情况', max_length=255, null=True)),
                ('voucher_163', models.CharField(blank=True, db_comment='163邮箱凭证', max_length=255, null=True)),
                ('email_163_account', models.CharField(blank=True, db_comment='163大师账号', max_length=255, null=True)),
                ('ling_xing_if', models.SmallIntegerField(db_comment='是否绑定领星')),
                ('browser', models.CharField(db_comment='浏览器', max_length=255)),
                ('divi_shop_id', models.IntegerField(blank=True, db_comment='迪唯店铺id', null=True)),
                ('ops', models.ForeignKey(blank=True, db_column='ops_id', db_comment='运营id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='运营人员')),
            ],
            options={
                'db_table': 'amazon_shop',
                'db_table_comment': '亚马逊店铺信息表',
            },
        ),
    ]
