# Generated by Django 5.2.7 on 2026-01-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='权限码')),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='权限分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限配置',
                'db_table': 'user_permission_configs',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permission_configs',
            field=models.ManyToManyField(blank=True, db_table='user_permission_config', related_name='users', to='general.permissionconfig', verbose_name='业务权限列表'),
        ),
    ]
