# Generated by Django 5.2.7 on 2025-11-17 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_amazonshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshop',
            name='ops',
            field=models.ForeignKey(blank=True, db_column='ops', db_comment='运营id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='运营人员'),
        ),
    ]
