# Generated by Django 5.2.7 on 2026-01-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_amazonshop_qupital_if'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshop',
            name='id',
            field=models.BigAutoField(db_comment='主键', primary_key=True, serialize=False),
        ),
    ]
