# Generated by Django 5.2.7 on 2025-11-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_amazonshop_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalaccount',
            name='ops_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='分组'),
        ),
    ]
