# Generated by Django 5.2.7 on 2026-01-29 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_amazonshop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='{"enable_risk_check": true, "max_shops": 100}', verbose_name='公司配置'),
        ),
        migrations.AddField(
            model_name='operationalaccount',
            name='role',
            field=models.CharField(blank=True, choices=[('leader', '运营组长'), ('staff', '运营'), ('assistant', '运营助理')], default='staff', max_length=50, null=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, help_text='用户所属的公司，多租户隔离用', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='general.company', verbose_name='所属公司'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('data', '数据部'), ('operation', '运营部'), ('hr', '人事部'), ('supply_chain', '供应链部'), ('assistant', '助理部')], db_comment='部门（静态选项：数据部、运营部、人事部、供应链部、助理部）', max_length=20, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='项目名称')),
                ('code', models.CharField(help_text='公司内唯一标识，如 "CNXH001"', max_length=50, verbose_name='项目代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前，用于前端展示', verbose_name='排序号')),
                ('is_active', models.BooleanField(db_comment='停用后不允许店铺挂靠，但已有数据保留', default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(db_comment='项目所属公司', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='general.company', verbose_name='所属公司')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'companies_projects',
                'ordering': ['company', 'sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_project',
            field=models.ForeignKey(blank=True, db_comment='用户默认所属项目，用于页面默认筛选（如"店铺列表"默认展示该项目店铺）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='general.project', verbose_name='主属项目'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='用户参与的项目列表，仅用于分类标记，不做权限隔离', related_name='members', to='general.project', verbose_name='参与项目'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'is_active'], name='idx_company_active'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('company', 'code')},
        ),
    ]
