# Generated by Django 5.2.7 on 2025-11-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_operationalaccount_ops_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ops_group',
        ),
    ]
