# Generated by Django 5.2.7 on 2025-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_remove_user_ops_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='权限'),
        ),
    ]
