# Generated by Django 5.2.7 on 2025-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemuShop',
            fields=[
                ('id', models.BigIntegerField(db_comment='主键', primary_key=True, serialize=False)),
                ('shop_name', models.CharField(blank=True, db_comment='店铺名称', max_length=255, null=True)),
                ('ops_id', models.IntegerField(blank=True, db_comment='运营id', null=True)),
                ('divi_shop_id', models.IntegerField(blank=True, db_comment='迪唯店铺id', null=True)),
                ('shop_entity', models.CharField(blank=True, db_comment='主体公司', max_length=255, null=True)),
                ('shop_account', models.CharField(blank=True, db_comment='登录账号', max_length=255, null=True)),
                ('shop_password', models.CharField(blank=True, db_comment='店铺的登录密码', max_length=255, null=True)),
                ('invitation_code', models.CharField(blank=True, db_comment='邀请码', max_length=255, null=True)),
                ('verification_email', models.CharField(blank=True, db_comment='邮箱地址', max_length=255, null=True)),
                ('email_password', models.CharField(blank=True, db_comment='登录密码', max_length=255, null=True)),
                ('shop_temu_id', models.CharField(blank=True, db_comment='店铺Temu_ID', max_length=255, null=True)),
                ('compliance_center', models.CharField(blank=True, db_comment='合规中心', max_length=255, null=True)),
                ('new_principal_info', models.CharField(blank=True, db_comment='负责人信息申报新增负责人信息', max_length=255, null=True)),
                ('new_manufacturer_info', models.CharField(blank=True, db_comment='制造商信息申报新增制造商信息申报', max_length=255, null=True)),
                ('phone_account_holder', models.CharField(blank=True, db_comment='手机号码开户人', max_length=255, null=True)),
                ('phone_current_location', models.CharField(blank=True, db_comment='手机号码现存放', max_length=255, null=True)),
                ('shop_nature', models.CharField(blank=True, db_comment='性质', max_length=255, null=True)),
                ('place_of_origin', models.CharField(blank=True, db_comment='归属地', max_length=255, null=True)),
                ('legal_person', models.CharField(blank=True, db_comment='法人', max_length=255, null=True)),
                ('customer', models.CharField(blank=True, db_comment='客户', max_length=255, null=True)),
                ('shop_status', models.SmallIntegerField(blank=True, db_comment='店铺状态', null=True)),
            ],
            options={
                'db_table': 'temu_shop',
                'db_table_comment': 'temu店铺表',
            },
        ),
    ]
