# Generated by Django 5.2.7 on 2025-11-25 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0008_temushop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('month', models.CharField(max_length=7, verbose_name='目标月份')),
                ('target_performance', models.IntegerField(default=0, verbose_name='目标业绩/单')),
                ('stretch_target', models.IntegerField(default=0, verbose_name='冲单业绩目标/单')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_targets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to=settings.AUTH_USER_MODEL, verbose_name='运营人员')),
            ],
            options={
                'verbose_name': '绩效目标',
                'verbose_name_plural': '绩效目标',
                'db_table': 'user_performance_targets',
                'indexes': [models.Index(fields=['month', 'user'], name='user_perfor_month_5b88ae_idx')],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
