# Generated by Django 5.2.7 on 2025-11-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_performancetarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPerformanceTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('month', models.CharField(max_length=7, verbose_name='目标月份')),
                ('ops_group', models.CharField(max_length=255, verbose_name='运营分组')),
                ('target_performance', models.IntegerField(default=0, verbose_name='组目标业绩/单')),
                ('stretch_target', models.IntegerField(default=0, verbose_name='组冲单目标/单')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_targets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '组绩效目标',
                'verbose_name_plural': '组绩效目标',
                'db_table': 'group_performance_targets',
            },
        ),
        migrations.CreateModel(
            name='PersonalPerformanceTarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('ops_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='运营分组')),
                ('month', models.CharField(max_length=7, verbose_name='目标月份')),
                ('target_performance', models.IntegerField(default=0, verbose_name='个人目标业绩/单')),
                ('stretch_target', models.IntegerField(default=0, verbose_name='个人冲单目标/单')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personal_targets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_performance_targets', to=settings.AUTH_USER_MODEL, verbose_name='运营人员')),
            ],
            options={
                'verbose_name': '个人绩效目标',
                'verbose_name_plural': '个人绩效目标',
                'db_table': 'personal_performance_targets',
            },
        ),
        migrations.DeleteModel(
            name='PerformanceTarget',
        ),
        migrations.AddIndex(
            model_name='groupperformancetarget',
            index=models.Index(fields=['month', 'ops_group'], name='group_perfo_month_714097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupperformancetarget',
            unique_together={('ops_group', 'month')},
        ),
        migrations.AddIndex(
            model_name='personalperformancetarget',
            index=models.Index(fields=['month', 'ops_group'], name='personal_pe_month_a63571_idx'),
        ),
        migrations.AddIndex(
            model_name='personalperformancetarget',
            index=models.Index(fields=['user', 'month'], name='personal_pe_user_id_f68088_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personalperformancetarget',
            unique_together={('user', 'month')},
        ),
    ]
