# Generated by Django 5.2.7 on 2025-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_groupperformancetarget_personalperformancetarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
