# Generated by Django 5.2.7 on 2026-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_remove_useroperationlog_idx_type_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalaccount',
            name='platform',
            field=models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('temu', 'Temu')], max_length=50, null=True, verbose_name='平台'),
        ),
    ]
