# Generated by Django 5.2.7 on 2026-01-30 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_operationalaccount_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroperationlog',
            name='company',
            field=models.ForeignKey(blank=True, db_comment='记录操作时的公司归属，用于审计和按公司查询', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_logs', to='general.company', verbose_name='操作所属公司'),
        ),
    ]
