# Generated by Django 5.2.7 on 2025-11-28 10:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0011_user_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(db_comment='公告唯一标识ID', primary_key=True, serialize=False, verbose_name='主键')),
                ('title', models.CharField(db_comment='公告标题，显示在弹窗顶部', max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(db_comment='公告正文内容，支持HTML格式', verbose_name='公告内容')),
                ('priority', models.CharField(choices=[('high', '高优先级'), ('medium', '中优先级'), ('low', '低优先级')], db_comment='公告优先级：high/medium/low', default='medium', max_length=10, verbose_name='优先级')),
                ('valid_from', models.DateTimeField(db_comment='公告开始显示时间', default=django.utils.timezone.now, verbose_name='生效时间')),
                ('valid_to', models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 5, 10, 59, 7, 938898), verbose_name='过期时间')),
                ('is_active', models.BooleanField(db_comment='后台控制是否启用该公告', default=True, verbose_name='是否激活')),
                ('is_dismissible', models.BooleanField(db_comment='是否显示"关闭"按钮', default=True, verbose_name='允许关闭')),
                ('can_mark_read', models.BooleanField(db_comment='是否显示"不再提示"按钮', default=True, verbose_name='允许标记已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='公告创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='公告最后修改时间', verbose_name='更新时间')),
                ('created_by', models.ForeignKey(db_comment='发布公告的用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'system_announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(db_comment='记录ID', primary_key=True, serialize=False, verbose_name='主键')),
                ('read_at', models.DateTimeField(auto_now_add=True, db_comment='用户点击"不再提示"的时间', verbose_name='已读时间')),
                ('dismissed_at', models.DateTimeField(blank=True, db_comment='用户仅点击关闭的时间（可记录但不影响逻辑）', null=True, verbose_name='关闭时间')),
                ('announcement', models.ForeignKey(db_comment='被标记已读的的公告ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_reads', to='General.announcement', verbose_name='公告')),
                ('user', models.ForeignKey(db_comment='已读公告的用户ID', on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户已读记录',
                'verbose_name_plural': '用户已读记录',
                'db_table': 'user_announcement_reads',
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_to', 'priority'], name='idx_announcement_active_time'),
        ),
        migrations.AddIndex(
            model_name='userannouncementread',
            index=models.Index(fields=['user', 'read_at'], name='idx_user_read_time'),
        ),
        migrations.AlterUniqueTogether(
            name='userannouncementread',
            unique_together={('user', 'announcement')},
        ),
    ]
