# Generated by Django 5.2.7 on 2025-12-01 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0012_announcement_userannouncementread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 8, 11, 16, 27, 6819), verbose_name='过期时间'),
        ),
    ]
