# Generated by Django 5.2.7 on 2026-01-30 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_alter_useroperationlog_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshop',
            name='company',
            field=models.ForeignKey(blank=True, db_comment='数据隔离边界', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amazon_shops', to='general.company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='amazonshop',
            name='project',
            field=models.ForeignKey(blank=True, db_comment='业务分组标签', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_shops', to='general.project', verbose_name='所属项目'),
        ),
    ]
