# Generated by Django 5.2.7 on 2026-01-31 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_amazonshop_company_alter_amazonshop_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temushop',
            name='project',
            field=models.ForeignKey(blank=True, db_comment='业务分组标签，可自由迁移', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temu_shops', to='general.project', verbose_name='所属项目'),
        ),
    ]
