# Generated by Django 5.2.7 on 2026-01-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_alter_temushop_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_project',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
