# Generated by Django 5.2.7 on 2025-12-05 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0015_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshop',
            name='registered_phone',
            field=models.CharField(blank=True, db_comment='注册手机号', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='amazonshop',
            name='company_name',
            field=models.CharField(blank=True, db_comment='公司名称', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 12, 17, 6, 10, 587497), verbose_name='过期时间'),
        ),
    ]
