# Generated by Django 5.2.7 on 2026-02-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_remove_user_default_project_remove_user_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='divi_api_key',
            field=models.CharField(blank=True, db_comment='Divi平台接口授权令牌', help_text='用于对接Divi侵权词库查询接口。通常格式为 Bearer Token', max_length=255, null=True, verbose_name='Divi API密钥'),
        ),
        migrations.AddField(
            model_name='project',
            name='divi_sync_enabled',
            field=models.BooleanField(db_comment='控制是否允许调用Divi接口查侵权词', default=False, verbose_name='启用Divi自动同步'),
        ),
        migrations.AddField(
            model_name='project',
            name='lingxing_api_key',
            field=models.CharField(blank=True, db_comment='领星ERP接口授权令牌(AppKey或Token)', help_text='用于对接领星ERP系统，拉取订单/库存数据。如未配置则该项目无法同步领星数据', max_length=255, null=True, verbose_name='领星API密钥'),
        ),
        migrations.AddField(
            model_name='project',
            name='lingxing_sync_enabled',
            field=models.BooleanField(db_comment='控制是否允许定时任务拉取领星数据', default=False, verbose_name='启用领星自动同步'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('data', '数据部'), ('operation', '运营部'), ('hr', '人事部'), ('supply_chain', '供应链部'), ('assistant', '助理部'), ('finance', '财务部')], db_comment='部门（静态选项：数据部、运营部、人事部、供应链部、助理部）', max_length=20, null=True, verbose_name='部门'),
        ),
    ]
