# Generated by Django 5.2.7 on 2026-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_project_divi_api_key_project_divi_sync_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='divi_api_key',
        ),
        migrations.AddField(
            model_name='project',
            name='divi_partner_code',
            field=models.CharField(blank=True, db_comment='固定分配的应用标识，如 7607f3480484b48235', help_text='对应 DIVI 的 PARTNER_CODE', max_length=100, null=True, verbose_name='Divi合作方编码 (PARTNER_CODE)'),
        ),
        migrations.AddField(
            model_name='project',
            name='divi_secret',
            field=models.CharField(blank=True, db_comment='用于生成请求签名，切勿泄露', help_text='对应 DIVI 的 SECRET，用于接口签名验证', max_length=255, null=True, verbose_name='Divi密钥 (SECRET)'),
        ),
    ]
