# Generated by Django 5.2.7 on 2025-12-10 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_amazonshop_registered_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', '浅色'), ('dark', '深色')], default='light', max_length=10, verbose_name='主题偏好'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 17, 18, 3, 55, 340667), verbose_name='过期时间'),
        ),
    ]
