# Generated by Django 5.2.7 on 2026-02-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0017_remove_project_divi_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lingxing_api_key',
        ),
        migrations.AddField(
            model_name='project',
            name='lingxing_app_id',
            field=models.CharField(blank=True, db_comment='领星开放平台的应用ID，如 ak_P211HcxRxAZ8x', help_text='对应领星开发者后台的 appId 字段', max_length=100, null=True, verbose_name='领星AppID'),
        ),
        migrations.AddField(
            model_name='project',
            name='lingxing_app_secret',
            field=models.CharField(blank=True, db_comment='领星开放平台密钥，用于生成请求签名', help_text='对应领星开发者后台的 appSecret，用于接口签名', max_length=255, null=True, verbose_name='领星AppSecret'),
        ),
    ]
