# Generated by Django 5.2.7 on 2025-12-11 16:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0017_user_theme_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 18, 16, 15, 26, 772188), verbose_name='过期时间'),
        ),
        migrations.CreateModel(
            name='UserOperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('operation_type', models.IntegerField(choices=[(1001, '新增用户'), (1002, '修改用户信息'), (1003, '删除用户'), (2001, '新增店铺'), (2002, '修改店铺'), (2003, '删除店铺'), (3001, '订单导单'), (3002, '订单发货'), (3003, '订单标注真发'), (3004, 'RPA真物流覆盖假物流')], db_comment='4位数字类型：1xxx用户操作，2xxx店铺操作，3xxx订单操作', db_index=True, verbose_name='操作类型')),
                ('operation_record', models.CharField(db_comment='自由记录的文本内容', db_index=True, max_length=255, verbose_name='操作记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='自动写入的操作时间', db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, db_comment='执行操作的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'db_table': 'user_operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_time'), models.Index(fields=['operation_type', '-created_at'], name='idx_type_time')],
            },
        ),
    ]
