# Generated by Django 5.2.7 on 2026-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0018_remove_project_lingxing_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopChannelRisk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=50, verbose_name='店铺渠道')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('none', '无')], db_index=True, default='none', max_length=20, verbose_name='渠道风险等级')),
                ('channel_remark', models.CharField(blank=True, max_length=100, verbose_name='渠道备注')),
            ],
            options={
                'verbose_name': '店铺渠道风险',
                'verbose_name_plural': '店铺渠道风险',
                'db_table': 'amazon_channel_risk',
                'indexes': [models.Index(fields=['risk_level', 'channel_name'], name='amazon_chan_risk_le_6ce0f2_idx')],
            },
        ),
    ]
