# Generated by Django 5.2.7 on 2026-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_shopchannelrisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopchannelrisk',
            name='channel_remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='渠道备注'),
        ),
    ]
