# Generated by Django 5.2.7 on 2025-12-12 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_alter_announcement_valid_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='公司名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='公司代码')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '停用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'db_table': 'companies',
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 19, 17, 56, 3, 524986), verbose_name='过期时间'),
        ),
    ]
