# Generated by Django 5.2.7 on 2026-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_alter_shopchannelrisk_channel_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopchannelrisk',
            name='channel_name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='店铺渠道'),
        ),
    ]
