# Generated by Django 5.2.7 on 2025-12-12 17:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0020_company_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='用户所属的公司，多租户隔离用', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='General.company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 19, 17, 59, 28, 398266), verbose_name='过期时间'),
        ),
    ]
