# Generated by Django 5.2.7 on 2026-02-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_alter_shopchannelrisk_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshop',
            name='channel_risk',
            field=models.ForeignKey(blank=True, db_comment='关联渠道风险表（qu_dao保留仅作历史显示）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_shops', to='general.shopchannelrisk', verbose_name='店铺渠道配置'),
        ),
    ]
