# Generated by Django 5.2.7 on 2026-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_amazonshop_channel_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
