# Generated by Django 5.2.7 on 2026-02-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroperationlog',
            name='operation_type',
            field=models.IntegerField(choices=[(1001, '新增用户'), (1002, '修改用户信息'), (1003, '删除用户'), (2001, '新增店铺'), (2002, '修改店铺'), (2003, '删除店铺'), (3001, '订单导单'), (3002, '订单发货'), (3003, '订单标注真发'), (3004, 'RPA真物流覆盖假物流'), (3005, '自动发货'), (4001, '标记邮件已处理'), (4002, '批量通知运营邮件'), (4011, '重置巡店'), (6001, '绩效考核-批量刷新订单'), (6002, '绩效考核-组长评分提交'), (6003, '绩效考核-组员评分确认'), (6004, '绩效考核-组长评分确认'), (6005, '考核创建'), (6006, '绩效考核-组员评分驳回'), (7101, '物流追踪-标记运单取消'), (7102, '物流追踪-恢复运单状态'), (8001, '新增侵权词'), (8002, '修改侵权词'), (8003, '删除侵权词'), (8004, '批量导入侵权词')], db_comment='4位数字类型：1xxx用户操作，2xxx店铺操作，3xxx订单操作，4xxx邮件，6xxx考核，7xxx物流', db_index=True, verbose_name='操作类型'),
        ),
    ]
