# Generated by Django 5.2.7 on 2025-12-20 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0026_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 27, 17, 28, 37, 422011), verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='useroperationlog',
            name='operation_type',
            field=models.IntegerField(choices=[(1001, '新增用户'), (1002, '修改用户信息'), (1003, '删除用户'), (2001, '新增店铺'), (2002, '修改店铺'), (2003, '删除店铺'), (3001, '订单导单'), (3002, '订单发货'), (3003, '订单标注真发'), (3004, 'RPA真物流覆盖假物流'), (3005, '自动发货'), (4001, '标记邮件已处理'), (4002, '批量通知运营邮件')], db_comment='4位数字类型：1xxx用户操作，2xxx店铺操作，3xxx订单操作', db_index=True, verbose_name='操作类型'),
        ),
    ]
