# Generated by Django 5.2.7 on 2026-03-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_operationalaccount_divi_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temushop',
            name='height',
            field=models.FloatField(blank=True, db_comment='包裹高度，单位inch', default=None, null=True, verbose_name='高(inch)'),
        ),
        migrations.AddField(
            model_name='temushop',
            name='length',
            field=models.FloatField(blank=True, db_comment='包裹长度，单位inch', default=None, null=True, verbose_name='长(inch)'),
        ),
        migrations.AddField(
            model_name='temushop',
            name='weight',
            field=models.FloatField(blank=True, db_comment='包裹重量，单位lb', default=None, null=True, verbose_name='重量(lb)'),
        ),
        migrations.AddField(
            model_name='temushop',
            name='width',
            field=models.FloatField(blank=True, db_comment='包裹宽度，单位inch', default=None, null=True, verbose_name='宽(inch)'),
        ),
    ]
