# Generated by Django 5.2.7 on 2026-04-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_temushop_height_temushop_length_temushop_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalaccount',
            name='ad_requires_approval',
            field=models.BooleanField(blank=True, default=False, help_text='该账号的广告投放/调整操作是否需要组长/管理员审批', null=True, verbose_name='广告需审批'),
        ),
    ]
