# Generated by Django 5.2.7 on 2026-04-03 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_operationalaccount_ad_requires_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='该用户的直接汇报对象，必须同公司', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='直接上级'),
        ),
    ]
