# Generated by Django 5.2.7 on 2026-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshop',
            name='divi_shop_id',
            field=models.IntegerField(blank=True, db_comment='迪唯店铺id', null=True, unique=True),
        ),
    ]
