# Generated by Django 5.2.7 on 2025-12-24 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0029_alter_announcement_valid_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2025, 12, 31, 15, 39, 3, 930919), verbose_name='过期时间'),
        ),
    ]
