# Generated by Django 5.2.7 on 2026-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_alter_amazonshop_divi_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshop',
            name='shop_status',
            field=models.CharField(blank=True, choices=[('status-active', '正常'), ('status-inactive', '停用'), ('status-cancelled', '注销'), ('status-warning', '救店中'), ('status-pending', '审核中'), ('status-unknown', '待定')], db_comment='店铺情况', default='status-active', max_length=50, null=True, verbose_name='amazon_shop_status'),
        ),
    ]
