# Generated by Django 5.2.7 on 2026-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_alter_amazonshop_shop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshop',
            name='company_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='公司地址'),
        ),
        migrations.AddField(
            model_name='amazonshop',
            name='id_card_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='身份证地址'),
        ),
    ]
