# Generated by Django 5.2.7 on 2025-12-26 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0032_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 2, 8, 44, 41, 739620), verbose_name='过期时间'),
        ),
    ]
