# Generated by Django 5.2.7 on 2026-04-17 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_alter_amazonshop_shop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshop',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, db_comment='被授权管理该店铺的用户，一个店铺可关联多个用户', related_name='authorized_shops', to=settings.AUTH_USER_MODEL, verbose_name='授权管理人员'),
        ),
    ]
