# Generated by Django 5.2.7 on 2026-04-20 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0034_amazonshop_authorized_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshop',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_shops', to=settings.AUTH_USER_MODEL, verbose_name='授权管理人员'),
        ),
    ]
