# Generated by Django 5.2.7 on 2026-04-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0035_add_approval_flow_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshop',
            name='license_registered_capital',
            field=models.CharField(blank=True, db_comment='执照注册资本', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazonshop',
            name='lingxing_ad_authorization_date',
            field=models.DateField(blank=True, db_comment='领星广告授权日期', null=True),
        ),
    ]
