# Generated by Django 5.2.7 on 2026-04-24 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


DEFAULT_SYSTEM_MODULES = [
    {
        'code': 'order_fulfillment',
        'name': '导单发货功能',
        'category': '业务流程',
        'description': '订单导入、订单处理、发货与相关业务流程',
        'icon': 'fas fa-file-import',
        'sort_order': 10,
    },
    {
        'code': 'automation',
        'name': '自动化功能',
        'category': '自动化',
        'description': 'RPA、自动同步、自动通知与自动化任务相关功能',
        'icon': 'fas fa-robot',
        'sort_order': 20,
    },
    {
        'code': 'logistics',
        'name': '物流板块',
        'category': '物流',
        'description': '物流追踪、物流异常、面单与外部采购物流相关功能',
        'icon': 'fas fa-truck',
        'sort_order': 30,
    },
    {
        'code': 'theme',
        'name': '主题板块',
        'category': '数据与选品',
        'description': '主题词、趋势、新品、ABA 与选品数据相关功能',
        'icon': 'fas fa-lightbulb',
        'sort_order': 40,
    },
    {
        'code': 'infringement',
        'name': '侵权板块',
        'category': '风控',
        'description': '侵权词库、商标查询、风险关键词与相关风控功能',
        'icon': 'fas fa-shield-alt',
        'sort_order': 50,
    },
]


def create_default_system_modules(apps, schema_editor):
    SystemModule = apps.get_model('general', 'SystemModule')
    for module in DEFAULT_SYSTEM_MODULES:
        SystemModule.objects.update_or_create(
            code=module['code'],
            defaults={
                'name': module['name'],
                'category': module['category'],
                'description': module['description'],
                'icon': module['icon'],
                'sort_order': module['sort_order'],
                'is_active': True,
                'is_builtin': True,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0036_amazonshop_license_registered_capital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='模块编码')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='模块分类')),
                ('description', models.TextField(blank=True, verbose_name='模块说明')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_builtin', models.BooleanField(default=True, verbose_name='系统内置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统模块',
                'verbose_name_plural': '系统模块',
                'db_table': 'system_modules',
                'ordering': ['category', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyModuleGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否开通')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='模块配置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_grants', to='general.company', verbose_name='公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_module_grants', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_module_grants', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_grants', to='general.systemmodule', verbose_name='模块')),
            ],
            options={
                'verbose_name': '公司模块授权',
                'verbose_name_plural': '公司模块授权',
                'db_table': 'company_module_grants',
            },
        ),
        migrations.RunPython(create_default_system_modules, migrations.RunPython.noop),
        migrations.AddField(
            model_name='company',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='companies', through='general.CompanyModuleGrant', to='general.systemmodule', verbose_name='开通模块'),
        ),
        migrations.AddIndex(
            model_name='companymodulegrant',
            index=models.Index(fields=['company', 'enabled'], name='idx_grant_company_enabled'),
        ),
        migrations.AddIndex(
            model_name='companymodulegrant',
            index=models.Index(fields=['module', 'enabled'], name='idx_grant_module_enabled'),
        ),
        migrations.AlterUniqueTogether(
            name='companymodulegrant',
            unique_together={('company', 'module')},
        ),
        migrations.AlterField(
            model_name='company',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='{"enable_risk_check": true}', verbose_name='公司配置'),
        ),
    ]
