# Generated by Django 5.2.7 on 2025-12-29 13:36

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0036_convert_month_to_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='groupperformancetarget',
            name='group_perf_month_ops_group_idx',
        ),
        migrations.RemoveIndex(
            model_name='personalperformancetarget',
            name='personal_perf_month_ops_group_idx',
        ),
        migrations.RemoveIndex(
            model_name='personalperformancetarget',
            name='personal_perf_user_month_idx',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 5, 13, 36, 56, 64238), verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='groupperformancetarget',
            name='month',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='目标月份'),
        ),
        migrations.AlterField(
            model_name='personalperformancetarget',
            name='month',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='目标月份'),
        ),
        migrations.AlterField(
            model_name='useroperationlog',
            name='operation_type',
            field=models.IntegerField(choices=[(1001, '新增用户'), (1002, '修改用户信息'), (1003, '删除用户'), (2001, '新增店铺'), (2002, '修改店铺'), (2003, '删除店铺'), (3001, '订单导单'), (3002, '订单发货'), (3003, '订单标注真发'), (3004, 'RPA真物流覆盖假物流'), (3005, '自动发货'), (4001, '标记邮件已处理'), (4002, '批量通知运营邮件'), (4011, '重置巡店'), (5001, '绩效考核-组长提交'), (5002, '绩效考核-个人确认'), (5003, '绩效考核-个人驳回'), (5004, '绩效考核-组长确认')], db_comment='4位数字类型：1xxx用户操作，2xxx店铺操作，3xxx订单操作', db_index=True, verbose_name='操作类型'),
        ),
    ]
