# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0037_systemmodule_companymodulegrant_company_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshop',
            name='registered_phone',
            field=models.CharField(
                blank=True,
                db_comment='邮箱绑定号码',
                max_length=20,
                null=True,
            ),
        ),
    ]
