# Generated by Django 5.2.7 on 2025-12-29 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0037_remove_groupperformancetarget_group_perf_month_ops_group_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 5, 13, 55, 43, 141938), verbose_name='过期时间'),
        ),
    ]
