# Generated by Django 5.2.7 on 2026-04-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0038_alter_amazonshop_registered_phone_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLingxingLogisticsCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('logistics_key', models.CharField(choices=[('USPS', 'USPS'), ('FEDEX', 'FedEx'), ('DHL', 'DHL'), ('UNIUNI', 'UniUni'), ('GOFO', 'GOFO'), ('GOFO_US_WEST', '美西 GOFO'), ('SF_CD', '顺丰国际电商专递-CD'), ('SF_STANDARD', '顺丰国际电商专递-标准'), ('WEISUYI_US_SMALL', '威速易美国小货专线'), ('YUNTU_GLOBAL_REGISTERED', '云途全球专线挂号（标快普货）'), ('JD_IE_STANDARD', '京东普货标准专线-IE-01'), ('ES_FEDEX_GROUND_US_WEST', 'ES-FEDEX GROUND（美西）'), ('ES_FEDEX_HD_US_WEST', 'ES-FEDEX HD（美西）'), ('ES_USPS_GA_US_WEST', 'ES-USPS GA（美西）'), ('ES_USPS_PM_US_WEST', 'ES-USPS PM（美西）'), ('SWIFTX_US_WEST', 'SWIFTX EXPRESS（美西）')], db_comment='系统根据DIVI物流方式和单号识别出的物流键', max_length=64, verbose_name='物流识别键')),
                ('logistics_name', models.CharField(blank=True, db_comment='展示用名称，可与领星后台名称保持一致', max_length=100, verbose_name='物流名称')),
                ('logistics_type_id', models.CharField(db_comment='领星 fastOutbound 接口需要的 logistics_type_id', max_length=64, verbose_name='领星物流编码')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(db_comment='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='lingxing_logistics_codes', to='general.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目领星物流编码',
                'verbose_name_plural': '项目领星物流编码',
                'db_table': 'project_lingxing_logistics_codes',
                'ordering': ['project', 'logistics_key'],
                'indexes': [models.Index(fields=['project', 'enabled'], name='idx_project_lx_logi_enabled')],
                'constraints': [models.UniqueConstraint(fields=('project', 'logistics_key'), name='uniq_project_lx_logistics_key')],
            },
        ),
    ]
