# Generated by Django 5.2.7 on 2026-01-02 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0039_alter_announcement_valid_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 9, 17, 31, 0, 354969), verbose_name='过期时间'),
        ),
    ]
