# Generated by Django 5.2.7 on 2026-01-05 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0041_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 12, 13, 52, 8, 858495), verbose_name='过期时间'),
        ),
    ]
