# Generated by Django 5.2.7 on 2026-01-06 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0043_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 13, 14, 3, 23, 25554), verbose_name='过期时间'),
        ),
    ]
