# Generated by Django 5.2.7 on 2026-01-09 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0045_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupperformancetarget',
            name='stretch_target',
        ),
        migrations.RemoveField(
            model_name='personalperformancetarget',
            name='stretch_target',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 16, 9, 15, 0, 128275), verbose_name='过期时间'),
        ),
    ]
