# Generated by Django 5.2.7 on 2026-01-09 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0046_remove_groupperformancetarget_stretch_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='valid_to',
            field=models.DateTimeField(db_comment='公告停止显示时间', default=datetime.datetime(2026, 1, 16, 17, 27, 59, 650035), verbose_name='过期时间'),
        ),
    ]
