# Generated by Django 5.2.7 on 2025-12-17 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考核模板',
                'verbose_name_plural': '考核模板管理',
            },
        ),
        migrations.CreateModel(
            name='AssessmentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('department', models.CharField(max_length=50, verbose_name='部门')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('period', models.CharField(max_length=50, verbose_name='考核时段')),
                ('employee_signature', models.CharField(blank=True, max_length=50, verbose_name='被考核人签名')),
                ('employee_confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('manager_signature', models.CharField(blank=True, max_length=50, verbose_name='上级签名')),
                ('manager_confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='上级确认时间')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='总分')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='评级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('confirmed', '已确认')], default='draft', max_length=20, verbose_name='状态')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Yuser.assessmenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='权重')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Yuser.assessmenttemplate')),
            ],
            options={
                'verbose_name': '考核分类',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='满分分值')),
                ('scoring_type', models.CharField(choices=[('manual', '手动评分'), ('auto', '自动计算'), ('deduct', '扣分制'), ('bonus', '加分项')], default='manual', max_length=20, verbose_name='评分方式')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='计算公式')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Yuser.templatecategory')),
            ],
            options={
                'verbose_name': '考核项目',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScoringCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=300, verbose_name='条件描述')),
                ('score_rule', models.CharField(max_length=100, verbose_name='得分规则')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='Yuser.templateitem')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='实际得分')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Yuser.assessmentinstance')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yuser.templateitem')),
            ],
        ),
    ]
