# Generated by Django 5.2.7 on 2025-12-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatecategory',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_scores', to='Yuser.assessmentinstance'),
        ),
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='权重(%)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Yuser.assessmenttemplate')),
            ],
            options={
                'verbose_name': '考核分类',
                'verbose_name_plural': '考核分类管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分组名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Yuser.assessmentcategory')),
            ],
            options={
                'verbose_name': '考核分组',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=10, verbose_name='序号')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='详细说明')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='满分分值')),
                ('scoring_type', models.CharField(choices=[('manual', '手动评分'), ('auto', '自动计算'), ('deduct', '扣分制')], default='manual', max_length=20, verbose_name='评分方式')),
                ('formula', models.TextField(blank=True, null=True, verbose_name='计算公式')),
                ('is_zero_if_violated', models.BooleanField(default=False, verbose_name='违规则分数全无')),
                ('is_bonus_item', models.BooleanField(default=False, verbose_name='加分项')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Yuser.assessmentgroup')),
            ],
            options={
                'verbose_name': '考核项目',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Yuser.assessmentitem'),
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=300, verbose_name='条件描述')),
                ('deduction_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='每单位扣分')),
                ('score_rule', models.CharField(max_length=100, verbose_name='计分规则描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='Yuser.assessmentitem')),
            ],
            options={
                'verbose_name': '评分标准',
            },
        ),
        migrations.DeleteModel(
            name='ScoringCriteria',
        ),
        migrations.DeleteModel(
            name='TemplateCategory',
        ),
        migrations.DeleteModel(
            name='TemplateItem',
        ),
    ]
