# Generated by Django 5.2.7 on 2025-12-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuser', '0002_remove_templatecategory_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='yuser.assessmentcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='yuser.assessmentgroup'),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='scoring_type',
            field=models.CharField(choices=[('manual', '手动评分'), ('auto', '自动计算'), ('deduct', '扣分制'), ('bonus', '加分项')], default='manual', max_length=20, verbose_name='评分方式'),
        ),
    ]
