# Generated by Django 5.2.7 on 2025-12-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0038_alter_announcement_valid_to'),
        ('yuser', '0003_assessmentitem_category_alter_assessmentitem_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assessmentgroup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assessmentitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='assessmentinstance',
            name='template',
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='item',
        ),
        migrations.RemoveField(
            model_name='assessmentscore',
            name='item',
        ),
        migrations.CreateModel(
            name='AssessmentItemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_type', models.CharField(choices=[('temu_operation', 'Temu运营'), ('amazon_operation', '亚马逊运营'), ('amazon_assistant', '亚马逊运营助理')], max_length=20, verbose_name='考核类型')),
                ('item_key', models.CharField(max_length=50, verbose_name='评分项标识')),
                ('item_name', models.CharField(max_length=200, verbose_name='评分项名称')),
                ('category', models.CharField(choices=[('performance', '业绩指标'), ('behavior', '行为考核'), ('bonus', '加分项')], max_length=20, verbose_name='评分类别')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='满分值')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='类别内权重')),
                ('input_type', models.CharField(choices=[('readonly', '只读显示'), ('number', '数字输入'), ('select', '下拉选择')], default='number', max_length=20, verbose_name='输入类型')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='下拉选项配置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
            ],
            options={
                'verbose_name': '评分项配置',
                'verbose_name_plural': '评分项配置',
                'db_table': 'assessment_item_configs',
                'ordering': ['assess_type', 'sort_order'],
                'unique_together': {('assess_type', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_type', models.CharField(choices=[('temu_operation', 'Temu运营'), ('amazon_operation', '亚马逊运营'), ('amazon_assistant', '亚马逊运营助理')], max_length=20, verbose_name='考核类型')),
                ('month', models.CharField(max_length=7, verbose_name='考核月份')),
                ('target_orders', models.IntegerField(verbose_name='目标订单件数')),
                ('actual_orders', models.IntegerField(verbose_name='实际订单件数')),
                ('achievement_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='达成率')),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='业绩得分')),
                ('status', models.CharField(choices=[('draft', '组长评分中'), ('pending_member', '待组员确认'), ('pending_leader', '待组长最终确认'), ('confirmed', '已确认锁定')], default='draft', max_length=20, verbose_name='考核状态')),
                ('is_locked', models.BooleanField(default=False, verbose_name='是否锁定')),
                ('member_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='组员确认时间')),
                ('leader_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='组长最终确认时间')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='最终得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_as_leader', to=settings.AUTH_USER_MODEL)),
                ('performance_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.personalperformancetarget', verbose_name='关联绩效目标')),
            ],
            options={
                'verbose_name': '绩效考核记录',
                'verbose_name_plural': '绩效考核记录',
                'db_table': 'performance_assessments',
            },
        ),
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.JSONField(verbose_name='快照数据')),
                ('snapshot_type', models.CharField(default='final_confirm', max_length=20, verbose_name='快照类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='快照时间')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yuser.performanceassessment', verbose_name='原始考核记录')),
            ],
            options={
                'verbose_name': '考核历史快照',
                'verbose_name_plural': '考核历史快照',
                'db_table': 'assessment_histories',
            },
        ),
        migrations.CreateModel(
            name='PerformanceScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50, verbose_name='评分项标识')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='得分')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_details', to='yuser.performanceassessment', verbose_name='关联考核')),
            ],
            options={
                'verbose_name': '评分明细',
                'verbose_name_plural': '评分明细',
                'db_table': 'performance_score_details',
            },
        ),
        migrations.DeleteModel(
            name='AssessmentCategory',
        ),
        migrations.DeleteModel(
            name='AssessmentGroup',
        ),
        migrations.DeleteModel(
            name='AssessmentTemplate',
        ),
        migrations.DeleteModel(
            name='AssessmentInstance',
        ),
        migrations.DeleteModel(
            name='ScoringRule',
        ),
        migrations.DeleteModel(
            name='AssessmentItem',
        ),
        migrations.DeleteModel(
            name='AssessmentScore',
        ),
        migrations.AddIndex(
            model_name='performanceassessment',
            index=models.Index(fields=['month', 'employee', 'assess_type'], name='performance_month_ff7c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceassessment',
            index=models.Index(fields=['leader', 'status', 'month'], name='performance_leader__cfaf69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceassessment',
            unique_together={('employee', 'month', 'assess_type')},
        ),
        migrations.AddIndex(
            model_name='assessmenthistory',
            index=models.Index(fields=['assessment', '-created_at'], name='assessment__assessm_ccb8d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancescoredetail',
            unique_together={('assessment', 'item_key')},
        ),
    ]
