# Yuser/migrations/0004_init_assessment_items.py

from django.db import migrations


def init_assessment_items(apps, schema_editor):
    """初始化绩效考核评分项配置"""
    AssessmentItemConfig = apps.get_model('yuser', 'AssessmentItemConfig')

    # 清空旧数据（确保可重复执行）
    AssessmentItemConfig.objects.all().delete()

    # ==================== Temu运营考核配置 ====================
    temu_configs = [
        # 业绩指标 (100分, 权重70%)
        {
            'assess_type': 'temu_operation',
            'item_key': 'performance_score',
            'item_name': '业绩目标达成',
            'category': 'performance',
            'max_score': 90,
            'weight': 1.0,
            'input_type': 'readonly',
            'options': None,
            'sort_order': 10,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'accident_score',
            'item_name': '损失事故次数',
            'category': 'performance',
            'max_score': 10,
            'weight': 1.0,
            'input_type': 'number',
            'options': None,
            'sort_order': 20,
        },

        # 行为考核 (85分, 权重30%)
        {
            'assess_type': 'temu_operation',
            'item_key': 'activation_score',
            'item_name': '精铺店铺激活率百分百',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,  # 10/85
            'input_type': 'number',
            'options': None,
            'sort_order': 30,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'optimization_score',
            'item_name': '店铺链接优化',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 40,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'analysis_score',
            'item_name': '数据分析能力',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 50,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'fulfillment_score',
            'item_name': '上架商品、导单与发货',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 60,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'ad_roi_score',
            'item_name': '广告投入产出异常',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 70,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'violation_score',
            'item_name': '个人原因导致店铺违规',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "0次"}, {"value": 0, "label": "有违规"}],
            'sort_order': 80,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'low_price_score',
            'item_name': '未经申请同意低价销售',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "无"}, {"value": 0, "label": "有"}],
            'sort_order': 90,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'initiative_score',
            'item_name': '工作态度-工作主动性/闭环衔接',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,  # 5/85
            'input_type': 'number',
            'options': None,
            'sort_order': 100,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'compliance_score',
            'item_name': '工作态度-工作遵从度、完成度',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'number',
            'options': None,
            'sort_order': 110,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'discipline_score',
            'item_name': '工作态度-工作纪律态度',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "无违纪"}, {"value": 0, "label": "有违纪"}],
            'sort_order': 120,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'hygiene_score',
            'item_name': '工作态度-卫生情况',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "无问题"}, {"value": 0, "label": "有问题"}],
            'sort_order': 130,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'learning_score',
            'item_name': '自主能力-学习与创新能力',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'number',
            'options': None,
            'sort_order': 140,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'pressure_score',
            'item_name': '抗压能力-遇事冷静避免情绪失控',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'number',
            'options': None,
            'sort_order': 150,
        },

        # 加分项
        {
            'assess_type': 'temu_operation',
            'item_key': 'extra_bonus',
            'item_name': '加分项-超额完成业绩',
            'category': 'bonus',
            'max_score': 999,
            'weight': 1.0,
            'input_type': 'readonly',
            'options': None,
            'sort_order': 160,
        },
        {
            'assess_type': 'temu_operation',
            'item_key': 'shop_activation',
            'item_name': '加分项-店铺激活情况',
            'category': 'bonus',
            'max_score': 999,
            'weight': 1.0,
            'input_type': 'readonly',
            'options': None,
            'sort_order': 170,
        },
    ]

    # ==================== 亚马逊运营考核配置 ====================
    amazon_configs = [
        # 业绩指标 (100分, 权重60%)
        {
            'assess_type': 'amazon_operation',
            'item_key': 'performance_score',
            'item_name': '业绩目标达成',
            'category': 'performance',
            'max_score': 90,
            'weight': 1.0,
            'input_type': 'readonly',
            'options': None,
            'sort_order': 10,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'accident_score',
            'item_name': '损失事故次数',
            'category': 'performance',
            'max_score': 10,
            'weight': 1.0,
            'input_type': 'number',
            'options': None,
            'sort_order': 20,
        },

        # 行为考核 (85分, 权重40%)
        {
            'assess_type': 'amazon_operation',
            'item_key': 'link_mistake_score',
            'item_name': '业务考核-链接操作失误',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "无失误"}, {"value": 0, "label": "有失误"}],
            'sort_order': 30,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'ad_roi_score',
            'item_name': '业务考核-广告投入产出异常',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 40,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'violation_score',
            'item_name': '业务考核-个人原因导致店铺异常',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "无异常"}, {"value": 0, "label": "有异常"}],
            'sort_order': 50,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'low_price_score',
            'item_name': '业务考核-未经申请同意低价销售',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "无低价销售"}, {"value": 0, "label": "有低价销售"}],
            'sort_order': 60,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'initiative_score',
            'item_name': '工作态度-工作主动性/闭环衔接',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 70,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'compliance_score',
            'item_name': '工作态度-工作遵从度',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 80,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'completion_score',
            'item_name': '工作态度-工作完成度',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 90,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'participation_score',
            'item_name': '工作态度-工作参与性',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 100,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'discipline_score',
            'item_name': '工作态度-工作纪律态度',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "无违纪"}, {"value": 0, "label": "有违纪"}],
            'sort_order': 110,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'hygiene_score',
            'item_name': '工作态度-卫生情况问题',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "无问题"}, {"value": 0, "label": "有问题"}],
            'sort_order': 120,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'pressure_score',
            'item_name': '抗压能力-遇事保持冷静',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'number',
            'options': None,
            'sort_order': 130,
        },
        {
            'assess_type': 'amazon_operation',
            'item_key': 'learning_score',
            'item_name': '学习能力-学习后能够理清',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "达标"}, {"value": 0, "label": "不达标"}],
            'sort_order': 140,
        },

        # 加分项
        {
            'assess_type': 'amazon_operation',
            'item_key': 'extra_bonus',
            'item_name': '加分项-超额完成业绩',
            'category': 'bonus',
            'max_score': 999,
            'weight': 1.0,
            'input_type': 'readonly',
            'options': None,
            'sort_order': 150,
        },
    ]

    # ==================== 亚马逊运营助理考核配置 ====================
    assistant_configs = [
        # 业绩指标 (100分, 权重30%)
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'performance_score',
            'item_name': '业绩目标达成',
            'category': 'performance',
            'max_score': 80,
            'weight': 1.0,
            'input_type': 'readonly',
            'options': None,
            'sort_order': 10,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'accident_score',
            'item_name': '损失事故次数',
            'category': 'performance',
            'max_score': 20,
            'weight': 1.0,
            'input_type': 'number',
            'options': None,
            'sort_order': 20,
        },

        # 行为考核 (85分, 权重70%)
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'link_mistake_score',
            'item_name': '业务考核-链接操作失误',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "无失误"}, {"value": 0, "label": "有失误"}],
            'sort_order': 30,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'ad_roi_score',
            'item_name': '业务考核-广告投入产出异常',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 40,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'violation_score',
            'item_name': '业务考核-个人原因导致店铺异常',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "无异常"}, {"value": 0, "label": "有异常"}],
            'sort_order': 50,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'low_price_score',
            'item_name': '业务考核-未经申请同意低价销售',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'select',
            'options': [{"value": 10, "label": "无低价销售"}, {"value": 0, "label": "有低价销售"}],
            'sort_order': 60,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'initiative_score',
            'item_name': '工作态度-工作主动性/闭环衔接',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 70,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'compliance_score',
            'item_name': '工作态度-工作遵从度',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 80,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'completion_score',
            'item_name': '工作态度-工作完成度',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 90,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'participation_score',
            'item_name': '工作态度-工作参与性',
            'category': 'behavior',
            'max_score': 10,
            'weight': 0.1176,
            'input_type': 'number',
            'options': None,
            'sort_order': 100,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'discipline_score',
            'item_name': '工作态度-工作纪律态度',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "无违纪"}, {"value": 0, "label": "有违纪"}],
            'sort_order': 110,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'hygiene_score',
            'item_name': '工作态度-卫生情况问题',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "无问题"}, {"value": 0, "label": "有问题"}],
            'sort_order': 120,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'pressure_score',
            'item_name': '抗压能力-遇事保持冷静',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'number',
            'options': None,
            'sort_order': 130,
        },
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'learning_score',
            'item_name': '学习能力-学习后能够理清',
            'category': 'behavior',
            'max_score': 5,
            'weight': 0.0588,
            'input_type': 'select',
            'options': [{"value": 5, "label": "达标"}, {"value": 0, "label": "不达标"}],
            'sort_order': 140,
        },

        # 加分项
        {
            'assess_type': 'amazon_assistant',
            'item_key': 'extra_bonus',
            'item_name': '加分项-超额完成业绩',
            'category': 'bonus',
            'max_score': 999,
            'weight': 1.0,
            'input_type': 'readonly',
            'options': None,
            'sort_order': 150,
        },
    ]

    # 批量创建所有配置
    all_configs = temu_configs + amazon_configs + assistant_configs
    for config in all_configs:
        AssessmentItemConfig.objects.create(**config)


def reverse_init_assessment_items(apps, schema_editor):
    """反向迁移：删除所有配置数据"""
    AssessmentItemConfig = apps.get_model('yuser', 'AssessmentItemConfig')
    AssessmentItemConfig.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('yuser', '0004_remove_assessmentitem_category_and_more'),  # 请修改为实际的上一个迁移文件名
    ]

    operations = [
        migrations.RunPython(init_assessment_items, reverse_init_assessment_items),
    ]