# Generated by Django 5.2.7 on 2025-12-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuser', '0005_init_assessment_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitemconfig',
            name='scoring_criteria',
            field=models.TextField(blank=True, help_text='详细的评分规则和标准说明', null=True, verbose_name='评分标准说明'),
        ),
    ]
