# Generated by Django 5.2.7 on 2025-12-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yuser', '0006_assessmentitemconfig_scoring_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交的快照时间'),
        ),
    ]
