# Generated by Django 5.2.7 on 2026-01-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zother', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bargainingorder',
            table='Zother_bargainingorder',
        ),
    ]
