# Generated by Django 5.2.7 on 2026-02-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zother', '0002_alter_bargainingorder_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bargainingorder',
            table='zother_bargainingorder',
        ),
    ]
