# Generated by Django 5.2.7 on 2026-01-06 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(db_comment='任务主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('title', models.CharField(db_comment='任务标题', max_length=200, verbose_name='任务标题')),
                ('task_no', models.CharField(db_comment='自动生成的任务单号', editable=False, max_length=50, unique=True, verbose_name='任务单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待执行'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], db_comment='任务当前状态', default='draft', max_length=20, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='任务创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='任务最后更新时间', verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='任务提交时间（非草稿状态）', null=True, verbose_name='提交时间')),
                ('created_by', models.ForeignKey(db_comment='任务的创建人', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('owner', models.ForeignKey(db_comment='任务的所有者（执行人）', on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='任务所有者')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务列表',
                'db_table': 'task_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(db_comment='子任务主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('subtask_type', models.CharField(choices=[('custom_upload', '定制上架'), ('temu_export', 'Temu导单')], db_comment='子任务类型：custom_upload/temu_export', max_length=20, verbose_name='子任务类型')),
                ('order', models.IntegerField(db_comment='子任务的执行顺序（用于前端拖拽排序）', default=0, verbose_name='执行顺序')),
                ('params', models.JSONField(db_comment='子任务的具体参数（不同类型结构不同）', default=dict, verbose_name='任务参数')),
                ('is_executed', models.BooleanField(db_comment='子任务是否已执行', default=False, verbose_name='是否已执行')),
                ('executed_at', models.DateTimeField(blank=True, db_comment='子任务实际执行时间', null=True, verbose_name='执行时间')),
                ('execution_result', models.JSONField(blank=True, db_comment='子任务执行结果（成功/失败详情）', default=dict, null=True, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='子任务创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='子任务最后更新时间', verbose_name='更新时间')),
                ('task', models.ForeignKey(db_comment='关联的主任务ID', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='Task.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '子任务',
                'verbose_name_plural': '子任务列表',
                'db_table': 'task_subtasks',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(db_comment='模板主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('name', models.CharField(db_comment='模板的名称', max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, db_comment='模板的详细描述', null=True, verbose_name='模板描述')),
                ('content', models.JSONField(db_comment='模板包含的子任务配置数组', default=list, verbose_name='模板内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='模板创建时间', verbose_name='创建时间')),
                ('created_by', models.ForeignKey(db_comment='模板的创建人', on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '任务模板',
                'verbose_name_plural': '任务模板列表',
                'db_table': 'task_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'created_at'], name='idx_task_status_created'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status'], name='idx_task_owner_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_no'], name='idx_task_no_unique'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'order'], name='idx_subtask_task_order'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['subtask_type', 'is_executed'], name='idx_subtask_type_status'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['created_by', 'created_at'], name='idx_template_user_created'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['name'], name='idx_template_name'),
        ),
    ]
