# Generated by Django 5.2.7 on 2026-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('custom_upload', '定制上架'), ('temu_export', 'Temu导单'), ('amazon_upload', 'Amazon上传商品')], db_comment='子任务类型：custom_upload/temu_export', max_length=20, verbose_name='子任务类型'),
        ),
    ]
