# Generated by Django 5.2.7 on 2026-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_subtask_subtask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('standard', '标准任务'), ('product_requirement', '产品需求')], db_comment='任务类型：standard/product_requirement', default='standard', max_length=50, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('custom_upload', '定制上架'), ('temu_export', 'Temu导单')], db_comment='子任务类型：custom_upload/temu_export', max_length=20, verbose_name='子任务类型'),
        ),
    ]
