# Generated by Django 5.2.7 on 2026-01-17 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_task_type_alter_subtask_subtask_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('custom_upload', '定制上架'), ('temu_export', 'Temu导单'), ('print_external', '印花外采')], db_comment='子任务类型：custom_upload/temu_export', max_length=20, verbose_name='子任务类型'),
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(db_comment='产品需求主键ID', primary_key=True, serialize=False, verbose_name='主键ID')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('approved', '已审核'), ('processing', '抓取中'), ('designing', '设计中'), ('uploading', '上传中'), ('testing', '测试中'), ('completed', '已完成')], db_comment='需求状态', default='submitted', max_length=20, verbose_name='状态')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品名称')),
                ('product_abbr', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品简称')),
                ('english_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名称')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品材质')),
                ('craft', models.JSONField(blank=True, db_comment='多选：生产工艺列表', default=list, null=True, verbose_name='生产工艺')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='计量单位')),
                ('customs_cn_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='报关中文名称')),
                ('customs_en_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='报关英文名称')),
                ('declared_weight', models.IntegerField(blank=True, null=True, verbose_name='申报重量(克)')),
                ('declared_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='海关申报单价(USD)')),
                ('customs_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='海关申报编码')),
                ('material_cn', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品材质(中文)')),
                ('material_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品材质(英文)')),
                ('material_desc', models.TextField(blank=True, null=True, verbose_name='材质说明')),
                ('accessory_struct', models.TextField(blank=True, null=True, verbose_name='配件构造')),
                ('product_performance', models.TextField(blank=True, null=True, verbose_name='产品性能')),
                ('applicable_scenario', models.TextField(blank=True, null=True, verbose_name='适用情景')),
                ('washing_instructions', models.TextField(blank=True, null=True, verbose_name='洗涤说明')),
                ('special_note', models.TextField(blank=True, null=True, verbose_name='特别说明')),
                ('reminder', models.TextField(blank=True, null=True, verbose_name='温馨提醒')),
                ('design_desc', models.TextField(blank=True, null=True, verbose_name='设计说明')),
                ('design_area', models.TextField(blank=True, null=True, verbose_name='设计区域')),
                ('image_requirement', models.TextField(blank=True, null=True, verbose_name='图片要求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(db_comment='创建人', on_delete=django.db.models.deletion.CASCADE, related_name='created_product_requirements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('task', models.OneToOneField(blank=True, db_comment='关联的任务ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requirement', to='task.task', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '产品需求',
                'verbose_name_plural': '产品需求列表',
                'db_table': 'task_product_requirements',
                'ordering': ['-created_at'],
            },
        ),
    ]
