# Generated by Django 5.2.7 on 2026-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_subtask_subtask_type_productrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='platform',
            field=models.CharField(choices=[('yizhiguan', '艺之冠')], db_comment='外采平台：yizhiguan', default='yizhiguan', max_length=50, verbose_name='外采平台'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='product_url',
            field=models.URLField(blank=True, db_comment='外采产品链接', max_length=500, null=True, verbose_name='产品链接'),
        ),
    ]
