# Generated by Django 5.2.7 on 2026-01-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_productrequirement_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('custom_upload', '定制上架'), ('temu_export', 'Temu导单'), ('print_external', '印花外采'), ('embroidery', '刺绣')], db_comment='子任务类型：custom_upload/temu_export', max_length=20, verbose_name='子任务类型'),
        ),
    ]
