# Generated by Django 5.2.7 on 2026-01-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_subtask_subtask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequirement',
            name='craft',
            field=models.CharField(blank=True, choices=[('印花', '印花'), ('刺绣', '刺绣'), ('镭射', '镭射')], db_comment='单选：生产工艺', max_length=50, null=True, verbose_name='生产工艺'),
        ),
    ]
