# Generated by Django 5.2.7 on 2026-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_productrequirement_craft'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='requirement_no',
            field=models.CharField(blank=True, db_comment='冗余：对应Task的task_no', max_length=50, null=True, verbose_name='需求单号'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='title',
            field=models.CharField(blank=True, db_comment='冗余：对应Task的title', max_length=200, null=True, verbose_name='需求标题'),
        ),
    ]
