# Generated by Django 5.2.7 on 2026-01-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_productrequirement_requirement_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='product_id',
            field=models.CharField(blank=True, db_comment='从URL提取的平台唯一ID', max_length=100, null=True, verbose_name='平台产品ID'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='platform',
            field=models.CharField(choices=[('yizhiguan', '艺之冠'), ('s2b', 'S2B')], db_comment='外采平台：yizhiguan, s2b', default='yizhiguan', max_length=50, verbose_name='外采平台'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='status',
            field=models.CharField(choices=[('submitted', '已提交'), ('approved', '已审核'), ('processing', '抓取中'), ('designing', '设计中'), ('uploading', '上传中'), ('testing', '测试中'), ('completed', '已完成'), ('rejected', '已驳回')], db_comment='需求状态', default='submitted', max_length=20, verbose_name='状态'),
        ),
    ]
