# Generated by Django 5.2.7 on 2026-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_productrequirement_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequirement',
            name='platform',
            field=models.CharField(choices=[('yizhiguan', '艺之冠'), ('s2b', 'S2B'), ('amazon', 'Amazon'), ('temu', 'Temu')], db_comment='外采平台：yizhiguan, s2b, amazon, temu', default='yizhiguan', max_length=50, verbose_name='外采平台'),
        ),
    ]
