# Generated by Django 5.2.7 on 2026-01-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_productrequirement_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequirement',
            name='platform',
            field=models.CharField(choices=[('yizhiguan', '艺之冠'), ('s2b', 'S2B')], db_comment='外采平台：yizhiguan, s2b', default='yizhiguan', max_length=50, verbose_name='外采平台'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='status',
            field=models.CharField(choices=[('submitted', '已提交'), ('approved', '已审核'), ('processing', '抓取中'), ('pending_design', '待设计'), ('designing', '设计中'), ('uploading', '上传中'), ('testing', '测试中'), ('completed', '已完成'), ('rejected', '已驳回')], db_comment='需求状态', default='submitted', max_length=20, verbose_name='状态'),
        ),
    ]
