# Generated by Django 5.2.7 on 2026-01-19 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_productrequirement_platform_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='owner',
            field=models.ForeignKey(blank=True, db_comment='需求负责人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_product_requirements', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='task',
            field=models.OneToOneField(blank=True, db_comment='关联的任务ID (旧数据兼容)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_requirement', to='task.task', verbose_name='关联任务'),
        ),
    ]
