# Generated by Django 5.2.7 on 2026-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_productrequirement_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
