# Generated by Django 5.2.7 on 2026-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_productrequirement_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='listing_platform',
            field=models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('temu', 'Temu')], db_comment='上架平台：amazon, temu', max_length=50, null=True, verbose_name='上架平台'),
        ),
    ]
