# Generated by Django 5.2.7 on 2026-01-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_productrequirement_listing_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='color_name',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='颜色列表'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='img_urls_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='图片链接列表'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='packaging_size_cm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包装尺寸(cm)'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='packaging_size_inch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包装尺寸(inch)'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='packaging_volumn_cm3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包装体积(cm3)'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='packaging_volumn_inch3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包装体积(inch3)'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='packaging_weight_g',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包装重量(g)'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='packaging_weight_lb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='包装重量(lb)'),
        ),
    ]
