# Generated by Django 5.2.7 on 2026-01-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_productrequirement_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='product_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品标识'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='special_cargo_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='特殊货物类型'),
        ),
    ]
