# Generated by Django 5.2.7 on 2026-01-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_productrequirement_trademark_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequirement',
            name='packaging_size_cm',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='packaging_size_inch',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='packaging_volumn_cm3',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='packaging_volumn_inch3',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='packaging_weight_g',
        ),
        migrations.RemoveField(
            model_name='productrequirement',
            name='packaging_weight_lb',
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='packaging_specification',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='包装规格'),
        ),
    ]
