# Generated by Django 5.2.7 on 2026-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_remove_productrequirement_packaging_size_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='size_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='尺码列表'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='img_urls_list',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='图片链接'),
        ),
    ]
