# Generated by Django 5.2.7 on 2026-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_productrequirement_size_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='product_size',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='产品尺码表'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='craft',
            field=models.CharField(blank=True, choices=[('印花', '印花'), ('刺绣', '刺绣'), ('镭射', '镭射'), ('成品', '成品')], db_comment='单选：生产工艺', max_length=50, null=True, verbose_name='生产工艺'),
        ),
    ]
