# Generated by Django 5.2.7 on 2026-01-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_productrequirement_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequirement',
            name='title',
        ),
    ]
