# Generated by Django 5.2.7 on 2026-01-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_remove_productrequirement_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='designer',
            field=models.ForeignKey(blank=True, db_comment='美工负责人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_product_requirements', to=settings.AUTH_USER_MODEL, verbose_name='美工'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('created', '创建完成'), ('pending_crawl', '等待数据抓取'), ('crawled', '数据抓取完成'), ('pending_confirm', '等待数据确认'), ('confirmed', '数据确认完成'), ('pending_review', '等待审核'), ('reviewed', '审核完成'), ('pending_design', '等待美工处理样机'), ('designed', '样机处理成功'), ('pending_divi_test', '等待系统上传DIVI测试'), ('divi_tested', '上传DIVI测试已完成'), ('uploading', '系统上传DIVI中'), ('completed', '上传DIVI已完成'), ('rejected', '已驳回'), ('crawl_failed', '抓取失败'), ('cancelled', '已取消')], db_comment='需求状态', default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
