# Generated by Django 5.2.7 on 2026-01-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_alter_productrequirement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPlatformProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_divi_code', models.CharField(help_text='divi_产品编码', max_length=100, unique=True, verbose_name='产品编号')),
                ('product_name', models.CharField(help_text='产品完整名称', max_length=255, verbose_name='产品名称')),
                ('is_listed', models.BooleanField(default=False, help_text='True=已上架，False=未上架', verbose_name='是否上架')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='颜色')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格')),
                ('divi_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='DIVI颜色')),
                ('divi_specification', models.CharField(blank=True, max_length=50, null=True, verbose_name='DIVI规格')),
                ('min_order_quantity', models.IntegerField(default=1, help_text='单次采购最低数量', verbose_name='起批量')),
                ('purchase_unit_price', models.DecimalField(decimal_places=2, help_text='原始采购单价（元）', max_digits=10, verbose_name='采购原单价')),
                ('new_price', models.DecimalField(decimal_places=2, help_text='现采购单价（元）', max_digits=10, verbose_name='采购现单价')),
                ('platform_name', models.CharField(help_text='如：艺之冠等', max_length=100, verbose_name='外采平台')),
                ('order_link', models.URLField(blank=True, help_text='外部平台的产品下单页面URL', max_length=500, null=True, verbose_name='下单链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '外采平台产品',
                'verbose_name_plural': '外采平台产品',
                'db_table': 'procurement_external_platform_product',
                'ordering': ['-created_at'],
            },
        ),
    ]
