# Generated by Django 5.2.7 on 2026-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_externalplatformproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalplatformproduct',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='现采购单价（元）', max_digits=10, null=True, verbose_name='采购现单价'),
        ),
        migrations.AlterField(
            model_name='externalplatformproduct',
            name='purchase_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='原始采购单价（元）', max_digits=10, null=True, verbose_name='采购原单价'),
        ),
    ]
