# Generated by Django 5.2.7 on 2026-01-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_amazonshop_qupital_if'),
        ('task', '0025_alter_externalplatformproduct_new_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonUploadFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('shop_name_suffix', models.CharField(db_comment='提取的数字法人间，如"16蔡婉婷"', max_length=100, verbose_name='店铺后缀')),
                ('excel_filename', models.CharField(db_comment='完整的Excel文件名', max_length=255, verbose_name='Excel文件名')),
                ('target_path', models.CharField(db_comment='完整的UNC路径', max_length=500, verbose_name='目标路径')),
                ('status', models.CharField(choices=[('pending', '待上传'), ('uploading', '上传中'), ('completed', '已完成'), ('failed', '上传失败')], db_comment='文件上传状态', default='pending', max_length=20, verbose_name='上传状态')),
                ('success_sku', models.IntegerField(blank=True, db_comment='成功上传的SKU数量', null=True, verbose_name='成功SKU数')),
                ('total_sku', models.IntegerField(blank=True, db_comment='Excel中的总SKU数量', null=True, verbose_name='总SKU数')),
                ('uploaded_at', models.DateTimeField(blank=True, db_comment='影刀标记完成的时间', null=True, verbose_name='上传完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='记录创建时间', verbose_name='创建时间')),
                ('amazon_shop', models.ForeignKey(db_comment='关联的Amazon店铺', on_delete=django.db.models.deletion.CASCADE, related_name='upload_files', to='general.amazonshop', verbose_name='所属店铺')),
                ('subtask', models.ForeignKey(db_comment='关联的子任务', on_delete=django.db.models.deletion.CASCADE, related_name='amazon_upload_files', to='task.subtask', verbose_name='所属子任务')),
                ('task', models.ForeignKey(db_comment='关联的主任务', on_delete=django.db.models.deletion.CASCADE, related_name='amazon_upload_files', to='task.task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'Amazon上传文件',
                'verbose_name_plural': 'Amazon上传文件列表',
                'db_table': 'task_amazon_upload_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'status'], name='idx_amazon_upload_task_status'), models.Index(fields=['amazon_shop', 'status'], name='idx_amazon_upload_shop_status'), models.Index(fields=['created_at'], name='idx_amazon_upload_created')],
            },
        ),
    ]
