# Generated by Django 5.2.7 on 2026-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_amazonuploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='subtask_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待执行'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '执行失败'), ('cancelled', '已取消')], db_comment='任务当前状态', default='draft', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('custom_upload', '定制上架'), ('temu_export', 'Temu导单'), ('print_external', '印花外采'), ('multi_side_custom', '多面定制'), ('amazon_upload', 'Amazon上架'), ('divi_auto_upload', 'Divi自动上架')], db_comment='子任务类型', default='custom_upload', max_length=20, verbose_name='子任务类型'),
        ),
    ]
