# Generated by Django 5.2.7 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_subtask_subtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(
                choices=[
                    ('custom_upload', '定制上架'),
                    ('temu_export', 'Temu导单'),
                    ('print_external', '印花外采'),
                    ('multi_side_custom', '多面定制'),
                    ('amazon_upload', 'Amazon上架'),
                    ('divi_auto_upload', 'Divi自动上架'),
                ],
                db_comment='子任务类型：custom_upload/temu_export',
                max_length=20,
                verbose_name='子任务类型',
            ),
        ),
    ]
