# Generated by Django 5.2.9 on 2026-03-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_subtask_subtask_status_alter_subtask_subtask_type'),
        ('task', '0029_alter_subtask_subtask_type'),
    ]

    operations = [
    ]
