# Generated by Django 5.2.7 on 2026-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_merge_20260311_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('divi_multi_side_custom', '迪唯多面定制'), ('divi_custom', '迪唯批量定制'), ('divi_export', '迪唯汇出'), ('divi_gallery_upload', 'DIVI图库上传'), ('custom_upload', '定制上架'), ('temu_export', 'Temu导单'), ('print_external', '印花外采'), ('amazon_upload', 'Amazon上架'), ('divi_auto_upload', 'Divi自动上架')], db_comment='子任务类型：divi_multi_side_custom/divi_custom/divi_export/divi_gallery_upload', max_length=30, verbose_name='子任务类型'),
        ),
    ]
