# Generated by Django 5.2.7 on 2026-04-02 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_amazonlistinglegacy_amazonlistingv2_and_more'),
        ('general', '0027_temushop_height_temushop_length_temushop_weight_and_more'),
        ('task', '0031_alter_subtask_subtask_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='审批单号')),
                ('approval_type', models.CharField(choices=[('amazon_ad', 'Amazon开广告')], db_comment='审批业务类型', default='amazon_ad', max_length=30, verbose_name='审批类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回')], db_comment='审批流程状态', default='draft', max_length=20, verbose_name='审批状态')),
                ('current_step_sequence', models.IntegerField(db_comment='当前待审批的步骤序号', default=0, verbose_name='当前步骤序号')),
                ('total_steps', models.IntegerField(db_comment='审批步骤总数', default=0, verbose_name='总步骤数')),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='申请人提交审批时间', null=True, verbose_name='提交时间')),
                ('completed_at', models.DateTimeField(blank=True, db_comment='审批流程结束时间', null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(db_comment='发起审批的用户', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('original_approval', models.ForeignKey(blank=True, db_comment='驳回后重新提交的原始审批单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reapply_list', to='task.approval', verbose_name='原始审批')),
            ],
            options={
                'verbose_name': '审批单',
                'verbose_name_plural': '审批单列表',
                'db_table': 'approval_main',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmazonAdApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('approval', models.OneToOneField(db_comment='对应的审批主表', on_delete=django.db.models.deletion.CASCADE, related_name='ad_detail', to='task.approval', verbose_name='关联审批单')),
            ],
            options={
                'verbose_name': '开广告审批详情',
                'verbose_name_plural': '开广告审批详情列表',
                'db_table': 'approval_amazon_ad',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(db_comment='从1开始的步骤顺序', verbose_name='步骤序号')),
                ('step_name', models.CharField(db_comment='如：组长审批、主管审批', max_length=50, verbose_name='步骤名称')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('completed', '已完成'), ('skipped', '已跳过')], db_comment='步骤执行状态', default='pending', max_length=20, verbose_name='步骤状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approval', models.ForeignKey(db_comment='关联的审批主表', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='task.approval', verbose_name='所属审批')),
                ('approver', models.ForeignKey(blank=True, db_comment='该步骤的审批人（创建时确定）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='指定审批人')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '审批步骤',
                'verbose_name_plural': '审批步骤列表',
                'db_table': 'approval_steps',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回')], db_comment='通过或驳回', max_length=20, verbose_name='审批结果')),
                ('comment', models.TextField(blank=True, db_comment='审批人的意见', verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('approver', models.ForeignKey(db_comment='实际执行审批的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_records', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('step', models.ForeignKey(db_comment='关联的审批步骤', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='task.approvalstep', verbose_name='所属步骤')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录列表',
                'db_table': 'approval_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegativeKeywordLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_type', models.CharField(choices=[('official', '官方词库'), ('personal', '个人词库')], db_comment='官方词库或个人词库', default='personal', max_length=10, verbose_name='词库类型')),
                ('name', models.CharField(max_length=100, verbose_name='词库名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('keywords', models.JSONField(db_comment='否定词字符串列表', default=list, help_text='格式：["否定词1", "否定词2"]', verbose_name='否定词列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, db_comment='官方词库此字段为空', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '否定词库',
                'verbose_name_plural': '否定词库列表',
                'db_table': 'approval_negative_keyword_libraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmazonAdShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_status', models.CharField(choices=[('pending', '待执行'), ('executing', '执行中'), ('completed', '执行成功'), ('failed', '执行失败')], db_comment='RPA执行状态', default='pending', max_length=20, verbose_name='执行状态')),
                ('exec_result', models.JSONField(blank=True, db_comment='RPA返回结果', default=dict, verbose_name='执行结果')),
                ('webhook_task_id', models.CharField(blank=True, db_comment='用于匹配Webhook回调', max_length=100, verbose_name='RPA任务ID')),
                ('sequence', models.IntegerField(db_comment='组间执行顺序', default=0, verbose_name='执行顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amazon_ad', models.ForeignKey(db_comment='关联的开广告审批', on_delete=django.db.models.deletion.CASCADE, related_name='shop_configs', to='task.amazonadapproval', verbose_name='所属审批')),
                ('asins', models.ManyToManyField(db_comment='需要开广告的ASIN', to='amazon.amazonlistingv2', verbose_name='ASIN列表')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('lingxing_shop', models.ForeignKey(db_comment='广告创建的店铺', on_delete=django.db.models.deletion.CASCADE, to='amazon.lingxingamazonshop', verbose_name='领星店铺')),
                ('negative_keyword_lib', models.ForeignKey(blank=True, db_comment='应用的否定词库', null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.negativekeywordlibrary', verbose_name='否定词库')),
            ],
            options={
                'verbose_name': '开广告店铺配置',
                'verbose_name_plural': '开广告店铺配置列表',
                'db_table': 'approval_amazon_ad_shop_config',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['company', 'status'], name='idx_approval_company_status'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['company', 'approval_type'], name='idx_approval_company_type'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['applicant', 'status'], name='idx_approval_applicant_status'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['submitted_at'], name='idx_approval_submitted'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['company', 'approval'], name='idx_step_company_approval'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approval', 'status'], name='idx_step_approval_status'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['approver', 'status'], name='idx_step_approver_status'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('approval', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['company', 'step'], name='idx_record_company_step'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['step', 'result'], name='idx_record_step_result'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['approver'], name='idx_record_approver'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['created_at'], name='idx_record_created'),
        ),
        migrations.AddIndex(
            model_name='negativekeywordlibrary',
            index=models.Index(fields=['company', 'lib_type'], name='idx_nklib_company_type'),
        ),
        migrations.AddIndex(
            model_name='negativekeywordlibrary',
            index=models.Index(fields=['company', 'is_active'], name='idx_nklib_company_active'),
        ),
        migrations.AddIndex(
            model_name='amazonadshopconfig',
            index=models.Index(fields=['company', 'amazon_ad'], name='idx_adshop_company_ad'),
        ),
        migrations.AddIndex(
            model_name='amazonadshopconfig',
            index=models.Index(fields=['company', 'exec_status'], name='idx_adshop_company_exec'),
        ),
        migrations.AddIndex(
            model_name='amazonadshopconfig',
            index=models.Index(fields=['lingxing_shop'], name='idx_adshop_shop'),
        ),
        migrations.AddIndex(
            model_name='amazonadshopconfig',
            index=models.Index(fields=['webhook_task_id'], name='idx_adshop_webhook'),
        ),
    ]
