# Generated by Django 5.2.7 on 2026-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_amazonlistinglegacy_amazonlistingv2_and_more'),
        ('task', '0032_approval_amazonadapproval_approvalstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonadshopconfig',
            name='asins',
            field=models.ManyToManyField(to='amazon.amazonlistingv2', verbose_name='ASIN列表'),
        ),
    ]
