# Generated by Django 5.2.7 on 2026-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_alter_amazonadshopconfig_asins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='current_step_sequence',
            field=models.IntegerField(db_comment='当前待审批的步骤序号', default=-1, verbose_name='当前步骤序号'),
        ),
    ]
