# Generated by Django 5.2.7 on 2026-04-06 16:00

from django.db import migrations, models


def migrate_current_step_sequence_forward(apps, schema_editor):
    Approval = apps.get_model('task', 'Approval')

    Approval.objects.filter(status='pending', current_step_sequence=1).update(current_step_sequence=0)
    Approval.objects.filter(status='pending', current_step_sequence=2).update(current_step_sequence=1)
    Approval.objects.filter(status='rejected', current_step_sequence=1).update(current_step_sequence=0)
    Approval.objects.filter(status='rejected', current_step_sequence=2).update(current_step_sequence=1)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0034_alter_approval_current_step_sequence'),
    ]

    operations = [
        migrations.RunPython(migrate_current_step_sequence_forward, noop_reverse),
        migrations.AlterField(
            model_name='approval',
            name='current_step_sequence',
            field=models.IntegerField(
                db_comment='审批进度序号：-1草稿，0待组长，1待主管，2全部完成',
                default=-1,
                verbose_name='当前步骤序号',
            ),
        ),
    ]
