# Generated by Django 5.2.7 on 2026-04-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0037_add_amazon_exempt_subtask_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequirement',
            name='webhook_payload',
            field=models.JSONField(blank=True, db_comment='创建时发送的 webhook JSON 数据', null=True, verbose_name='Webhook payload'),
        ),
        migrations.AddField(
            model_name='task',
            name='webhook_payload',
            field=models.JSONField(blank=True, db_comment='创建时发送的 webhook JSON 数据', null=True, verbose_name='Webhook payload'),
        ),
        migrations.AlterField(
            model_name='amazonadshopconfig',
            name='exec_status',
            field=models.CharField(choices=[('waiting', '待执行'), ('executing', '执行中'), ('success', '执行成功'), ('failed', '执行失败')], db_comment='RPA执行状态', default='waiting', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '审批中'), ('approved', '已通过'), ('rejected', '已驳回'), ('waiting', '待执行'), ('executing', '执行中'), ('success', '执行成功'), ('failed', '执行失败')], db_comment='审批流程状态', default='draft', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('completed', '已完成'), ('skipped', '已跳过'), ('waiting', '待执行'), ('executing', '执行中'), ('success', '执行成功'), ('failed', '执行失败')], db_comment='步骤执行状态', default='pending', max_length=20, verbose_name='步骤状态'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('divi_multi_side_custom', '迪唯多面定制'), ('divi_custom', '迪唯批量定制'), ('divi_export', '迪唯汇出'), ('divi_export_pro', '迪唯汇出上架-Pro'), ('amazon_exempt', 'Amazon UPC豁免'), ('divi_gallery_upload', 'DIVI图库上传'), ('custom_upload', '定制上架'), ('temu_export', 'Temu导单'), ('print_external', '印花外采'), ('amazon_upload', 'Amazon上架'), ('divi_auto_upload', 'Divi自动上架')], db_comment='子任务类型：divi_multi_side_custom/divi_custom/divi_export/divi_export_pro/divi_gallery_upload', max_length=30, verbose_name='子任务类型'),
        ),
    ]
