# Generated by Django 5.2.7 on 2026-04-14 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divi', '0005_diviexporttemplate_template_type_and_more'),
        ('general', '0033_alter_amazonshop_shop_status'),
        ('task', '0038_productrequirement_webhook_payload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExportShopProductPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divi.product', verbose_name='产品')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.amazonshop', verbose_name='汇出店铺')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_shop_prefs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户汇出店铺产品偏好',
                'verbose_name_plural': '用户汇出店铺产品偏好',
                'db_table': 'task_user_export_shop_product_preference',
                'unique_together': {('user', 'shop', 'product')},
            },
        ),
    ]
