# Generated by Django 5.2.7 on 2026-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0039_userexportshopproductpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexportshopproductpreference',
            name='shop_name',
            field=models.CharField(default='', max_length=255, verbose_name='汇出店铺名（缓存）'),
        ),
    ]
