# Generated by Django 5.2.7 on 2026-04-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divi', '0005_diviexporttemplate_template_type_and_more'),
        ('general', '0033_alter_amazonshop_shop_status'),
        ('task', '0040_userexportshopproductpreference_shop_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexportshopproductpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userexportshopproductpreference',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divi.diviexporttemplate', verbose_name='汇出模板'),
        ),
        migrations.AlterField(
            model_name='userexportshopproductpreference',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='divi.product', verbose_name='产品'),
        ),
        migrations.AlterUniqueTogether(
            name='userexportshopproductpreference',
            unique_together={('user', 'shop', 'product', 'template')},
        ),
    ]
