# Generated by Django 5.2.7 on 2026-04-14 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divi', '0005_diviexporttemplate_template_type_and_more'),
        ('general', '0033_alter_amazonshop_shop_status'),
        ('task', '0041_alter_userexportshopproductpreference_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexportshopproductpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userexportshopproductpreference',
            name='diwei_account',
            field=models.CharField(default='', max_length=100, verbose_name='迪唯账号'),
        ),
        migrations.AlterUniqueTogether(
            name='userexportshopproductpreference',
            unique_together={('user', 'diwei_account', 'shop', 'product', 'template')},
        ),
    ]
