# Generated by Django 5.2.7 on 2026-04-20 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0035_add_approval_flow_config'),
        ('task', '0042_alter_userexportshopproductpreference_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('amazon_ad', 'Amazon开广告')], db_comment='审批业务类型', default='amazon_ad', max_length=30, verbose_name='审批类型')),
                ('skip_approval', models.BooleanField(db_comment='为 True 时该员工提交此类型审批直接通过，不经过任何人', default=False, verbose_name='跳过审批')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(db_comment='该配置适用的员工', on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow_configs', to=settings.AUTH_USER_MODEL, verbose_name='被配置员工')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('proxy_approver', models.ForeignKey(blank=True, db_comment='代替组长审批该员工审批单的人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_approval_configs', to=settings.AUTH_USER_MODEL, verbose_name='代理审批人')),
            ],
            options={
                'verbose_name': '审批流程配置',
                'verbose_name_plural': '审批流程配置列表',
                'db_table': 'approval_flow_configs',
                'indexes': [models.Index(fields=['company', 'applicant'], name='idx_flowcfg_company_applicant'), models.Index(fields=['company', 'approval_type'], name='idx_flowcfg_company_type')],
                'unique_together': {('company', 'applicant', 'approval_type')},
            },
        ),
    ]
