# Generated by Django 5.2.7 on 2026-04-20 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0043_add_approval_flow_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflowconfig',
            name='step2_approver',
            field=models.ForeignKey(blank=True, db_comment='代替主管审批该员工审批单的人（step2，可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step2_approval_configs', to=settings.AUTH_USER_MODEL, verbose_name='二级审批人'),
        ),
        migrations.AlterField(
            model_name='approvalflowconfig',
            name='proxy_approver',
            field=models.ForeignKey(blank=True, db_comment='代替组长审批该员工审批单的人（step1）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_approval_configs', to=settings.AUTH_USER_MODEL, verbose_name='一级审批人'),
        ),
    ]
