# Generated by Django 5.2.7 on 2026-04-28 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0017_amazonmskudailyprofit_amazonmskudailyprofitasin_and_more'),
        ('general', '0038_alter_amazonshop_registered_phone_comment'),
        ('task', '0044_add_step2_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(choices=[('amazon_ad', 'Amazon开广告'), ('fba_shipment', 'FBA发仓审批')], db_comment='审批业务类型', default='amazon_ad', max_length=30, verbose_name='审批类型'),
        ),
        migrations.AlterField(
            model_name='approvalflowconfig',
            name='approval_type',
            field=models.CharField(choices=[('amazon_ad', 'Amazon开广告'), ('fba_shipment', 'FBA发仓审批')], db_comment='审批业务类型', default='amazon_ad', max_length=30, verbose_name='审批类型'),
        ),
        migrations.CreateModel(
            name='FbaShipmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approval', models.OneToOneField(db_comment='对应的审批主表', on_delete=django.db.models.deletion.CASCADE, related_name='fba_shipment_detail', to='task.approval', verbose_name='关联审批单')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': 'FBA发仓审批详情',
                'verbose_name_plural': 'FBA发仓审批详情列表',
                'db_table': 'approval_fba_shipment',
            },
        ),
        migrations.CreateModel(
            name='FbaShipmentShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_status', models.CharField(choices=[('waiting', '待执行'), ('executing', '执行中'), ('success', '执行成功'), ('failed', '执行失败')], db_comment='RPA执行状态', default='waiting', max_length=20, verbose_name='执行状态')),
                ('exec_result', models.JSONField(blank=True, db_comment='RPA返回结果', default=dict, verbose_name='执行结果')),
                ('webhook_task_id', models.CharField(blank=True, db_comment='用于匹配Webhook回调', max_length=100, verbose_name='RPA任务ID')),
                ('sequence', models.IntegerField(db_comment='组间执行顺序', default=0, verbose_name='执行顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('fba_shipment', models.ForeignKey(db_comment='关联的FBA发仓审批', on_delete=django.db.models.deletion.CASCADE, related_name='shop_configs', to='task.fbashipmentapproval', verbose_name='所属审批')),
                ('lingxing_shop', models.ForeignKey(db_comment='FBA发仓的店铺', on_delete=django.db.models.deletion.CASCADE, to='amazon.lingxingamazonshop', verbose_name='领星店铺')),
            ],
            options={
                'verbose_name': 'FBA发仓店铺配置',
                'verbose_name_plural': 'FBA发仓店铺配置列表',
                'db_table': 'approval_fba_shipment_shop_config',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FbaShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_comment='每个ASIN的发仓数量，必须为正整数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='发仓数量')),
                ('sequence', models.IntegerField(db_comment='ASIN在配置组内的展示顺序', default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(db_comment='数据隔离边界', on_delete=django.db.models.deletion.CASCADE, to='general.company', verbose_name='所属公司')),
                ('listing', models.ForeignKey(db_comment='需要发仓的ASIN记录', on_delete=django.db.models.deletion.CASCADE, related_name='fba_shipment_items', to='amazon.amazonlistingv2', verbose_name='ASIN记录')),
                ('shop_config', models.ForeignKey(db_comment='关联的FBA发仓店铺配置', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='task.fbashipmentshopconfig', verbose_name='所属配置组')),
            ],
            options={
                'verbose_name': 'FBA发仓ASIN明细',
                'verbose_name_plural': 'FBA发仓ASIN明细列表',
                'db_table': 'approval_fba_shipment_item',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fbashipmentshopconfig',
            index=models.Index(fields=['company', 'fba_shipment'], name='idx_fbashop_company_ship'),
        ),
        migrations.AddIndex(
            model_name='fbashipmentshopconfig',
            index=models.Index(fields=['company', 'exec_status'], name='idx_fbashop_company_exec'),
        ),
        migrations.AddIndex(
            model_name='fbashipmentshopconfig',
            index=models.Index(fields=['lingxing_shop'], name='idx_fbashop_shop'),
        ),
        migrations.AddIndex(
            model_name='fbashipmentshopconfig',
            index=models.Index(fields=['webhook_task_id'], name='idx_fbashop_webhook'),
        ),
        migrations.AddIndex(
            model_name='fbashipmentitem',
            index=models.Index(fields=['company', 'shop_config'], name='idx_fbaitem_company_config'),
        ),
        migrations.AddIndex(
            model_name='fbashipmentitem',
            index=models.Index(fields=['shop_config'], name='idx_fbaitem_shop_config'),
        ),
        migrations.AddIndex(
            model_name='fbashipmentitem',
            index=models.Index(fields=['listing'], name='idx_fbaitem_listing'),
        ),
        migrations.AddConstraint(
            model_name='fbashipmentitem',
            constraint=models.UniqueConstraint(fields=('shop_config', 'listing'), name='uniq_fbaitem_config_listing'),
        ),
        migrations.AddConstraint(
            model_name='fbashipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='chk_fbaitem_qty_positive'),
        ),
    ]
