# Generated by Django 5.2.7 on 2026-04-30 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0045_alter_approval_approval_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingOptimizationJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('original_file_path', models.CharField(max_length=500, verbose_name='原始文件路径')),
                ('output_file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='输出文件路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '优化中'), ('completed', '已完成'), ('failed', '有失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('optimized_rows', models.IntegerField(default=0, verbose_name='已优化行数')),
                ('failed_rows', models.IntegerField(default=0, verbose_name='失败行数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_optimization_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Listing优化任务',
                'verbose_name_plural': 'Listing优化任务',
                'db_table': 'task_listing_optimization_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingOptimizationRow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('row_number', models.IntegerField(verbose_name='Excel行号')),
                ('status', models.CharField(choices=[('pending', '待优化'), ('processing', '优化中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('source_data', models.JSONField(default=dict, verbose_name='原始数据')),
                ('optimized_data', models.JSONField(blank=True, default=dict, verbose_name='优化后数据')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='task.listingoptimizationjob', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'Listing优化行',
                'verbose_name_plural': 'Listing优化行',
                'db_table': 'task_listing_optimization_rows',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='listingoptimizationjob',
            index=models.Index(fields=['created_by', 'created_at'], name='idx_listing_job_user_created'),
        ),
        migrations.AddIndex(
            model_name='listingoptimizationjob',
            index=models.Index(fields=['status', 'created_at'], name='idx_listing_job_status_created'),
        ),
        migrations.AddIndex(
            model_name='listingoptimizationrow',
            index=models.Index(fields=['job', 'status'], name='idx_listing_row_job_status'),
        ),
        migrations.AddIndex(
            model_name='listingoptimizationrow',
            index=models.Index(fields=['job', 'row_number'], name='idx_listing_row_job_number'),
        ),
        migrations.AlterUniqueTogether(
            name='listingoptimizationrow',
            unique_together={('job', 'row_number')},
        ),
    ]
