# Generated by Django 5.2.7 on 2026-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0046_listingoptimizationjob_listingoptimizationrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoptimizationjob',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '优化中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '有失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
