# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0047_alter_listingoptimizationjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingoptimizationjob',
            name='ai_model',
            field=models.CharField(default='qwen-flash', max_length=120, verbose_name='AI模型'),
        ),
        migrations.AddField(
            model_name='listingoptimizationjob',
            name='prompt_profile',
            field=models.CharField(default='amazon_grammar_tyrant', max_length=80, verbose_name='提示词方案'),
        ),
    ]
