# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0048_listingoptimizationjob_ai_model_and_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingoptimizationjob',
            name='enable_infringement_check',
            field=models.BooleanField(default=False, verbose_name='是否侵权检测'),
        ),
        migrations.AddField(
            model_name='listingoptimizationjob',
            name='infringement_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='侵权检测时间'),
        ),
        migrations.AddField(
            model_name='listingoptimizationjob',
            name='infringement_error_message',
            field=models.TextField(blank=True, default='', verbose_name='侵权检测错误信息'),
        ),
        migrations.AddField(
            model_name='listingoptimizationjob',
            name='infringement_status',
            field=models.CharField(
                choices=[
                    ('none', '未检测'),
                    ('pending', '待检测'),
                    ('checking', '检测中'),
                    ('completed', '已检测'),
                    ('failed', '检测失败'),
                ],
                default='none',
                max_length=20,
                verbose_name='侵权检测状态',
            ),
        ),
        migrations.AddField(
            model_name='listingoptimizationrow',
            name='infringement_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='侵权检测数据'),
        ),
        migrations.AddField(
            model_name='listingoptimizationrow',
            name='infringement_error_message',
            field=models.TextField(blank=True, default='', verbose_name='侵权检测错误信息'),
        ),
    ]
