# Generated by Django 5.2.7 on 2025-11-18 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('General', '0005_operationalaccount_ops_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LingXingAmazonShop',
            fields=[
                ('sid', models.BigIntegerField(db_comment='领星店铺 sid（主键）', primary_key=True, serialize=False)),
                ('mid', models.IntegerField(db_comment='领星店铺 mid（账号内唯一）')),
                ('name', models.CharField(blank=True, db_comment='领星店铺名称（例如：黄志雄-19高强-US）', max_length=150, null=True)),
                ('seller_id', models.CharField(blank=True, db_comment='领星 seller_id', max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, db_comment='领星账号名称（例如：黄志雄-19高强）', max_length=100, null=True)),
                ('seller_account_id', models.BigIntegerField(blank=True, db_comment='领星 seller_account_id', null=True)),
                ('region', models.CharField(blank=True, db_comment='区域（如 NA/EU）', max_length=20, null=True)),
                ('country', models.CharField(blank=True, db_comment='国家（如 美国/加拿大）', max_length=50, null=True)),
                ('marketplace_id', models.CharField(blank=True, db_comment='亚马逊 marketplace_id（如 ATVPDKIKX0DER）', max_length=50, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_comment='领星店铺状态（1=正常等）', null=True)),
                ('has_ads_setting', models.SmallIntegerField(blank=True, db_comment='是否有广告配置（0/1）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间（插入本地记录时间）')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间（最后同步时间）')),
                ('amazon_shop', models.ForeignKey(blank=True, db_comment='绑定的本地亚马逊店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lingxing_amazon_shops', to='General.amazonshop')),
            ],
            options={
                'verbose_name': '领星亚马逊店铺',
                'verbose_name_plural': '领星亚马逊店铺',
                'db_table': 'lingxing_amazon_shop',
                'db_table_comment': '领星-亚马逊店铺信息表',
                'constraints': [models.UniqueConstraint(fields=('seller_account_id', 'mid'), name='uniq_lingxing_seller_mid')],
            },
        ),
    ]
