# Generated by Django 5.2.7 on 2025-11-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0007_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrders',
            fields=[
                ('id', models.BigAutoField(db_comment='自增主键', primary_key=True, serialize=False)),
                ('amazon_order_id', models.CharField(db_comment='亚马逊订单ID', db_index=True, max_length=50)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_total_currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fulfillment_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_return', models.SmallIntegerField(default=0)),
                ('is_mcf_order', models.SmallIntegerField(default=0)),
                ('is_assessed', models.SmallIntegerField(default=0)),
                ('is_replaced_order', models.SmallIntegerField(default=0)),
                ('is_replacement_order', models.SmallIntegerField(default=0)),
                ('is_return_order', models.SmallIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_date_local', models.DateTimeField(blank=True, null=True)),
                ('purchase_date_utc', models.DateTimeField(blank=True, null=True)),
                ('shipment_date_local', models.DateTimeField(blank=True, null=True)),
                ('shipment_date_utc', models.DateTimeField(blank=True, null=True)),
                ('last_update_date_local', models.DateTimeField(blank=True, null=True)),
                ('last_update_date_utc', models.DateTimeField(blank=True, null=True)),
                ('gmt_modified', models.DateTimeField(blank=True, null=True)),
                ('gmt_modified_utc', models.DateTimeField(blank=True, null=True)),
                ('hide_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('amazon_shop', models.ForeignKey(blank=True, db_comment='关联的本地亚马逊店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_orders', to='general.amazonshop')),
            ],
            options={
                'db_table': 'amazon_orders',
                'db_table_comment': '亚马逊订单主表',
            },
        ),
        migrations.CreateModel(
            name='AmazonOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=30)),
                ('seller_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('local_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('local_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('order', models.ForeignKey(db_comment='关联的订单', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amazon.amazonorders')),
            ],
            options={
                'db_table': 'amazon_order_item',
                'db_table_comment': '亚马逊订单商品明细',
            },
        ),
        migrations.CreateModel(
            name='LingXingAmazonShop',
            fields=[
                ('sid', models.BigIntegerField(db_comment='领星店铺 sid（主键）', primary_key=True, serialize=False)),
                ('mid', models.IntegerField(db_comment='领星店铺 mid（账号内唯一）')),
                ('name', models.CharField(blank=True, db_comment='领星店铺名称（例如：黄志雄-19高强-US）', max_length=150, null=True)),
                ('seller_id', models.CharField(blank=True, db_comment='领星 seller_id', max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, db_comment='领星账号名称（例如：黄志雄-19高强）', max_length=100, null=True)),
                ('seller_account_id', models.BigIntegerField(blank=True, db_comment='领星 seller_account_id', null=True)),
                ('region', models.CharField(blank=True, db_comment='区域（如 NA/EU）', max_length=20, null=True)),
                ('country', models.CharField(blank=True, db_comment='国家（如 美国/加拿大）', max_length=50, null=True)),
                ('marketplace_id', models.CharField(blank=True, db_comment='亚马逊 marketplace_id（如 ATVPDKIKX0DER）', max_length=50, null=True)),
                ('status', models.SmallIntegerField(blank=True, db_comment='领星店铺状态（1=正常等）', null=True)),
                ('has_ads_setting', models.SmallIntegerField(blank=True, db_comment='是否有广告配置（0/1）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间（插入本地记录时间）')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间（最后同步时间）')),
                ('amazon_shop', models.ForeignKey(blank=True, db_comment='绑定的本地亚马逊店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lingxing_amazon_shops', to='general.amazonshop')),
            ],
            options={
                'verbose_name': '领星亚马逊店铺',
                'verbose_name_plural': '领星亚马逊店铺',
                'db_table': 'lingxing_amazon_shop',
                'db_table_comment': '领星-亚马逊店铺信息表',
            },
        ),
        migrations.AddField(
            model_name='amazonorders',
            name='lingxing_shop',
            field=models.ForeignKey(blank=True, db_comment='关联的领星店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_orders', to='amazon.lingxingamazonshop'),
        ),
        migrations.AddConstraint(
            model_name='lingxingamazonshop',
            constraint=models.UniqueConstraint(fields=('seller_account_id', 'mid'), name='uniq_lingxing_seller_mid'),
        ),
        migrations.AddConstraint(
            model_name='amazonorders',
            constraint=models.UniqueConstraint(fields=('lingxing_shop', 'amazon_order_id'), name='uniq_lingxing_shop_order_id'),
        ),
    ]
