# Generated by Django 5.2.7 on 2025-11-18 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
        ('General', '0005_operationalaccount_ops_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrders',
            fields=[
                ('amazon_order_id', models.CharField(db_comment='亚马逊订单ID', max_length=50, primary_key=True, serialize=False)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_total_currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fulfillment_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_return', models.SmallIntegerField(default=0)),
                ('is_mcf_order', models.SmallIntegerField(default=0)),
                ('is_assessed', models.SmallIntegerField(default=0)),
                ('is_replaced_order', models.SmallIntegerField(default=0)),
                ('is_replacement_order', models.SmallIntegerField(default=0)),
                ('is_return_order', models.SmallIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_date_local', models.DateTimeField(blank=True, null=True)),
                ('purchase_date_utc', models.DateTimeField(blank=True, null=True)),
                ('shipment_date_local', models.DateTimeField(blank=True, null=True)),
                ('shipment_date_utc', models.DateTimeField(blank=True, null=True)),
                ('last_update_date_local', models.DateTimeField(blank=True, null=True)),
                ('last_update_date_utc', models.DateTimeField(blank=True, null=True)),
                ('gmt_modified', models.DateTimeField(blank=True, null=True)),
                ('gmt_modified_utc', models.DateTimeField(blank=True, null=True)),
                ('hide_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('amazon_shop', models.ForeignKey(blank=True, db_comment='关联的本地亚马逊店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_orders', to='General.amazonshop')),
                ('lingxing_shop', models.ForeignKey(blank=True, db_comment='关联的领星店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_orders', to='Amazon.lingxingamazonshop')),
            ],
            options={
                'db_table': 'amazon_orders',
                'db_table_comment': '亚马逊订单主表',
            },
        ),
        migrations.CreateModel(
            name='AmazonOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=30)),
                ('seller_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('local_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('local_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('order', models.ForeignKey(db_comment='关联的订单', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Amazon.amazonorders')),
            ],
            options={
                'db_table': 'amazon_order_item',
                'db_table_comment': '亚马逊订单商品明细',
            },
        ),
    ]
