# Generated by Django 5.2.7 on 2025-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='is_exported_to_divi',
            field=models.BooleanField(default=False, help_text='勾选表示该订单已同步至DIVI系统', verbose_name='是否已导出DIVI'),
        ),
    ]
