# Generated by Django 5.2.7 on 2026-01-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='amazon_shop',
            field=models.ForeignKey(blank=True, db_comment='关联的本地亚马逊店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_orders', to='general.amazonshop'),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='order',
            field=models.ForeignKey(db_comment='关联的订单', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amazon.amazonorders'),
        ),
        migrations.AddField(
            model_name='amazonorderitemfulldetail',
            name='order',
            field=models.ForeignKey(db_comment='关联的亚马逊订单', on_delete=django.db.models.deletion.CASCADE, related_name='item_full_details', to='amazon.amazonorders', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='amazonperformancenotification',
            name='shop',
            field=models.ForeignKey(db_comment='关联的亚马逊店铺', on_delete=django.db.models.deletion.CASCADE, related_name='performance_notifications', to='general.amazonshop'),
        ),
        migrations.AddField(
            model_name='amazonshopdailycheck',
            name='shop',
            field=models.ForeignKey(db_comment='关联的亚马逊店铺', on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to='general.amazonshop'),
        ),
        migrations.AddField(
            model_name='amazonshopemail',
            name='shop',
            field=models.ForeignKey(db_comment='关联的亚马逊店铺', on_delete=django.db.models.deletion.CASCADE, related_name='shop_emails', to='general.amazonshop'),
        ),
        migrations.AddField(
            model_name='lingxingamazonshop',
            name='amazon_shop',
            field=models.ForeignKey(blank=True, db_comment='绑定的本地亚马逊店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lingxing_amazon_shops', to='general.amazonshop'),
        ),
        migrations.AddField(
            model_name='amazonorders',
            name='lingxing_shop',
            field=models.ForeignKey(blank=True, db_comment='关联的领星店铺', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazon_orders', to='amazon.lingxingamazonshop'),
        ),
        migrations.AlterUniqueTogether(
            name='amazonorderitem',
            unique_together={('order', 'seller_sku')},
        ),
        migrations.AlterUniqueTogether(
            name='amazonorderitemfulldetail',
            unique_together={('order', 'order_item_id')},
        ),
        migrations.AddIndex(
            model_name='amazonperformancenotification',
            index=models.Index(fields=['shop', 'date'], name='idx_shop_date'),
        ),
        migrations.AddIndex(
            model_name='amazonperformancenotification',
            index=models.Index(fields=['needs_attention'], name='idx_needs_attention'),
        ),
        migrations.AddIndex(
            model_name='amazonperformancenotification',
            index=models.Index(fields=['is_processed'], name='idx_is_processed'),
        ),
        migrations.AddConstraint(
            model_name='amazonperformancenotification',
            constraint=models.UniqueConstraint(fields=('shop', 'subject', 'date'), name='uniq_shop_subject_date'),
        ),
        migrations.AddIndex(
            model_name='amazonshopdailycheck',
            index=models.Index(fields=['shop', 'check_date'], name='idx_check_shop_date'),
        ),
        migrations.AddIndex(
            model_name='amazonshopdailycheck',
            index=models.Index(fields=['check_date'], name='idx_check_date'),
        ),
        migrations.AddIndex(
            model_name='amazonshopdailycheck',
            index=models.Index(fields=['visited'], name='idx_check_visited'),
        ),
        migrations.AddIndex(
            model_name='amazonshopdailycheck',
            index=models.Index(fields=['performance_checked'], name='idx_check_performance'),
        ),
        migrations.AddIndex(
            model_name='amazonshopdailycheck',
            index=models.Index(fields=['withdrawal_processed'], name='idx_check_withdrawal'),
        ),
        migrations.AddConstraint(
            model_name='amazonshopdailycheck',
            constraint=models.UniqueConstraint(fields=('shop', 'check_date'), name='uniq_shop_daily_check'),
        ),
        migrations.AddConstraint(
            model_name='lingxingamazonshop',
            constraint=models.UniqueConstraint(fields=('seller_account_id', 'mid'), name='uniq_lingxing_seller_mid'),
        ),
        migrations.AddConstraint(
            model_name='amazonorders',
            constraint=models.UniqueConstraint(fields=('lingxing_shop', 'amazon_order_id'), name='uniq_lingxing_shop_order_id'),
        ),
    ]
