# Generated by Django 5.2.7 on 2026-02-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255, verbose_name='关键词/短语')),
                ('category', models.CharField(choices=[('account_ban', '账户停用/冻结'), ('performance', '绩效/政策警告'), ('funds', '资金/提现异常'), ('listing', 'Listing下架/违规'), ('verification', '审核/验证通知'), ('tro', 'TRO/法律诉讼'), ('inventory', '库存/物流异常'), ('other', '其他')], default='other', max_length=50, verbose_name='风险分类')),
                ('match_type', models.CharField(choices=[('whole', '整词匹配'), ('contains', '包含匹配'), ('regex', '正则表达式'), ('start', '开头匹配')], default='whole', max_length=20, verbose_name='匹配方式')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='数值越大越优先，用于排序和显示', verbose_name='优先级')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='规则说明')),
                ('example_text', models.CharField(blank=True, help_text='该关键词通常出现的标题/内容示例，供参考', max_length=500, verbose_name='示例文本')),
                ('apply_to', models.CharField(choices=[('all', '全部'), ('email', '仅邮件'), ('performance', '仅绩效通知')], default='all', max_length=20, verbose_name='适用范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '风险关键词',
                'verbose_name_plural': '风险关键词',
                'db_table': 'amazon_risk_keywords',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='amazonperformancenotification',
            name='matched_keywords',
            field=models.ManyToManyField(blank=True, db_table='amazon_performance_risk_matches', to='amazon.riskkeyword', verbose_name='命中的风险关键词'),
        ),
        migrations.AddField(
            model_name='amazonshopemail',
            name='matched_keywords',
            field=models.ManyToManyField(blank=True, db_table='amazon_email_risk_matches', to='amazon.riskkeyword', verbose_name='命中的风险关键词'),
        ),
    ]
