# Generated by Django 5.2.7 on 2026-02-07 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_riskkeyword_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskkeyword',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risk_keywords', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
