# Generated by Django 5.2.7 on 2025-11-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_amazonorderitem_divi_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='order_no',
            field=models.CharField(blank=True, db_comment='领星订单号', db_index=True, max_length=50),
        ),
    ]
