# Generated by Django 5.2.7 on 2026-02-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_riskkeyword_created_by'),
        ('theme', '0015_alter_trotable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskkeyword',
            name='category',
            field=models.CharField(choices=[('account_ban', '账户停用/冻结'), ('performance', '绩效/政策警告'), ('funds', '资金/提现异常'), ('listing', 'Listing下架/违规'), ('verification', '审核/验证通知'), ('tro', 'TRO/法律诉讼'), ('inventory', '库存/物流异常'), ('official', '官方通知'), ('other', '其他')], default='other', max_length=50, verbose_name='风险分类'),
        ),
        migrations.CreateModel(
            name='AmazonListing',
            fields=[
                ('id', models.BigAutoField(db_comment='自增主键', primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_comment='亚马逊商品编码', db_index=True, max_length=10, verbose_name='ASIN')),
                ('title', models.CharField(blank=True, db_comment='Listing标题', max_length=500, null=True, verbose_name='标题')),
                ('is_active', models.BooleanField(db_comment='Listing是否处于在售状态', default=True, verbose_name='是否在售')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lingxing_shop', models.ForeignKey(db_comment='绑定的领星站点店铺', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='amazon.lingxingamazonshop', verbose_name='所属领星店铺')),
                ('trademarks', models.ManyToManyField(blank=True, related_name='listings', to='theme.trademarkinfo', verbose_name='命中商标')),
                ('tro_words', models.ManyToManyField(blank=True, related_name='listings', to='theme.trotable', verbose_name='命中侵权词')),
            ],
            options={
                'verbose_name': 'Amazon Listing',
                'verbose_name_plural': 'Amazon Listings',
                'db_table': 'amazon_listing',
                'db_table_comment': 'Listing主表（店铺+ASIN唯一）',
                'indexes': [models.Index(fields=['asin'], name='idx_listing_asin'), models.Index(fields=['is_active'], name='idx_listing_active'), models.Index(fields=['created_at'], name='idx_listing_created')],
                'constraints': [models.UniqueConstraint(fields=('lingxing_shop', 'asin'), name='uniq_lingxing_shop_asin')],
            },
        ),
    ]
