# Generated by Django 5.2.7 on 2025-11-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0004_amazonorders_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='divi_shipping_amount',
            field=models.DecimalField(blank=True, db_comment='运费金额', decimal_places=2, max_digits=10, null=True),
        ),
    ]
