# Generated by Django 5.2.7 on 2025-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_amazonorders_divi_shipping_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='divi_goods_payment_total',
            field=models.DecimalField(blank=True, db_comment='货款总计', decimal_places=2, max_digits=10, null=True),
        ),
    ]
