# Generated by Django 5.2.7 on 2026-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_alter_riskkeyword_category_amazonlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='lingxingamazonshop',
            name='profile_id',
            field=models.BigIntegerField(blank=True, db_comment='领星API返回的profile_id（与sid一一对应，用于数据校验）用于广告', db_index=True, null=True, verbose_name='领星ProfileID'),
        ),
    ]
