# Generated by Django 5.2.7 on 2025-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_amazonorders_divi_goods_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='masked_single',
            field=models.BooleanField(db_comment='是否假面单', default=False, verbose_name='假发货'),
        ),
    ]
