# Generated by Django 5.2.7 on 2026-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_lingxingamazonshop_profile_id'),
        ('theme', '0015_alter_trotable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlisting',
            name='risk_level',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_comment='主题风险等级', default='unknown', max_length=10, verbose_name='主题风险等级'),
        ),
        migrations.AddIndex(
            model_name='amazonlisting',
            index=models.Index(fields=['risk_level'], name='idx_listing_risk'),
        ),
    ]
