# Generated by Django 5.2.7 on 2026-03-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_amazonlisting_risk_level_and_more'),
        ('general', '0025_alter_useroperationlog_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonShopUploadRecord',
            fields=[
                ('batch_id', models.CharField(db_comment='批次编号（主键）', max_length=20, primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_comment='上传的文件名', max_length=255)),
                ('status', models.CharField(choices=[('processing', '进行中'), ('completed', '完成'), ('needs_action', '需操作'), ('draft', '已保存为草稿'), ('published', '已发布'), ('failed', '失败')], db_comment='上货状态', default='processing', max_length=20)),
                ('upload_time', models.DateTimeField(db_comment='上传时间（年月日时分）')),
                ('shop', models.ForeignKey(db_comment='关联的亚马逊店铺', on_delete=django.db.models.deletion.CASCADE, related_name='upload_records', to='general.amazonshop')),
            ],
            options={
                'verbose_name': '店铺上货记录',
                'verbose_name_plural': '店铺上货记录',
                'db_table': 'amazon_shop_upload_record',
                'db_table_comment': '亚马逊店铺上货记录表',
                'indexes': [models.Index(fields=['shop', 'upload_time'], name='idx_upload_shop_time'), models.Index(fields=['status'], name='idx_upload_status'), models.Index(fields=['upload_time'], name='idx_upload_time')],
            },
        ),
    ]
