# Generated by Django 5.2.7 on 2025-11-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_amazonorders_masked_single'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonorderitem',
            unique_together={('order', 'seller_sku')},
        ),
    ]
