# Generated by Django 5.2.7 on 2026-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_amazonshopuploadrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshopuploadrecord',
            name='sku_success',
            field=models.IntegerField(blank=True, db_comment='SKU成功数量', null=True),
        ),
        migrations.AddField(
            model_name='amazonshopuploadrecord',
            name='submitted',
            field=models.IntegerField(blank=True, db_comment='已提交数量', null=True),
        ),
    ]
