# Generated by Django 5.2.7 on 2025-12-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_amazonorderitem_unique_together'),
        ('general', '0013_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonPerformanceNotification',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_comment='通知主题', max_length=250)),
                ('date', models.DateField(db_comment='通知日期')),
                ('needs_attention', models.SmallIntegerField(db_comment='是否需要注意（0=否，1=是）', default=0, verbose_name='需要注意')),
                ('is_processed', models.SmallIntegerField(db_comment='是否已处理（0=否，1=是）', default=0, verbose_name='已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('shop', models.ForeignKey(db_comment='关联的亚马逊店铺', on_delete=django.db.models.deletion.CASCADE, related_name='performance_notifications', to='general.amazonshop')),
            ],
            options={
                'verbose_name': '亚马逊绩效通知',
                'verbose_name_plural': '亚马逊绩效通知',
                'db_table': 'amazon_performance_notification',
                'db_table_comment': '亚马逊绩效通知表',
                'indexes': [models.Index(fields=['shop', 'date'], name='idx_shop_date'), models.Index(fields=['needs_attention'], name='idx_needs_attention'), models.Index(fields=['is_processed'], name='idx_is_processed')],
            },
        ),
    ]
