# Generated by Django 5.2.7 on 2025-12-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0009_amazonperformancenotification'),
        ('General', '0014_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amazonperformancenotification',
            constraint=models.UniqueConstraint(fields=('shop', 'subject', 'date'), name='uniq_shop_subject_date'),
        ),
    ]
