# Generated by Django 5.2.7 on 2026-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_amazonshopuploadrecord_sku_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshopdailycheck',
            name='is_restricted',
            field=models.BooleanField(blank=True, db_comment='是否受限', default=False, null=True),
        ),
        migrations.AddField(
            model_name='amazonshopdailycheck',
            name='restricted_regions',
            field=models.JSONField(blank=True, db_comment='受限地区列表，如["加拿大", "美国", "墨西哥"]', default=list, null=True),
        ),
    ]
