# Generated by Django 5.2.7 on 2025-12-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0010_amazonperformancenotification_uniq_shop_subject_date'),
        ('General', '0015_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonShopDailyCheck',
            fields=[
                ('id', models.BigAutoField(db_comment='主键', primary_key=True, serialize=False)),
                ('check_date', models.DateField(db_comment='巡店日期')),
                ('visited', models.BooleanField(db_comment='是否进入店铺', default=False)),
                ('performance_checked', models.BooleanField(db_comment='是否进行绩效通知检查', default=False)),
                ('withdrawal_processed', models.BooleanField(db_comment='是否进行提现操作', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间')),
                ('shop', models.ForeignKey(db_comment='关联的亚马逊店铺', on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to='General.amazonshop')),
            ],
            options={
                'verbose_name': '亚马逊巡店日报',
                'verbose_name_plural': '亚马逊巡店日报',
                'db_table': 'amazon_shop_daily_check',
                'db_table_comment': '亚马逊巡店日报表',
                'indexes': [models.Index(fields=['shop', 'check_date'], name='idx_check_shop_date'), models.Index(fields=['check_date'], name='idx_check_date'), models.Index(fields=['visited'], name='idx_check_visited'), models.Index(fields=['performance_checked'], name='idx_check_performance'), models.Index(fields=['withdrawal_processed'], name='idx_check_withdrawal')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'check_date'), name='uniq_shop_daily_check')],
            },
        ),
    ]
