# Generated by Django 5.2.7 on 2026-04-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_amazonshopuploadrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlisting',
            name='amount_14d',
            field=models.DecimalField(blank=True, db_comment='14天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-14天'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='amount_1d',
            field=models.DecimalField(blank=True, db_comment='昨天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-昨天'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='amount_30d',
            field=models.DecimalField(blank=True, db_comment='30天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-30天'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='amount_7d',
            field=models.DecimalField(blank=True, db_comment='7天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-7天'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='avg_volume_14d',
            field=models.IntegerField(blank=True, db_comment='14日日均销量', null=True, verbose_name='日均销量-14日'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='avg_volume_30d',
            field=models.IntegerField(blank=True, db_comment='30日日均销量', null=True, verbose_name='日均销量-30日'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='avg_volume_7d',
            field=models.IntegerField(blank=True, db_comment='7日日均销量', null=True, verbose_name='日均销量-7日'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='seller_category_new',
            field=models.JSONField(blank=True, db_comment='排名所属的类别列表，如["Beauty & Personal Care"]', default=list, null=True, verbose_name='排名所属类别'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='seller_rank',
            field=models.IntegerField(blank=True, db_comment='销售排名', null=True, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='seller_sku',
            field=models.CharField(blank=True, db_comment='卖家SKU（MSKU）', max_length=100, null=True, verbose_name='MSKU'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='small_image_url',
            field=models.URLField(blank=True, db_comment='商品缩略图URL', max_length=500, null=True, verbose_name='商品缩略图地址'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='volume_14d',
            field=models.IntegerField(blank=True, db_comment='14天销量', null=True, verbose_name='销量-14天'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='volume_1d',
            field=models.IntegerField(blank=True, db_comment='昨天销量', null=True, verbose_name='销量-昨天'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='volume_30d',
            field=models.IntegerField(blank=True, db_comment='30天销量', null=True, verbose_name='销量-30天'),
        ),
        migrations.AddField(
            model_name='amazonlisting',
            name='volume_7d',
            field=models.IntegerField(blank=True, db_comment='7天销量', null=True, verbose_name='销量-7天'),
        ),
    ]
