# Generated by Django 5.2.7 on 2025-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_amazonshopdailycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='earliest_ship_date_local',
            field=models.DateTimeField(blank=True, db_comment='最晚发货时间（本地时间）', null=True),
        ),
        migrations.AddField(
            model_name='amazonorders',
            name='earliest_ship_date_utc',
            field=models.DateTimeField(blank=True, db_comment='最晚发货时间（UTC）', null=True),
        ),
    ]
