# Generated by Django 5.2.7 on 2025-12-20 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0012_amazonorders_earliest_ship_date_local_and_more'),
        ('General', '0026_alter_announcement_valid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonShopEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('subject', models.CharField(max_length=500, verbose_name='邮件标题')),
                ('sender', models.CharField(max_length=255, verbose_name='发件人')),
                ('receive_time', models.DateTimeField(verbose_name='接收时间')),
                ('is_attention_needed', models.BooleanField(default=False, verbose_name='是否需要注意')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(db_comment='关联的亚马逊店铺', on_delete=django.db.models.deletion.CASCADE, related_name='shop_emails', to='General.amazonshop')),
            ],
            options={
                'verbose_name': '店铺邮件',
                'verbose_name_plural': '店铺邮件',
                'db_table': 'amazon_shop_emails',
            },
        ),
    ]
