# Generated by Django 5.2.7 on 2026-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_amazonlistinglegacy_amazonlistingv2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshopuploadrecord',
            name='status',
            field=models.CharField(choices=[('queued', '队列中'), ('processing', '进行中'), ('completed', '完成'), ('needs_action', '需操作'), ('draft', '已保存为草稿'), ('published', '已发布'), ('failed', '失败'), ('cancelled', '已取消')], db_comment='上货状态', default='processing', max_length=20),
        ),
    ]
