# Generated by Django 5.2.7 on 2025-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0013_amazonshopemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshopdailycheck',
            name='last_restock_date',
            field=models.DateField(blank=True, db_comment='最后上货日期', null=True),
        ),
        migrations.AddField(
            model_name='amazonshopdailycheck',
            name='shop_status',
            field=models.CharField(blank=True, db_comment='店铺状况', default='', max_length=100),
        ),
    ]
