# Generated by Django 5.2.7 on 2026-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_alter_amazonshopuploadrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_amount_14d',
            field=models.DecimalField(blank=True, db_comment='14天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-14天'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_amount_1d',
            field=models.DecimalField(blank=True, db_comment='昨天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-昨天'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_amount_30d',
            field=models.DecimalField(blank=True, db_comment='30天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-30天'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_amount_7d',
            field=models.DecimalField(blank=True, db_comment='7天销售额', decimal_places=2, max_digits=12, null=True, verbose_name='销售额-7天'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_avg_volume_14d',
            field=models.DecimalField(blank=True, db_comment='14日日均销量', decimal_places=2, max_digits=8, null=True, verbose_name='日均销量-14日'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_avg_volume_30d',
            field=models.DecimalField(blank=True, db_comment='30日日均销量', decimal_places=2, max_digits=8, null=True, verbose_name='日均销量-30日'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_avg_volume_7d',
            field=models.DecimalField(blank=True, db_comment='7日日均销量', decimal_places=2, max_digits=8, null=True, verbose_name='日均销量-7日'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_volume_14d',
            field=models.IntegerField(blank=True, db_comment='14天销量', null=True, verbose_name='销量-14天'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_volume_1d',
            field=models.IntegerField(blank=True, db_comment='昨天销量', null=True, verbose_name='销量-昨天'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_volume_30d',
            field=models.IntegerField(blank=True, db_comment='30天销量', null=True, verbose_name='销量-30天'),
        ),
        migrations.AddField(
            model_name='amazonlistingv2',
            name='sales_volume_7d',
            field=models.IntegerField(blank=True, db_comment='7天销量', null=True, verbose_name='销量-7天'),
        ),
    ]
