# Generated by Django 5.2.7 on 2025-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_amazonshopdailycheck_last_restock_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonshopdailycheck',
            name='shop_status',
            field=models.CharField(blank=True, db_comment='店铺状况', default='', max_length=100, null=True),
        ),
    ]
