# Generated by Django 5.2.7 on 2025-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_alter_amazonshopdailycheck_shop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshopemail',
            name='email_body',
            field=models.TextField(blank=True, null=True, verbose_name='邮件内容'),
        ),
    ]
