# Generated by Django 5.2.7 on 2026-04-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_amazonlistingv2_sales_amount_14d_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonListingSalesHistory',
        ),
    ]
