# Generated by Django 5.2.7 on 2025-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0016_amazonshopemail_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshopemail',
            name='html_body',
            field=models.TextField(blank=True, null=True, verbose_name='HTML邮件内容'),
        ),
    ]
