# Generated by Django 5.2.7 on 2025-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0017_amazonshopemail_html_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorders',
            name='latest_ship_date',
            field=models.DateTimeField(blank=True, db_comment='承诺配送订单的最晚发货时间', null=True, verbose_name='最晚发货时间'),
        ),
        migrations.AlterField(
            model_name='amazonorders',
            name='earliest_ship_date_local',
            field=models.DateTimeField(blank=True, db_comment='最晚发货时间（本地时间）列表的 - 放弃', null=True),
        ),
        migrations.AlterField(
            model_name='amazonorders',
            name='earliest_ship_date_utc',
            field=models.DateTimeField(blank=True, db_comment='最晚发货时间（UTC）列表的 - 放弃', null=True),
        ),
    ]
