# Generated by Django 5.2.7 on 2026-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0019_amazonorderfulldetail_amazonorderitemfulldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonshopdailycheck',
            name='withdrawal_amount',
            field=models.DecimalField(blank=True, db_comment='提现金额', decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
