# Generated by Django 5.2.7 on 2025-12-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment="物流商代码，如 'usps'", max_length=50, unique=True)),
                ('name_cn', models.CharField(blank=True, db_comment='物流商中文名称', max_length=100)),
                ('name_en', models.CharField(blank=True, db_comment='物流商英文名称', max_length=100)),
                ('homepage', models.URLField(blank=True, db_comment='物流商官网地址')),
            ],
            options={
                'verbose_name': '物流商基础信息表',
                'verbose_name_plural': '物流商',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.CharField(db_comment='运单号（唯一标识）', db_index=True, max_length=100, unique=True)),
                ('transit_status', models.CharField(blank=True, db_comment="当前运输状态，如 'DELIVERED'、'IN_TRANSIT'", db_index=True, max_length=50)),
                ('transit_sub_status', models.CharField(blank=True, db_comment='运输子状态', max_length=50)),
                ('order_time', models.DateTimeField(blank=True, db_comment='订单下单时间', null=True)),
                ('delivered_time', models.DateTimeField(blank=True, db_comment='签收时间', db_index=True, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, db_comment='最后轨迹更新时间（用于异常监控）', db_index=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='本系统导入时间（北京时间）')),
                ('next_update_time', models.DateTimeField(blank=True, db_comment='建议下次查询时间', null=True)),
                ('stay_days', models.PositiveIntegerField(blank=True, db_comment='停滞天数', null=True)),
                ('transit_days', models.PositiveIntegerField(blank=True, db_comment='运输天数', null=True)),
                ('delivered_days', models.PositiveIntegerField(blank=True, db_comment='总签收天数', null=True)),
                ('ship_from', models.CharField(blank=True, db_comment='发货地国家代码', max_length=10)),
                ('ship_to', models.CharField(blank=True, db_comment='收货地国家代码', max_length=10)),
                ('shipment_type', models.CharField(blank=True, db_comment='运输方式', max_length=100)),
                ('raw_data', models.JSONField(blank=True, db_comment='原始API返回数据（备份用）', null=True)),
                ('courier', models.ForeignKey(blank=True, db_comment='关联物流商', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Track.courier')),
            ],
            options={
                'verbose_name': '物流运单主表',
                'verbose_name_plural': '运单',
            },
        ),
        migrations.CreateModel(
            name='TrackingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(db_comment='事件发生时间（原样存储API返回的本地时间）', db_index=True)),
                ('address', models.CharField(blank=True, db_comment='事件地点', max_length=200)),
                ('event_detail', models.CharField(db_comment="事件描述，如 'Delivered, In/At Mailbox'", max_length=500)),
                ('transit_sub_status', models.CharField(blank=True, db_comment='该事件子状态', max_length=50)),
                ('tracking', models.ForeignKey(db_comment='关联运单', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Track.tracking')),
            ],
            options={
                'verbose_name': '物流轨迹明细表',
                'verbose_name_plural': '轨迹明细',
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['transit_status'], name='Track_track_transit_c52094_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['delivered_time'], name='Track_track_deliver_27e482_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['last_update_time'], name='Track_track_last_up_b5e166_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['courier'], name='Track_track_courier_33fb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingdetail',
            index=models.Index(fields=['event_time'], name='Track_track_event_t_66fea1_idx'),
        ),
    ]
