# Generated by Django 5.2.7 on 2025-12-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-create_time'], 'verbose_name': '物流运单主表', 'verbose_name_plural': '运单'},
        ),
        migrations.AddField(
            model_name='tracking',
            name='content_type',
            field=models.ForeignKey(blank=True, db_comment='关联订单类型', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_comment='关联订单ID', null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='ops_group',
            field=models.CharField(blank=True, db_comment='运营分组（冗余）', db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='ops_name',
            field=models.CharField(blank=True, db_comment='运营姓名（冗余）', db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='order_id',
            field=models.CharField(blank=True, db_comment='订单号（冗余）', db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='platform',
            field=models.CharField(blank=True, db_comment='平台来源（amazon/temu/other）', db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['platform'], name='Track_track_platfor_ed2f09_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['order_id'], name='Track_track_order_i_fe8676_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['ops_group'], name='Track_track_ops_gro_7e2cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='tracking',
            index=models.Index(fields=['ops_name'], name='Track_track_ops_nam_0f9212_idx'),
        ),
    ]
