# Generated by Django 5.2.7 on 2026-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProcurementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(blank=True, db_comment='产品编号', null=True)),
                ('product_name', models.CharField(blank=True, db_comment='产品名称', max_length=255, null=True)),
                ('is_listed', models.BooleanField(db_comment='是否上架', default=False)),
                ('color', models.CharField(blank=True, db_comment='颜色', max_length=50, null=True)),
                ('size', models.CharField(blank=True, db_comment='规格', max_length=255, null=True)),
                ('divi_color', models.CharField(blank=True, db_comment='divi颜色', max_length=50, null=True)),
                ('divi_size', models.CharField(blank=True, db_comment='divi尺码', max_length=255, null=True)),
                ('min_order_qty', models.CharField(blank=True, db_comment='起批量', max_length=100, null=True)),
                ('purchase_unit_origin_price', models.DecimalField(db_comment='采购原单价', decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_unit_now_price', models.DecimalField(blank=True, db_comment='采购现单价', decimal_places=2, max_digits=10, null=True)),
                ('platform', models.CharField(choices=[('yzg', '艺之冠'), ('sds', 'SDS'), ('fn', '蜂鸟'), ('s2b', 'S2B'), ('yjl', '艺捷乐'), ('zw', '指纹')], db_comment='外采平台', max_length=20)),
            ],
            options={
                'verbose_name': '外采平台产品',
                'verbose_name_plural': '外采平台产品',
                'db_table': 'Track_external_procurement_products',
                'indexes': [models.Index(fields=['platform', 'product_id'], name='Track_exter_platfor_e8d473_idx'), models.Index(fields=['platform', 'is_listed'], name='Track_exter_platfor_bfa151_idx'), models.Index(fields=['platform', 'color', 'size'], name='Track_exter_platfor_670e64_idx')],
            },
        ),
    ]
