# Generated by Django 5.2.7 on 2026-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_externalprocurementproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprocurementproduct',
            name='process_type',
            field=models.CharField(choices=[('embroidery', '刺绣'), ('printing', '印花'), ('laser', '镭射')], db_comment='工艺类型', default='printing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='externalprocurementproduct',
            index=models.Index(fields=['process_type'], name='Track_exter_process_dcd7e0_idx'),
        ),
    ]
