# Generated by Django 5.2.7 on 2025-12-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_alter_tracking_options_tracking_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='工厂名称', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '工厂',
                'verbose_name_plural': '工厂',
            },
        ),
        migrations.AddField(
            model_name='tracking',
            name='factory',
            field=models.ForeignKey(blank=True, db_comment='关联工厂', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Track.factory'),
        ),
    ]
