# Generated by Django 5.2.7 on 2025-12-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_factory_tracking_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='cancel_bool',
            field=models.BooleanField(db_comment='运单是否取消', default=False),
        ),
    ]
