# Generated by Django 5.2.7 on 2026-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_externalprocurementproduct_process_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalprocurementproduct',
            options={'verbose_name': '外采平台产品总表', 'verbose_name_plural': '外采平台产品总表'},
        ),
        migrations.AlterField(
            model_name='externalprocurementproduct',
            name='process_type',
            field=models.CharField(choices=[('embroidery', '刺绣'), ('printing', '印花'), ('laser', '镭射')], db_comment='工艺类型', max_length=20),
        ),
    ]
