# Generated by Django 5.2.7 on 2026-01-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0004_tracking_cancel_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='remark',
            field=models.CharField(blank=True, db_comment='物流单号备注信息', max_length=200, null=True),
        ),
    ]
