# Generated by Django 5.2.7 on 2026-01-19 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('title', models.CharField(max_length=500, verbose_name='产品标题')),
                ('title_translation', models.CharField(blank=True, max_length=500, verbose_name='标题翻译')),
                ('subject', models.CharField(max_length=200, verbose_name='产品主题')),
                ('subject_translation', models.CharField(blank=True, max_length=200, verbose_name='主题翻译')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='上架时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次抓取时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_latest_deal', models.BooleanField(default=False, verbose_name='是否为最新成交')),
                ('product_type', models.CharField(choices=[('new_peculiar', '新奇特'), ('new_arrival', '新品榜')], max_length=20, verbose_name='产品类型')),
            ],
            options={
                'verbose_name': '亚马逊产品',
                'verbose_name_plural': '亚马逊产品',
                'db_table': 'amazon_product',
            },
        ),
        migrations.CreateModel(
            name='AmazonTheme',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('title', models.CharField(max_length=500, verbose_name='产品标题')),
                ('title_translation', models.CharField(blank=True, max_length=500, verbose_name='标题译文')),
                ('subject', models.CharField(max_length=200, verbose_name='产品主题')),
                ('subject_translation', models.CharField(blank=True, max_length=200, verbose_name='主题译文')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='上架日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_latest_deal', models.BooleanField(default=False, verbose_name='是否为最新成交')),
            ],
            options={
                'verbose_name': '亚马逊主题表',
                'verbose_name_plural': '亚马逊主题表',
                'db_table': 'theme_amazon',
            },
        ),
        migrations.CreateModel(
            name='EntityTypeMapping',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='法律实体类型码')),
                ('description', models.CharField(max_length=100, verbose_name='法律实体类型描述')),
            ],
            options={
                'verbose_name': '法律实体类型映射',
                'verbose_name_plural': '法律实体类型映射',
                'db_table': 'theme_entity_type_mapping',
            },
        ),
        migrations.CreateModel(
            name='MarkDrawingTypeMapping',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='商标绘制类型码')),
                ('description_en', models.CharField(max_length=255, verbose_name='商标绘制类型英文描述')),
                ('description_cn', models.CharField(max_length=255, verbose_name='商标绘制类型中文描述')),
            ],
            options={
                'verbose_name': '商标绘制类型映射',
                'verbose_name_plural': '商标绘制类型映射',
                'db_table': 'theme_mark_drawing_type_mapping',
            },
        ),
        migrations.CreateModel(
            name='NameTypeMapping',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='侵权类型码')),
                ('rank_level', models.CharField(max_length=50, verbose_name='侵权类型等级')),
            ],
            options={
                'verbose_name': '侵权类型映射',
                'verbose_name_plural': '侵权类型映射',
                'db_table': 'theme_name_type_mapping',
            },
        ),
        migrations.CreateModel(
            name='StatusCodeMapping',
            fields=[
                ('status_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='商标状态码')),
                ('status_type', models.CharField(max_length=50, verbose_name='商标状态类型')),
            ],
            options={
                'verbose_name': '商标状态码映射',
                'verbose_name_plural': '商标状态码映射',
                'db_table': 'theme_status_code_mapping',
            },
        ),
        migrations.CreateModel(
            name='ThemeTrashBin',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ASIN')),
            ],
            options={
                'db_table': 'theme_trash_bin',
            },
        ),
        migrations.CreateModel(
            name='ThemeDailySubjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='统计日期')),
                ('subject_snapshot', models.CharField(max_length=200, verbose_name='主题')),
                ('appear_count', models.IntegerField(default=0, verbose_name='出现次数')),
            ],
            options={
                'verbose_name': '当日主题统计',
                'verbose_name_plural': '当日主题统计',
                'db_table': 'theme_daily_subject_stat',
                'indexes': [models.Index(fields=['record_date'], name='theme_daily_record__d64a87_idx'), models.Index(fields=['record_date', 'subject_snapshot'], name='theme_daily_record__2591d8_idx')],
                'unique_together': {('record_date', 'subject_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='ProductRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateField(verbose_name='爬取日期')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='当前排名')),
                ('rank_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='排名大类')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='theme.amazonproduct', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '排名历史',
                'verbose_name_plural': '排名历史',
                'db_table': 'product_rank_history',
                'indexes': [models.Index(fields=['product', 'crawl_date'], name='product_ran_product_bc3794_idx'), models.Index(fields=['crawl_date'], name='product_ran_crawl_d_73ba45_idx')],
                'unique_together': {('product', 'crawl_date')},
            },
        ),
        migrations.CreateModel(
            name='ThemeDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateField(verbose_name='抓取日期')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('rank_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='排名分类')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('appear_count', models.IntegerField(default=1, verbose_name='重复数')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='theme.amazontheme', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '排名历史',
                'verbose_name_plural': '排名历史',
                'db_table': 'theme_daily_data',
                'indexes': [models.Index(fields=['product', 'crawl_date'], name='theme_daily_product_794ed1_idx'), models.Index(fields=['crawl_date'], name='theme_daily_crawl_d_a2c085_idx')],
                'unique_together': {('product', 'crawl_date')},
            },
        ),
        migrations.CreateModel(
            name='ThemeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infringement_level', models.CharField(max_length=10, verbose_name='侵权等级(词库)')),
                ('infringement_words', models.JSONField(blank=True, null=True, verbose_name='侵权词列表(词库)')),
                ('ai_infringement_level', models.CharField(max_length=10, verbose_name='侵权等级(AI)')),
                ('ai_infringement_words', models.JSONField(blank=True, null=True, verbose_name='侵权词列表(AI)')),
                ('duplicate_count', models.IntegerField(default=1, verbose_name='重复数')),
                ('record_date', models.DateField(verbose_name='生成日期')),
                ('record_time', models.DateTimeField(verbose_name='生成时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_records', to='theme.amazontheme', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': 'AI主题记录',
                'verbose_name_plural': 'AI主题记录',
                'db_table': 'theme_record',
                'indexes': [models.Index(fields=['record_date'], name='theme_recor_record__470761_idx'), models.Index(fields=['infringement_level'], name='theme_recor_infring_1ae917_idx'), models.Index(fields=['ai_infringement_level'], name='theme_recor_ai_infr_42fdb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrademarkInfo',
            fields=[
                ('serial_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='商标注册号')),
                ('word_mark', models.CharField(max_length=100, verbose_name='侵权词')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='注册号')),
                ('filing_date', models.DateField(auto_now_add=True, verbose_name='入库时间')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='注册日期')),
                ('transaction_date', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('intl_class', models.CharField(blank=True, max_length=500, null=True, verbose_name='国际类')),
                ('owner_name', models.CharField(blank=True, max_length=525, null=True, verbose_name='商标所有者')),
                ('entity_statement', models.CharField(blank=True, max_length=500, null=True, verbose_name='法律实体声明')),
                ('legal_entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademark_entities', to='theme.entitytypemapping', verbose_name='法律实体类型')),
                ('mark_drawing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademarks', to='theme.markdrawingtypemapping', verbose_name='商标绘制类型')),
                ('status_code', models.ForeignKey(blank=True, db_column='status_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademarks', to='theme.statuscodemapping', verbose_name='商标状态码')),
            ],
            options={
                'verbose_name': '美标网表',
                'verbose_name_plural': '美标网表',
                'db_table': 'theme_trademark_info',
                'indexes': [models.Index(fields=['word_mark', 'status_code'], name='theme_trade_word_ma_d848e9_idx'), models.Index(fields=['word_mark', 'mark_drawing_type', 'status_code'], name='theme_trade_word_ma_8b78a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TroTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=765, verbose_name='侵权词名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tro_words', to='theme.nametypemapping', verbose_name='侵权类型')),
            ],
            options={
                'verbose_name': '侵权词表',
                'verbose_name_plural': '侵权词表',
                'db_table': 'theme_tro_table',
                'indexes': [models.Index(fields=['theme_name'], name='theme_tro_t_theme_n_c5660d_idx'), models.Index(fields=['name_type'], name='theme_tro_t_name_ty_a0c428_idx'), models.Index(fields=['theme_name', 'name_type'], name='theme_tro_t_theme_n_d25635_idx')],
            },
        ),
    ]
