# Generated by Django 5.2.7 on 2026-01-13 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('title', models.CharField(max_length=500, verbose_name='产品标题')),
                ('title_translation', models.CharField(blank=True, max_length=500, verbose_name='标题翻译')),
                ('subject', models.CharField(max_length=200, verbose_name='产品主题')),
                ('subject_translation', models.CharField(blank=True, max_length=200, verbose_name='主题翻译')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='上架时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次抓取时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_latest_deal', models.BooleanField(default=False, verbose_name='是否为最新成交')),
                ('product_type', models.CharField(choices=[('new_peculiar', '新奇特'), ('new_arrival', '新品榜')], max_length=20, verbose_name='产品类型')),
            ],
            options={
                'verbose_name': '亚马逊产品',
                'verbose_name_plural': '亚马逊产品',
                'db_table': 'amazon_product',
            },
        ),
        migrations.CreateModel(
            name='ProductRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateField(verbose_name='爬取日期')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='当前排名')),
                ('rank_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='排名大类')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='theme.amazonproduct', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '排名历史',
                'verbose_name_plural': '排名历史',
                'db_table': 'product_rank_history',
                'indexes': [models.Index(fields=['product', 'crawl_date'], name='product_ran_product_bc3794_idx'), models.Index(fields=['crawl_date'], name='product_ran_crawl_d_73ba45_idx')],
                'unique_together': {('product', 'crawl_date')},
            },
        ),
    ]
