# Generated by Django 5.2.7 on 2026-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkinfo',
            name='word_mark',
            field=models.CharField(max_length=525, verbose_name='侵权词'),
        ),
    ]
