# Generated by Django 5.2.7 on 2026-01-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonTheme',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('title', models.CharField(max_length=500, verbose_name='产品标题')),
                ('title_translation', models.CharField(blank=True, max_length=500, verbose_name='标题译文')),
                ('subject', models.CharField(max_length=200, verbose_name='产品主题')),
                ('subject_translation', models.CharField(blank=True, max_length=200, verbose_name='主题译文')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='上架日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('a', models.CharField(max_length=50, verbose_name='主题分类')),
            ],
            options={
                'verbose_name': '亚马逊主题表',
                'verbose_name_plural': '亚马逊主题表',
                'db_table': 'theme_amazon',
            },
        ),
        migrations.CreateModel(
            name='ThemeDailySubjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='统计日期')),
                ('subject_snapshot', models.CharField(max_length=200, verbose_name='主题')),
                ('appear_count', models.IntegerField(default=0, verbose_name='出现次数')),
            ],
            options={
                'verbose_name': '当日主题统计',
                'verbose_name_plural': '当日主题统计',
                'db_table': 'theme_daily_subject_stat',
                'indexes': [models.Index(fields=['record_date'], name='theme_daily_record__d64a87_idx'), models.Index(fields=['record_date', 'subject_snapshot'], name='theme_daily_record__2591d8_idx')],
                'unique_together': {('record_date', 'subject_snapshot')},
            },
        ),
        migrations.CreateModel(
            name='ThemeDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateField(verbose_name='抓取日期')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('rank_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='排名分类')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='theme.amazontheme', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '排名历史',
                'verbose_name_plural': '排名历史',
                'db_table': 'theme_daily_data',
                'indexes': [models.Index(fields=['product', 'crawl_date'], name='theme_daily_product_794ed1_idx'), models.Index(fields=['crawl_date'], name='theme_daily_crawl_d_a2c085_idx')],
                'unique_together': {('product', 'crawl_date')},
            },
        ),
        migrations.CreateModel(
            name='ThemeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infringement_level', models.CharField(max_length=10, verbose_name='侵权等级(词库)')),
                ('infringement_words', models.JSONField(blank=True, null=True, verbose_name='侵权词列表(词库)')),
                ('ai_infringement_level', models.CharField(max_length=10, verbose_name='侵权等级(AI)')),
                ('ai_infringement_words', models.JSONField(blank=True, null=True, verbose_name='侵权词列表(AI)')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('duplicate_count', models.IntegerField(default=1, verbose_name='重复数')),
                ('record_date', models.DateField(verbose_name='生成日期')),
                ('record_time', models.DateTimeField(verbose_name='生成时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_records', to='theme.amazontheme', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': 'AI主题记录',
                'verbose_name_plural': 'AI主题记录',
                'db_table': 'theme_record',
                'indexes': [models.Index(fields=['record_date'], name='theme_recor_record__470761_idx'), models.Index(fields=['score'], name='theme_recor_score_5908ea_idx'), models.Index(fields=['infringement_level'], name='theme_recor_infring_1ae917_idx'), models.Index(fields=['ai_infringement_level'], name='theme_recor_ai_infr_42fdb7_idx')],
            },
        ),
    ]
