# Generated by Django 5.2.7 on 2026-01-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('new_peculiar', '新奇特'), ('new_arrival', '新品榜')], max_length=20, null=True, verbose_name='产品类型'),
        ),
    ]
