# Generated by Django 5.2.7 on 2026-01-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0002_amazonproduct_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='product_type',
            field=models.CharField(choices=[('new_peculiar', '新奇特'), ('new_arrival', '新品榜')], default='new_peculiar', max_length=20, verbose_name='产品类型'),
            preserve_default=False,
        ),
    ]
