# Generated by Django 5.2.7 on 2026-01-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_amazontheme_themedailysubjectstat_themedailydata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazontheme',
            name='a',
        ),
        migrations.AddField(
            model_name='amazontheme',
            name='is_latest_deal',
            field=models.BooleanField(default=False, verbose_name='是否为最新成交'),
        ),
        migrations.AddField(
            model_name='themedailydata',
            name='appear_count',
            field=models.IntegerField(default=1, verbose_name='出现次数'),
        ),
    ]
