# Generated by Django 5.2.7 on 2026-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_trademarkinfo_word_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkinfo',
            name='filing_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='入库时间'),
        ),
    ]
