# Generated by Django 5.2.7 on 2026-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0003_alter_amazonproduct_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrankhistory',
            name='rank_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='排名大类'),
        ),
    ]
