# Generated by Django 5.2.7 on 2026-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_remove_amazontheme_a_amazontheme_is_latest_deal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeTrashBin',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ASIN')),
            ],
            options={
                'db_table': 'theme_trash_bin',
            },
        ),
        migrations.RemoveIndex(
            model_name='themerecord',
            name='theme_recor_score_5908ea_idx',
        ),
        migrations.RemoveField(
            model_name='themerecord',
            name='score',
        ),
        migrations.AddField(
            model_name='themedailydata',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='themedailydata',
            name='appear_count',
            field=models.IntegerField(default=1, verbose_name='重复数'),
        ),
    ]
