# Generated by Django 5.2.7 on 2026-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_trademarkinfo_filing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trotable',
            name='name_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='侵权类型码'),
        ),
        migrations.RenameIndex(
            model_name='trotable',
            new_name='theme_tro_t_name_ty_8bb416_idx',
            old_name='theme_tro_t_name_ty_a0c428_idx',
        ),
        migrations.RenameIndex(
            model_name='trotable',
            new_name='theme_tro_t_theme_n_f0ca78_idx',
            old_name='theme_tro_t_theme_n_d25635_idx',
        ),
        migrations.DeleteModel(
            name='NameTypeMapping',
        ),
    ]
