# Generated by Django 5.2.7 on 2026-01-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_alter_trotable_name_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonTheme',
            new_name='AmazonThemeNovelty',
        ),
        migrations.AlterModelTable(
            name='amazonthemenovelty',
            table='theme_amazon_novelty',
        ),
    ]
