# Generated by Django 5.2.7 on 2026-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theme', '0004_alter_productrankhistory_rank_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='is_latest_deal',
            field=models.BooleanField(default=False, verbose_name='是否为最新成交'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
