# Generated by Django 5.2.7 on 2026-01-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_rename_amazontheme_amazonthemenovelty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themerecord',
            name='duplicate_count',
        ),
    ]
