# Generated by Django 5.2.7 on 2026-01-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_remove_themerecord_duplicate_count'),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name='trademarkinfo',
        #     new_name='theme_trade_word_ma_31ebb4_idx',
        #     old_name='theme_trade_word_ma_8b78a9_idx',
        # ),
        migrations.AddField(
            model_name='trotable',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建人'),
        ),
        # migrations.AlterField(
        #     model_name='trademarkinfo',
        #     name='legal_entity_type',
        #     field=models.ForeignKey(blank=True, db_column='legal_entity_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademark_entities', to='theme.entitytypemapping', verbose_name='法律实体类型'),
        # ),
        # migrations.AlterField(
        #     model_name='trademarkinfo',
        #     name='mark_drawing_type',
        #     field=models.ForeignKey(blank=True, db_column='mark_drawing_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademarks', to='theme.markdrawingtypemapping', verbose_name='商标绘制类型'),
        # ),
    ]
