# Generated by Django 5.2.7 on 2026-01-29 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_auto_20260123_0919'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
            ],
            options={
                'verbose_name': '主题举报记录',
                'verbose_name_plural': '主题举报记录',
                'db_table': 'theme_reports',
            },
        ),
        migrations.AlterField(
            model_name='trademarkinfo',
            name='legal_entity_type',
            field=models.ForeignKey(blank=True, db_column='legal_entity_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademark_entities', to='theme.entitytypemapping', verbose_name='法律实体类型'),
        ),
        migrations.AlterField(
            model_name='trademarkinfo',
            name='mark_drawing_type',
            field=models.ForeignKey(blank=True, db_column='mark_drawing_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademarks', to='theme.markdrawingtypemapping', verbose_name='商标绘制类型'),
        ),
        migrations.AlterField(
            model_name='trademarkinfo',
            name='status_code',
            field=models.ForeignKey(blank=True, db_column='status_code', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trademarks', to='theme.statuscodemapping', verbose_name='商标状态码'),
        ),
        migrations.AddIndex(
            model_name='trademarkinfo',
            index=models.Index(fields=['word_mark', 'status_code'], name='theme_trade_word_ma_d848e9_idx'),
        ),
        migrations.AddIndex(
            model_name='trademarkinfo',
            index=models.Index(fields=['word_mark', 'mark_drawing_type', 'status_code'], name='theme_trade_word_ma_31ebb4_idx'),
        ),
        migrations.AddField(
            model_name='themereport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_reports', to='theme.amazonthemenovelty', verbose_name='商品ASIN'),
        ),
        migrations.AddField(
            model_name='themereport',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人'),
        ),
        migrations.AddIndex(
            model_name='themereport',
            index=models.Index(fields=['product', 'is_active'], name='theme_repor_product_0baafc_idx'),
        ),
        migrations.AddIndex(
            model_name='themereport',
            index=models.Index(fields=['reporter', 'is_active'], name='theme_repor_reporte_9e2cba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='themereport',
            unique_together={('product', 'reporter')},
        ),
    ]
