# Generated by Django 5.2.7 on 2026-02-04 16:04
# Modified to handle existing table scenario

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_riskkeyword_and_more'),
        ('theme', '0009_themereport_alter_trademarkinfo_legal_entity_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # 数据库操作：条件创建表和中间表
            database_operations=[
                # 1. 创建 AmazonListing 表（如果不存在）
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS amazon_listing (
                        id BIGSERIAL PRIMARY KEY,
                        asin VARCHAR(10) NOT NULL,
                        title VARCHAR(500) NULL,
                        is_active BOOLEAN DEFAULT TRUE NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                        lingxing_shop_id INTEGER NOT NULL REFERENCES amazon_lingxingamazonshop(id) ON DELETE CASCADE
                    );
                    COMMENT ON TABLE amazon_listing IS 'Listing主表（店铺+ASIN唯一）';
                    
                    -- 创建索引
                    CREATE INDEX IF NOT EXISTS idx_listing_asin ON amazon_listing(asin);
                    CREATE INDEX IF NOT EXISTS idx_listing_active ON amazon_listing(is_active);
                    CREATE INDEX IF NOT EXISTS idx_listing_created ON amazon_listing(created_at);
                    
                    -- 创建唯一约束
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint 
                            WHERE conname = 'uniq_lingxing_shop_asin'
                        ) THEN
                            ALTER TABLE amazon_listing 
                            ADD CONSTRAINT uniq_lingxing_shop_asin 
                            UNIQUE (lingxing_shop_id, asin);
                        END IF;
                    END $$;
                    """,
                    reverse_sql="DROP TABLE IF EXISTS amazon_listing CASCADE;"
                ),
                
                # 2. 创建 amazon_listing_tro_words 中间表（ManyToMany）
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS amazon_listing_tro_words (
                        id BIGSERIAL PRIMARY KEY,
                        amazonlisting_id BIGINT NOT NULL REFERENCES amazon_listing(id) ON DELETE CASCADE,
                        trotable_id INTEGER NOT NULL REFERENCES theme_tro_table(id) ON DELETE CASCADE,
                        CONSTRAINT uniq_listing_tro UNIQUE (amazonlisting_id, trotable_id)
                    );
                    
                    CREATE INDEX IF NOT EXISTS idx_tro_words_listing_id ON amazon_listing_tro_words(amazonlisting_id);
                    CREATE INDEX IF NOT EXISTS idx_tro_words_tro_id ON amazon_listing_tro_words(trotable_id);
                    
                    COMMENT ON TABLE amazon_listing_tro_words IS 'AmazonListing 与 TroTable 的多对多关系中间表';
                    """,
                    reverse_sql="DROP TABLE IF EXISTS amazon_listing_tro_words;"
                ),
                
                # 3. 创建 amazon_listing_trademarks 中间表（ManyToMany）
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS amazon_listing_trademarks (
                        id BIGSERIAL PRIMARY KEY,
                        amazonlisting_id BIGINT NOT NULL REFERENCES amazon_listing(id) ON DELETE CASCADE,
                        trademarkinfo_id VARCHAR(10) NOT NULL REFERENCES theme_trademark_info(serial_number) ON DELETE CASCADE,
                        CONSTRAINT uniq_listing_trademark UNIQUE (amazonlisting_id, trademarkinfo_id)
                    );
                    
                    CREATE INDEX IF NOT EXISTS idx_trademarks_listing_id ON amazon_listing_trademarks(amazonlisting_id);
                    CREATE INDEX IF NOT EXISTS idx_trademarks_trademark_id ON amazon_listing_trademarks(trademarkinfo_id);
                    
                    COMMENT ON TABLE amazon_listing_trademarks IS 'AmazonListing 与 TrademarkInfo 的多对多关系中间表';
                    """,
                    reverse_sql="DROP TABLE IF EXISTS amazon_listing_trademarks;"
                ),
            ],

            # 状态操作：告诉 Django 模型状态
            state_operations=[
                migrations.CreateModel(
                    name='AmazonListing',
                    fields=[
                        ('id', models.BigAutoField(db_comment='自增主键', primary_key=True, serialize=False, verbose_name='ID')),
                        ('asin', models.CharField(db_comment='亚马逊商品编码', db_index=True, max_length=10, verbose_name='ASIN')),
                        ('title', models.CharField(blank=True, db_comment='Listing标题', max_length=500, null=True, verbose_name='标题')),
                        ('is_active', models.BooleanField(db_comment='Listing是否处于在售状态', default=True, verbose_name='是否在售')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                        ('lingxing_shop', models.ForeignKey(db_comment='绑定的领星站点店铺', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='amazon.lingxingamazonshop', verbose_name='所属领星店铺')),
                        ('trademarks', models.ManyToManyField(blank=True, related_name='listings', to='theme.trademarkinfo', verbose_name='命中商标')),
                        ('tro_words', models.ManyToManyField(blank=True, related_name='listings', to='theme.trotable', verbose_name='命中侵权词')),
                    ],
                    options={
                        'verbose_name': 'Amazon Listing',
                        'verbose_name_plural': 'Amazon Listings',
                        'db_table': 'amazon_listing',
                        'db_table_comment': 'Listing主表（店铺+ASIN唯一）',
                        'indexes': [models.Index(fields=['asin'], name='idx_listing_asin'), models.Index(fields=['is_active'], name='idx_listing_active'), models.Index(fields=['created_at'], name='idx_listing_created')],
                        'constraints': [models.UniqueConstraint(fields=('lingxing_shop', 'asin'), name='uniq_lingxing_shop_asin')],
                    },
                ),
            ],
        ),
    ]
