# Generated by Django 5.2.7 on 2026-02-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_themereport_alter_trademarkinfo_legal_entity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiceClassification',
            fields=[
                ('code', models.CharField(help_text='01-45，带前导零', max_length=2, primary_key=True, serialize=False, verbose_name='分类编号')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('category_type', models.CharField(choices=[('goods', '商品'), ('service', '服务')], db_index=True, max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name': '尼斯分类',
                'verbose_name_plural': '尼斯分类',
                'db_table': 'theme_nice_classification',
                'ordering': ['code'],
            },
        ),
    ]
