# Generated by Django 5.2.7 on 2026-02-07 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_niceclassification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trotable',
            name='created_by',
        ),
        migrations.AddField(
            model_name='trotable',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tro_words', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='trotable',
            name='international_classes',
            field=models.ManyToManyField(blank=True, db_table='theme_tro_nice_classification', related_name='tro_words', to='theme.niceclassification', verbose_name='所属国际类'),
        ),
    ]
