# Generated by Django 5.2.7 on 2026-02-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_amazonshop_channel_risk'),
        ('theme', '0011_remove_trotable_created_by_trotable_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trotable',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tro_words', to='general.amazonshop', verbose_name='所属店铺'),
        ),
    ]
