# Generated by Django 5.2.7 on 2026-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_trotable_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trotable',
            name='replacement_word',
            field=models.CharField(blank=True, help_text='检测到侵权时建议使用的替代词汇', max_length=765, null=True, verbose_name='建议替换词'),
        ),
    ]
