# Generated by Django 5.2.7 on 2026-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_trotable_replacement_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='trotable',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '文字侵权'), (2, '版权侵权'), (3, '商标侵权')], null=True, verbose_name='侵权分类'),
        ),
    ]
