# Generated by Django 5.2.7 on 2026-02-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0014_trotable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trotable',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '文字侵权'), (2, '版权侵权')], null=True, verbose_name='侵权分类'),
        ),
    ]
