# Generated by Django 5.2.7 on 2026-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0015_alter_trotable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trotable',
            name='theme_name',
            field=models.CharField(max_length=765, unique=True, verbose_name='侵权词名'),
        ),
    ]
