# Generated by Django 5.2.7 on 2026-03-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0016_alter_trotable_theme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='分类名称')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='层级')),
                ('path', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='路径ID链')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='theme.marketcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '市场分类',
                'verbose_name_plural': '市场分类',
                'db_table': 'theme_market_category',
            },
        ),
        migrations.CreateModel(
            name='NicheMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='细分市场名称')),
                ('market_name_cn', models.CharField(blank=True, max_length=255, verbose_name='中文翻译')),
                ('monthly_sales', models.BigIntegerField(blank=True, null=True, verbose_name='月总销量')),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='月均销售额')),
                ('leaf_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niche_markets', to='theme.marketcategory', verbose_name='所属叶子分类')),
            ],
            options={
                'verbose_name': '细分市场',
                'verbose_name_plural': '细分市场',
                'db_table': 'theme_niche_market',
            },
        ),
        migrations.AddIndex(
            model_name='marketcategory',
            index=models.Index(fields=['path'], name='theme_marke_path_8d0087_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketcategory',
            unique_together={('name', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='nichemarket',
            unique_together={('market_name', 'leaf_category')},
        ),
    ]
