# Generated by Django 5.2.7 on 2026-03-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0017_marketcategory_nichemarket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSubject',
            fields=[
                ('canonical_subject', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='标准化主题')),
                ('core_entities', models.JSONField(default=list, verbose_name='核心实体')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '核心主题',
                'verbose_name_plural': '核心主题',
                'db_table': 'theme_subject',
            },
        ),
        migrations.CreateModel(
            name='ThemeNovelty',
            fields=[
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='theme_novelty', serialize=False, to='theme.themesubject', verbose_name='核心主题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '新奇特主题',
                'verbose_name_plural': '新奇特主题',
                'db_table': 'theme_novelty',
            },
        ),
        migrations.AddField(
            model_name='amazonthemenovelty',
            name='theme_novelty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asins', to='theme.themenovelty', verbose_name='所属新奇特主题'),
        ),
        migrations.CreateModel(
            name='ThemeNoveltyDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_date', models.DateField(verbose_name='主题日期')),
                ('asin_count', models.IntegerField(default=0, verbose_name='当日ASIN数量')),
                ('ranked_asin_count', models.IntegerField(default=0, verbose_name='有排名ASIN数')),
                ('score', models.IntegerField(default=0, verbose_name='核心分值')),
                ('rank_trend_7d', models.JSONField(blank=True, default=list, verbose_name='7天排名趋势')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novelty_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='theme.themenovelty', verbose_name='新奇特主题')),
            ],
            options={
                'verbose_name': '新奇特主题每日数据',
                'verbose_name_plural': '新奇特主题每日数据',
                'db_table': 'theme_novelty_daily_data',
                'ordering': ['-theme_date'],
                'indexes': [models.Index(fields=['novelty_theme', 'theme_date'], name='theme_novel_novelty_fd922a_idx'), models.Index(fields=['theme_date', 'score'], name='theme_novel_theme_d_6689d4_idx')],
                'unique_together': {('novelty_theme', 'theme_date')},
            },
        ),
    ]
