# Generated by Django 5.2.7 on 2026-03-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0018_themesubject_themenovelty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonNewReleaseRank',
            fields=[
                ('asin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('title', models.CharField(max_length=500, verbose_name='产品标题')),
                ('title_translation', models.CharField(blank=True, max_length=500, verbose_name='标题译文')),
                ('subject', models.CharField(max_length=200, verbose_name='产品主题')),
                ('subject_translation', models.CharField(blank=True, max_length=200, verbose_name='主题译文')),
                ('category', models.CharField(max_length=100, verbose_name='产品分类')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片链接')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='上架日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '亚马逊新品榜主题表',
                'verbose_name_plural': '亚马逊新品榜主题表',
                'db_table': 'theme_amazon_new_release_rank',
            },
        ),
        migrations.CreateModel(
            name='ThemeNewDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_date', models.DateField(verbose_name='抓取日期')),
                ('rank_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='排名分类1')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名1')),
                ('rank_category2', models.CharField(blank=True, max_length=100, null=True, verbose_name='排名分类2')),
                ('rank2', models.IntegerField(blank=True, null=True, verbose_name='排名2')),
                ('rank_category3', models.CharField(blank=True, max_length=100, null=True, verbose_name='排名分类3')),
                ('rank3', models.IntegerField(blank=True, null=True, verbose_name='排名3')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('appear_count', models.IntegerField(default=1, verbose_name='重复数')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_release_daily_data', to='theme.amazonnewreleaserank', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '排名历史',
                'verbose_name_plural': '排名历史',
                'db_table': 'theme_new_daily_data',
                'indexes': [models.Index(fields=['product', 'crawl_date'], name='theme_new_d_product_7bba0c_idx'), models.Index(fields=['crawl_date'], name='theme_new_d_crawl_d_363683_idx')],
                'unique_together': {('product', 'crawl_date')},
            },
        ),
    ]
