# Generated by Django 5.2.7 on 2026-03-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0019_amazonnewreleaserank_themenewdailydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonnewreleaserank',
            name='category',
            field=models.CharField(db_index=True, max_length=100, verbose_name='产品分类'),
        ),
        migrations.CreateModel(
            name='ThemeSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_subject_title', models.CharField(max_length=525, unique=True, verbose_name='汇总主题')),
            ],
            options={
                'verbose_name': '主题汇总',
                'db_table': 'theme_summary',
                'indexes': [models.Index(fields=['summary_subject_title'], name='theme_summa_summary_2fb77b_idx')],
            },
        ),
        migrations.AddField(
            model_name='amazonnewreleaserank',
            name='summary_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_subject', to='theme.themesummary', verbose_name='汇总主题'),
        ),
    ]
