# Generated by Django 5.2.7 on 2026-03-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0020_alter_amazonnewreleaserank_category_themesummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonnewreleaserank',
            name='denoising',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否去噪'),
        ),
    ]
