# Generated by Django 5.2.7 on 2026-03-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0021_amazonnewreleaserank_denoising'),
    ]

    operations = [
        migrations.AddField(
            model_name='themenewdailydata',
            name='fulfillment',
            field=models.CharField(blank=True, choices=[('AMZ', 'Amz'), ('FBA', 'Fba'), ('FBM', 'Fbm')], max_length=10, null=True, verbose_name='配送方式'),
        ),
        migrations.AddIndex(
            model_name='themenewdailydata',
            index=models.Index(fields=['fulfillment'], name='theme_new_d_fulfill_54770f_idx'),
        ),
    ]
