# Generated by Django 5.2.7 on 2026-03-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0022_themenewdailydata_fulfillment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='themenewdailydata',
            name='theme_new_d_fulfill_54770f_idx',
        ),
        migrations.RemoveField(
            model_name='themenewdailydata',
            name='fulfillment',
        ),
        migrations.AddField(
            model_name='amazonnewreleaserank',
            name='fulfillment',
            field=models.CharField(blank=True, choices=[('AMZ', 'Amz'), ('FBA', 'Fba'), ('FBM', 'Fbm')], max_length=10, null=True, verbose_name='配送方式'),
        ),
        migrations.AddIndex(
            model_name='amazonnewreleaserank',
            index=models.Index(fields=['fulfillment'], name='theme_amazo_fulfill_652d3e_idx'),
        ),
    ]
