# Generated by Django 5.2.7 on 2026-03-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0023_remove_themenewdailydata_theme_new_d_fulfill_54770f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonnewreleaserank',
            name='report',
            field=models.BooleanField(default=False, verbose_name='举报ASIN'),
        ),
        migrations.AddField(
            model_name='themesummary',
            name='report',
            field=models.BooleanField(default=False, verbose_name='举报主题'),
        ),
    ]
