# Generated by Django 5.2.7 on 2026-04-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0024_amazonnewreleaserank_report_themesummary_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='themesummary',
            name='created_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='NewReleaseThemeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_release_theme_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_release_theme_reports', to='theme.themesummary', verbose_name='被举报主题')),
            ],
            options={
                'verbose_name': '新品榜主题举报记录',
                'verbose_name_plural': '新品榜主题举报记录',
                'db_table': 'theme_new_release_theme_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewReleaseAsinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_release_asin_reports', to='theme.amazonnewreleaserank', verbose_name='被举报ASIN')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_release_asin_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('source_theme_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asin_reports', to='theme.newreleasethemereport', verbose_name='来源主题举报')),
            ],
            options={
                'verbose_name': '新品榜ASIN举报记录',
                'verbose_name_plural': '新品榜ASIN举报记录',
                'db_table': 'theme_new_release_asin_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newreleasethemereport',
            index=models.Index(fields=['theme'], name='theme_new_r_theme_i_b2684e_idx'),
        ),
        migrations.AddIndex(
            model_name='newreleasethemereport',
            index=models.Index(fields=['reporter', 'created_at'], name='theme_new_r_reporte_885e26_idx'),
        ),
        migrations.AddConstraint(
            model_name='newreleasethemereport',
            constraint=models.UniqueConstraint(fields=('reporter', 'theme'), name='uniq_new_release_theme_report'),
        ),
        migrations.AddIndex(
            model_name='newreleaseasinreport',
            index=models.Index(fields=['asin'], name='theme_new_r_asin_id_9bc11b_idx'),
        ),
        migrations.AddIndex(
            model_name='newreleaseasinreport',
            index=models.Index(fields=['source_theme_report'], name='theme_new_r_source__98a83c_idx'),
        ),
        migrations.AddIndex(
            model_name='newreleaseasinreport',
            index=models.Index(fields=['reporter', 'created_at'], name='theme_new_r_reporte_134cdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='newreleaseasinreport',
            constraint=models.UniqueConstraint(condition=models.Q(('source_theme_report__isnull', True)), fields=('reporter', 'asin'), name='uniq_new_release_manual_asin_report'),
        ),
        migrations.AddConstraint(
            model_name='newreleaseasinreport',
            constraint=models.UniqueConstraint(condition=models.Q(('source_theme_report__isnull', False)), fields=('source_theme_report', 'asin'), name='uniq_new_release_theme_derived_asin_report'),
        ),
    ]
