# Generated by Django 5.2.7 on 2026-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0025_themesummary_created_time_newreleasethemereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeNoveltySummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_subject_title', models.CharField(max_length=525, unique=True, verbose_name='汇总主题')),
                ('created_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新奇特主题汇总',
                'db_table': 'theme_novelty_summary',
                'indexes': [models.Index(fields=['summary_subject_title'], name='theme_novel_summary_28fc27_idx')],
            },
        ),
    ]
