# Generated by Django 5.2.7 on 2026-04-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0026_themenoveltysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonthemenovelty',
            name='theme_novelty_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_subject', to='theme.themenoveltysummary', verbose_name='所属新奇特聚合主题'),
        ),
    ]
