# Generated by Django 5.2.7 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0027_amazonthemenovelty_theme_novelty_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommendedTheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(help_text='当天的推荐主题名称', max_length=255, verbose_name='推荐主题')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日推荐主题',
                'verbose_name_plural': '每日推荐主题',
                'db_table': 'theme_daily_recommended_theme',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('date', 'theme'), name='unique_daily_theme')],
            },
        ),
    ]
