# Generated by Django 5.2.7 on 2026-04-18 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0028_dailyrecommendedtheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonThemeCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=500, verbose_name='展示标题')),
                ('core_tags', models.JSONField(default=list, help_text="算法提取的核心特征词, 如 ['1776', '250th']", verbose_name='核心词')),
                ('fingerprint_count', models.IntegerField(default=0, verbose_name='聚类主题下Fingerprint数')),
                ('asin_count', models.IntegerField(default=0, verbose_name='聚类主题下ASIN数')),
                ('burst_score', models.FloatField(blank=True, default=0.0, null=True, verbose_name='爆发指数')),
                ('new_asin_7d', models.IntegerField(blank=True, default=0, null=True, verbose_name='7天内新上架数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '新奇特主题聚类',
                'verbose_name_plural': '新奇特主题聚类',
                'db_table': 'theme_novelty_cluster',
            },
        ),
        migrations.CreateModel(
            name='ThemeFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_key', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='指纹')),
                ('representative_title', models.CharField(max_length=500, verbose_name='代表性标题')),
                ('asin_count', models.IntegerField(default=0)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_theme', to='theme.amazonthemecluster', verbose_name='聚合标题')),
            ],
            options={
                'db_table': 'theme_novelty_fingerprint',
            },
        ),
        migrations.AddField(
            model_name='amazonnewreleaserank',
            name='fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint', to='theme.themefingerprint', verbose_name='关联指纹'),
        ),
    ]
