# Generated by Django 5.2.7 on 2026-04-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0030_amazonthemeclusternovelty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommendedThemeV2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], db_index=True, max_length=20, verbose_name='时间维度')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='榜单归属日期')),
                ('window_start', models.DateField(db_index=True, verbose_name='统计窗口开始日期')),
                ('window_end', models.DateField(db_index=True, verbose_name='统计窗口结束日期')),
                ('source', models.CharField(choices=[('novelty', '新奇特'), ('new_release', '新品榜'), ('aba', 'ABA')], db_index=True, max_length=20, verbose_name='来源')),
                ('reason_type', models.CharField(choices=[('novelty_score', '新奇特分值'), ('new_release_new_asin', '新品榜新增ASIN'), ('new_release_rank_up', '新品榜排名上升'), ('aba_burst', 'ABA爆发'), ('aba_surge', 'ABA飙升'), ('aba_continuous_growth', 'ABA持续增长')], db_index=True, max_length=50, verbose_name='推荐原因')),
                ('theme', models.CharField(help_text='新奇特/新品榜存display_title，ABA存搜索词term', max_length=525, verbose_name='推荐主题')),
                ('source_object_type', models.CharField(choices=[('novelty_cluster', '新奇特聚合主题'), ('new_release_cluster', '新品榜聚合主题'), ('aba_search_term', 'ABA搜索词')], db_index=True, max_length=50, verbose_name='来源对象类型')),
                ('source_object_id', models.IntegerField(db_index=True, help_text='cluster id 或 aba_db.search_terms.id', verbose_name='来源对象ID')),
                ('source_metric_id', models.IntegerField(blank=True, db_index=True, help_text='ABA可存aba_db.search_term_metrics.id', null=True, verbose_name='来源指标ID')),
                ('source_date', models.DateField(db_index=True, help_text='ABA存report_week，其他来源存命中日期', verbose_name='来源数据日期')),
                ('asin_count', models.IntegerField(default=0, verbose_name='命中ASIN数量')),
                ('metric_value', models.FloatField(blank=True, db_index=True, help_text='排名上升百分比、最高分值、前三转化份额等', null=True, verbose_name='主指标值')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='指标明细')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐主题',
                'verbose_name_plural': '推荐主题',
                'db_table': 'theme_daily_recommended_theme_v2',
                'ordering': ['-snapshot_date', '-metric_value', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedThemeAsin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asin', models.CharField(db_index=True, max_length=20, verbose_name='ASIN')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='产品标题')),
                ('launch_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='上架日期')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('score', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='分值')),
                ('source_position', models.IntegerField(default=0, verbose_name='来源排序位')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='ASIN指标明细')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐主题ASIN',
                'verbose_name_plural': '推荐主题ASIN',
                'db_table': 'theme_recommended_theme_asin',
                'ordering': ['recommended_theme', 'source_position', 'asin'],
            },
        ),
        migrations.DeleteModel(
            name='DailyRecommendedTheme',
        ),
        migrations.AddIndex(
            model_name='dailyrecommendedthemev2',
            index=models.Index(fields=['snapshot_date', 'period_type', 'source'], name='idx_rec_theme_snap_src'),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendedthemev2',
            index=models.Index(fields=['source', 'reason_type', 'metric_value'], name='idx_rec_theme_src_metric'),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendedthemev2',
            index=models.Index(fields=['source_object_type', 'source_object_id'], name='idx_rec_theme_src_obj'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecommendedthemev2',
            constraint=models.UniqueConstraint(fields=('snapshot_date', 'period_type', 'source', 'reason_type', 'theme', 'source_object_type', 'source_object_id', 'source_date'), name='uniq_recommended_theme_snapshot'),
        ),
        migrations.AddField(
            model_name='recommendedthemeasin',
            name='recommended_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asins', to='theme.dailyrecommendedthemev2', verbose_name='推荐主题'),
        ),
        migrations.AddIndex(
            model_name='recommendedthemeasin',
            index=models.Index(fields=['recommended_theme', 'source_position'], name='idx_rec_asin_theme_pos'),
        ),
        migrations.AddIndex(
            model_name='recommendedthemeasin',
            index=models.Index(fields=['asin', 'launch_date'], name='idx_rec_asin_launch'),
        ),
        migrations.AddConstraint(
            model_name='recommendedthemeasin',
            constraint=models.UniqueConstraint(fields=('recommended_theme', 'asin'), name='uniq_recommended_theme_asin'),
        ),
    ]
