# Generated by Django 5.2.7 on 2026-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0031_dailyrecommendedthemev2_recommendedthemeasin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyrecommendedthemev2',
            name='uniq_recommended_theme_snapshot',
        ),
        migrations.RemoveIndex(
            model_name='dailyrecommendedthemev2',
            name='idx_rec_theme_snap_src',
        ),
        migrations.AddField(
            model_name='dailyrecommendedthemev2',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='品类'),
        ),
        migrations.AddField(
            model_name='recommendedthemeasin',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='品类'),
        ),
        migrations.AddIndex(
            model_name='dailyrecommendedthemev2',
            index=models.Index(fields=['snapshot_date', 'period_type', 'category', 'source'], name='idx_rec_theme_snap_cat'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecommendedthemev2',
            constraint=models.UniqueConstraint(fields=('snapshot_date', 'period_type', 'source', 'reason_type', 'category', 'theme', 'source_object_type', 'source_object_id', 'source_date'), name='uniq_recommended_theme_snapshot'),
        ),
    ]
