# Generated by Django 5.2.7 on 2026-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0032_remove_dailyrecommendedthemev2_uniq_recommended_theme_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonthemeclusternovelty',
            name='asin_change',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='今日新增主题数'),
        ),
    ]
