# Generated by Django 5.2.7 on 2026-04-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0033_amazonthemeclusternovelty_asin_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonthemeclusternovelty',
            name='asin_change',
        ),
        migrations.AddField(
            model_name='amazonthemecluster',
            name='asin_change',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='今日新增主题数'),
        ),
    ]
